apiVersion: v2
name: operator
description: Redpanda operator helm chart
type: application

# The operator helm chart is considered part of the operator itself. Therefore
# version == appVersion. Our charts' versions, don't include a leading `v`, so
# we match that precedence here.
version: 2.3.12-24.3.17
appVersion: v2.3.12-24.3.17

sources:
  - https://github.com/redpanda-data/redpanda-operator/tree/main/operator/chart
icon: https://go.redpanda.com/hubfs/Redpandas/operator-panda.png
maintainers:
  - name: redpanda-data
    url: https://github.com/orgs/redpanda-data/people

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://docs.redpanda.com
    - name: "Helm (>= 3.6.0)"
      url: https://helm.sh/docs/intro/install/
  artifacthub.io/images: |
    - name: redpanda-operator
      image: docker.redpanda.com/redpandadata/redpanda-operator:v2.3.12-24.3.17
    - name: configurator
      image: docker.redpanda.com/redpandadata/configurator:v2.3.12-24.3.17
    - name: redpanda
      image: docker.redpanda.com/redpandadata/redpanda:v24.3.14
  artifacthub.io/crds: |
    - kind: Redpanda
      version: v1alpha1
      name: redpanda
      displayName: Redpanda
      description: Define a Redpanda cluster
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Seamless Upgrades
