---
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: sasl
spec:
  clusterSpec:
    image:
      repository: docker.redpanda.com/redpandadata/redpanda-unstable
      tag: v25.2.1-rc7
    auth:
      sasl:
        enabled: true
        users:
          - name: superuser
            password: superpassword
            mechanism: SCRAM-SHA-512
    statefulset:
      replicas: 1
      sideCars:
        image:
          tag: dev
          repository: localhost/redpanda-operator
        controllers:
          image:
            tag: dev
            repository: localhost/redpanda-operator
