---
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: sasl
spec:
  clusterSpec:
    image:
      tag: v0.0.0-20251008git7a18f63
      repository: redpandadata/redpanda-nightly
    external:
      enabled: false
    auth:
      sasl:
        enabled: true
        users:
          - name: superuser
            password: superpassword
            mechanism: SCRAM-SHA-512
    statefulset:
      replicas: 1
      sideCars:
        image:
          tag: dev
          repository: localhost/redpanda-operator
        controllers:
          image:
            tag: dev
            repository: localhost/redpanda-operator
