// Copyright 2025 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0
//go:build !generate

// +gotohelm:ignore=true
//
// Code generated by genpartial DO NOT EDIT.
package chart

import (
	"github.com/redpanda-data/redpanda-operator/charts/console/v3"
)

type PartialValues struct {
	console.PartialValues "json:\",inline,omitempty\""
	Enabled               *bool              "json:\"enabled,omitempty\""
	Tests                 *PartialEnableable "json:\"tests,omitempty\""
}

type PartialEnableable struct {
	Enabled *bool "json:\"enabled,omitempty\""
}
