//go:build !ignore_autogenerated

// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowLink) DeepCopyInto(out *ShadowLink) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowLink.
func (in *ShadowLink) DeepCopy() *ShadowLink {
	if in == nil {
		return nil
	}
	out := new(ShadowLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShadowLink) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowLinkList) DeepCopyInto(out *ShadowLinkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShadowLink, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowLinkList.
func (in *ShadowLinkList) DeepCopy() *ShadowLinkList {
	if in == nil {
		return nil
	}
	out := new(ShadowLinkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShadowLinkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowLinkSpec) DeepCopyInto(out *ShadowLinkSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	in.TopicMetadataSyncOptions.DeepCopyInto(&out.TopicMetadataSyncOptions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowLinkSpec.
func (in *ShadowLinkSpec) DeepCopy() *ShadowLinkSpec {
	if in == nil {
		return nil
	}
	out := new(ShadowLinkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShadowLinkTopicMetadataSyncOptions) DeepCopyInto(out *ShadowLinkTopicMetadataSyncOptions) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.AutoCreateShadowTopicFilters != nil {
		in, out := &in.AutoCreateShadowTopicFilters, &out.AutoCreateShadowTopicFilters
		*out = make([]NameFilter, len(*in))
		copy(*out, *in)
	}
	if in.SyncedShadowTopicProperties != nil {
		in, out := &in.SyncedShadowTopicProperties, &out.SyncedShadowTopicProperties
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.StartOffset != nil {
		in, out := &in.StartOffset, &out.StartOffset
		*out = new(TopicMetadataSyncOffset)
		**out = **in
	}
	if in.StartOffsetTimestamp != nil {
		in, out := &in.StartOffsetTimestamp, &out.StartOffsetTimestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShadowLinkTopicMetadataSyncOptions.
func (in *ShadowLinkTopicMetadataSyncOptions) DeepCopy() *ShadowLinkTopicMetadataSyncOptions {
	if in == nil {
		return nil
	}
	out := new(ShadowLinkTopicMetadataSyncOptions)
	in.DeepCopyInto(out)
	return out
}
