//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	virtual "github.com/redpanda-data/redpanda-operator/operator/api/virtual"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ClusterRef)(nil), (*virtual.ClusterRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterRef_To_virtual_ClusterRef(a.(*ClusterRef), b.(*virtual.ClusterRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*virtual.ClusterRef)(nil), (*ClusterRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_virtual_ClusterRef_To_v1alpha1_ClusterRef(a.(*virtual.ClusterRef), b.(*ClusterRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShadowLink)(nil), (*virtual.ShadowLink)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShadowLink_To_virtual_ShadowLink(a.(*ShadowLink), b.(*virtual.ShadowLink), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*virtual.ShadowLink)(nil), (*ShadowLink)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_virtual_ShadowLink_To_v1alpha1_ShadowLink(a.(*virtual.ShadowLink), b.(*ShadowLink), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShadowLinkList)(nil), (*virtual.ShadowLinkList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShadowLinkList_To_virtual_ShadowLinkList(a.(*ShadowLinkList), b.(*virtual.ShadowLinkList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*virtual.ShadowLinkList)(nil), (*ShadowLinkList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_virtual_ShadowLinkList_To_v1alpha1_ShadowLinkList(a.(*virtual.ShadowLinkList), b.(*ShadowLinkList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShadowLinkSpec)(nil), (*virtual.ShadowLinkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShadowLinkSpec_To_virtual_ShadowLinkSpec(a.(*ShadowLinkSpec), b.(*virtual.ShadowLinkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*virtual.ShadowLinkSpec)(nil), (*ShadowLinkSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_virtual_ShadowLinkSpec_To_v1alpha1_ShadowLinkSpec(a.(*virtual.ShadowLinkSpec), b.(*ShadowLinkSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ShadowLinkStatus)(nil), (*virtual.ShadowLinkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ShadowLinkStatus_To_virtual_ShadowLinkStatus(a.(*ShadowLinkStatus), b.(*virtual.ShadowLinkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*virtual.ShadowLinkStatus)(nil), (*ShadowLinkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_virtual_ShadowLinkStatus_To_v1alpha1_ShadowLinkStatus(a.(*virtual.ShadowLinkStatus), b.(*ShadowLinkStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ClusterRef_To_virtual_ClusterRef(in *ClusterRef, out *virtual.ClusterRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_ClusterRef_To_virtual_ClusterRef is an autogenerated conversion function.
func Convert_v1alpha1_ClusterRef_To_virtual_ClusterRef(in *ClusterRef, out *virtual.ClusterRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterRef_To_virtual_ClusterRef(in, out, s)
}

func autoConvert_virtual_ClusterRef_To_v1alpha1_ClusterRef(in *virtual.ClusterRef, out *ClusterRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_virtual_ClusterRef_To_v1alpha1_ClusterRef is an autogenerated conversion function.
func Convert_virtual_ClusterRef_To_v1alpha1_ClusterRef(in *virtual.ClusterRef, out *ClusterRef, s conversion.Scope) error {
	return autoConvert_virtual_ClusterRef_To_v1alpha1_ClusterRef(in, out, s)
}

func autoConvert_v1alpha1_ShadowLink_To_virtual_ShadowLink(in *ShadowLink, out *virtual.ShadowLink, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_ShadowLinkSpec_To_virtual_ShadowLinkSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_ShadowLinkStatus_To_virtual_ShadowLinkStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ShadowLink_To_virtual_ShadowLink is an autogenerated conversion function.
func Convert_v1alpha1_ShadowLink_To_virtual_ShadowLink(in *ShadowLink, out *virtual.ShadowLink, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShadowLink_To_virtual_ShadowLink(in, out, s)
}

func autoConvert_virtual_ShadowLink_To_v1alpha1_ShadowLink(in *virtual.ShadowLink, out *ShadowLink, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_virtual_ShadowLinkSpec_To_v1alpha1_ShadowLinkSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_virtual_ShadowLinkStatus_To_v1alpha1_ShadowLinkStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_virtual_ShadowLink_To_v1alpha1_ShadowLink is an autogenerated conversion function.
func Convert_virtual_ShadowLink_To_v1alpha1_ShadowLink(in *virtual.ShadowLink, out *ShadowLink, s conversion.Scope) error {
	return autoConvert_virtual_ShadowLink_To_v1alpha1_ShadowLink(in, out, s)
}

func autoConvert_v1alpha1_ShadowLinkList_To_virtual_ShadowLinkList(in *ShadowLinkList, out *virtual.ShadowLinkList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]virtual.ShadowLink)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ShadowLinkList_To_virtual_ShadowLinkList is an autogenerated conversion function.
func Convert_v1alpha1_ShadowLinkList_To_virtual_ShadowLinkList(in *ShadowLinkList, out *virtual.ShadowLinkList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShadowLinkList_To_virtual_ShadowLinkList(in, out, s)
}

func autoConvert_virtual_ShadowLinkList_To_v1alpha1_ShadowLinkList(in *virtual.ShadowLinkList, out *ShadowLinkList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ShadowLink)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_virtual_ShadowLinkList_To_v1alpha1_ShadowLinkList is an autogenerated conversion function.
func Convert_virtual_ShadowLinkList_To_v1alpha1_ShadowLinkList(in *virtual.ShadowLinkList, out *ShadowLinkList, s conversion.Scope) error {
	return autoConvert_virtual_ShadowLinkList_To_v1alpha1_ShadowLinkList(in, out, s)
}

func autoConvert_v1alpha1_ShadowLinkSpec_To_virtual_ShadowLinkSpec(in *ShadowLinkSpec, out *virtual.ShadowLinkSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_ClusterRef_To_virtual_ClusterRef(&in.ClusterRef, &out.ClusterRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ShadowLinkSpec_To_virtual_ShadowLinkSpec is an autogenerated conversion function.
func Convert_v1alpha1_ShadowLinkSpec_To_virtual_ShadowLinkSpec(in *ShadowLinkSpec, out *virtual.ShadowLinkSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShadowLinkSpec_To_virtual_ShadowLinkSpec(in, out, s)
}

func autoConvert_virtual_ShadowLinkSpec_To_v1alpha1_ShadowLinkSpec(in *virtual.ShadowLinkSpec, out *ShadowLinkSpec, s conversion.Scope) error {
	if err := Convert_virtual_ClusterRef_To_v1alpha1_ClusterRef(&in.ClusterRef, &out.ClusterRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_virtual_ShadowLinkSpec_To_v1alpha1_ShadowLinkSpec is an autogenerated conversion function.
func Convert_virtual_ShadowLinkSpec_To_v1alpha1_ShadowLinkSpec(in *virtual.ShadowLinkSpec, out *ShadowLinkSpec, s conversion.Scope) error {
	return autoConvert_virtual_ShadowLinkSpec_To_v1alpha1_ShadowLinkSpec(in, out, s)
}

func autoConvert_v1alpha1_ShadowLinkStatus_To_virtual_ShadowLinkStatus(in *ShadowLinkStatus, out *virtual.ShadowLinkStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_ShadowLinkStatus_To_virtual_ShadowLinkStatus is an autogenerated conversion function.
func Convert_v1alpha1_ShadowLinkStatus_To_virtual_ShadowLinkStatus(in *ShadowLinkStatus, out *virtual.ShadowLinkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_ShadowLinkStatus_To_virtual_ShadowLinkStatus(in, out, s)
}

func autoConvert_virtual_ShadowLinkStatus_To_v1alpha1_ShadowLinkStatus(in *virtual.ShadowLinkStatus, out *ShadowLinkStatus, s conversion.Scope) error {
	return nil
}

// Convert_virtual_ShadowLinkStatus_To_v1alpha1_ShadowLinkStatus is an autogenerated conversion function.
func Convert_virtual_ShadowLinkStatus_To_v1alpha1_ShadowLinkStatus(in *virtual.ShadowLinkStatus, out *ShadowLinkStatus, s conversion.Scope) error {
	return autoConvert_virtual_ShadowLinkStatus_To_v1alpha1_ShadowLinkStatus(in, out, s)
}
