changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* {{.Body}}'
body:
  block: true
# All changes specify auto as 'patch' to avoid unintentional major or minor
# version bumps as those are handled manually.
kinds:
    - label: Added
      auto: patch
    - label: Changed
      auto: patch
    - label: Deprecated
      auto: patch
    - label: Removed
      auto: patch
    - label: Fixed
      auto: patch
newlines:
    afterChangelogHeader: 1
    beforeChangelogVersion: 1
    endOfVersion: 1
envPrefix: CHANGIE_
# Project keys and version separators are configured to align with the tagging
# semantics of multi-module repositories. `dir/of/module/v<version>`
# https://go.dev/wiki/Modules#what-are-multi-module-repositories
projectsVersionSeparator: "/"
projects:
- label: Redpanda Operator
  key: operator
  changelog: operator/CHANGELOG.md
  replacements:
    # Update operator's Chart.yaml
    - path: operator/chart/Chart.yaml
      find: '^version: .*$'
      replace: 'version: {{.VersionNoPrefix}}'
    - path: operator/chart/Chart.yaml
      find: '^appVersion: .*$'
      replace: 'appVersion: {{.Version}}'
    - path: operator/chart/Chart.yaml
      find: '/redpanda-operator:.*$'
      replace: '/redpanda-operator:{{.Version}}'
    # Update golden files of the operator chart itself.
    - path: operator/chart/testdata/*.golden.txtar
      find: '/chart: operator-v.*$'
      replace: '/chart: operator-{{.Version}}'
    - path: operator/chart/testdata/*.golden.txtar
      find: '/version: v.*$'
      replace: '/version: {{.Version}}'
    # TODO this mergie auto correction is very useful but it prevents from cutting operator release
    # Update references to the operator image in redpanda's values.yaml
    # The whitespace ensures we update both values without touching the redpanda tag.
    # It's fragile but all values are checked via unittests.
    #- path: charts/redpanda/values.yaml
    #  find: '^      tag: .*$'
    # replace: '      tag: {{.Version}}'
    #- path: charts/redpanda/values.yaml
    #  find: '^        tag: .*$'
    #  replace: '        tag: {{.Version}}'
    # Update golden files across the entire repo.
    # Changie uses go's filepath.Match which doesn't support ** globbing so
    # there's some repetition here.
    #- path: 'charts/redpanda/testdata/*.golden.txtar'
    #  find: 'image: docker.redpanda.com/redpandadata/redpanda-operator:v.*$'
    #  replace: 'image: docker.redpanda.com/redpandadata/redpanda-operator:{{.Version}}'
- label: Redpanda Helm Chart
  key: charts/redpanda
  replacements:
    # Update Chart.yaml
    - path: charts/redpanda/Chart.yaml
      find: '^version: .*$'
      replace: 'version: {{.VersionNoPrefix}}'
    # Update tests without having to re-run.
    - path: charts/redpanda/testdata/*.golden.txtar
      find: '/chart: redpanda-v.*$'
      replace: '/chart: redpanda-{{.VersionNoPrefix}}'
  changelog: charts/redpanda/CHANGELOG.md
- label: Console Helm Chart
  key: charts/console
  changelog: charts/console/CHANGELOG.md
- label: Connectors Helm Chart
  key: charts/connectors
  changelog: charts/connectors/CHANGELOG.md
