changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
# This nasty regex reformats "internal versions" to "external versions" the
# same way that ./ci/scripts/version.sh does.
# v$MAJOR.$MINOR.$PATCH-$PREREL+$METADATA -> v$MAJOR.$MINOR-k8s$PATCH-$PREREL+$METADATA
versionFormat: '## {{regexReplaceAll "^(v\\d+\\.\\d+)\\.(\\d+.*)$" .Version "${1}-k8s${2}"}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* {{.Body}}'
body:
  block: true
# All changes specify auto as 'patch' to avoid unintentional major or minor
# version bumps as those are handled manually.
kinds:
    - label: Added
      auto: patch
    - label: Changed
      auto: patch
    - label: Deprecated
      auto: patch
    - label: Removed
      auto: patch
    - label: Fixed
      auto: patch
newlines:
    afterChangelogHeader: 1
    beforeChangelogVersion: 1
    endOfVersion: 1
envPrefix: CHANGIE_
# Project keys and version separators are configured to align with the tagging
# semantics of multi-module repositories. `dir/of/module/v<version>`
# https://go.dev/wiki/Modules#what-are-multi-module-repositories
projectsVersionSeparator: "/"
projects:
- label: Redpanda Operator
  key: operator
  changelog: operator/CHANGELOG.md
- label: Redpanda Helm Chart
  key: charts/redpanda
  changelog: charts/redpanda/CHANGELOG.md
- label: Console Helm Chart
  key: charts/console
  changelog: charts/console/CHANGELOG.md
- label: Connectors Helm Chart
  key: charts/connectors
  changelog: charts/connectors/CHANGELOG.md
