project_name: redpanda-operator
builds:
  - id: redpanda-operator
    dir: ./src/go/k8s/
    main: ./cmd/main.go
    binary: redpanda-operator-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
      - GOPRIVATE=github.com/redpanda-data/flux-controller-shim
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

  - id: configurator
    dir: ./src/go/k8s/
    main: ./cmd/configurator/main.go
    binary: configurator-{{ .Os }}-{{ .Arch }}
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
      - GOPRIVATE=github.com/redpanda-data/flux-controller-shim
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

release:
  github:
    owner: redpanda-data
    name: redpanda-operator
  draft: true
  discussion_category_name: Releases
announce:
  skip: "true"
