apiVersion: v1
items:
- apiVersion: cluster.redpanda.com/v1alpha2
  kind: Console
  metadata:
    creationTimestamp: "2026-03-17T03:22:40Z"
    generation: 1
    name: basic
    namespace: testing-2janolh4tj
    resourceVersion: "1486"
    uid: ae60b4e5-3141-4c55-87c1-47dcec4172c8
  spec:
    cluster:
      clusterRef:
        name: basic
    secret: {}
- apiVersion: cluster.redpanda.com/v1alpha2
  kind: Console
  metadata:
    creationTimestamp: "2026-03-17T03:24:30Z"
    generation: 1
    name: console
    namespace: testing-2janolh4tj
    resourceVersion: "1618"
    uid: 1f93ed9e-8cbe-4ff7-ba21-5f9b9864cbb2
  spec:
    cluster:
      clusterRef:
        name: basic
kind: List
metadata:
  resourceVersion: ""
