#! /usr/bin/env bash

# Weird hack to get the location on disk of this script (The root of
# the repository).
ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Construct the path to `.build/bin` while respecting possible overrides and
# weird working directories (See Taskfile.yml).
LOCAL_BIN="$ROOT/${BUILD_ROOT:-.build}/bin"

# Ensure that $LOCAL_BIN exists as a directory.
if [ ! -d $LOCAL_BIN ]; then
	mkdir -p $LOCAL_BIN
fi

# Delegate to task with a corrected $PATH.
# See Taskfile.yml for more details.
PATH="$LOCAL_BIN:$PATH" task "$@"
