version: '3'

# if a task is referenced multiple times, only run it once
run: once

vars:
  SRC_DIR:
    sh: 'realpath {{default "." .SRC_DIR}}'
  BUILD_ROOT:
    sh: 'realpath {{default ".build" .BUILD_ROOT}}'

env:
  # Redpanda maintains a few private forks of fluxcd repositories (See go.mod
  # files). GOPRIVATE ensures that go mod commands will understand how to
  # access them.
  GOPRIVATE: 'github.com/redpanda-data/*'

includes:
  ci: taskfiles/ci.yml
  k8s: taskfiles/k8s.yml
  dev: taskfiles/dev.yml
  goreleaser: taskfiles/goreleaser.yml

tasks:
  lint:
    var:
      ARGS: ""
    cmds:
      # NB: go list -f takes a go template string, It needs to be escaped in
      # taskfile land to get properly passed to go list.
      - golangci-lint run $(go list -f '{{"{{.Dir}}"}}/...' -m) {{.ARGS}}

  lint-fix:
    cmds:
      - task: lint
        vars:
          ARGS: "--fix"

  fmt:
    cmds:
      - gofumpt -w ./

  generate:
    cmds:
      - task: k8s:generate
      - task: dev:update-licenses

  build:
    cmds:
      - task: build:binaries

  build:binaries:
    cmds:
      # TODO(chrisseto): Ditch goreleaser in favor of just go build in task
      # files. We're not using it for anything other than an arch build matrix.
      - task: goreleaser:build-operator-binaries

  build:images:
    cmds:
      - task: k8s:build-operator-images
