---
apiVersion: cluster.redpanda.com/v1alpha2
kind: User
metadata:
  name: myuser
  namespace: redpanda
spec:
  cluster:
    clusterRef:
      name: sasl
  authentication:
    password:
      valueFrom:
        secretKeyRef:
          name: myuser-password
          key: password
  authorization:
    acls:
      - type: allow
        resource:
          type: topic
          name: mytopic2
          patternType: prefixed
        operations:
          - Read
