---
# The following patch adds the spec.versions.v1beta2.schema.openAPIV3Schema.properties.spec.properties.timeout.default property
# that was removed
- op: add
  path: /spec/versions/1/schema/openAPIV3Schema/properties/spec/properties/timeout/default
  value: 60s
