---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: old-decommission
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets/status
    verbs:
      - patch
      - update
  - apiGroups:
      - cluster.redpanda.com
    resources:
      - redpandas
    verbs:
      - get
      - list
      - watch
