---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pipeline
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cluster.redpanda.com
    resources:
      - pipelines
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - cluster.redpanda.com
    resources:
      - pipelines/finalizers
    verbs:
      - update
  - apiGroups:
      - cluster.redpanda.com
    resources:
      - pipelines/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - cluster.redpanda.com
    resources:
      - redpandas
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
