---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvcunbinder
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - cluster.redpanda.com
    resources:
      - redpandas
      - stretchclusters
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - redpanda.vectorized.io
    resources:
      - clusters
    verbs:
      - get
      - list
      - watch
