---
# The following patch adds the spec.versions.v1beta2.schema.openAPIV3Schema.properties.status.properties.artifact.properties.checksum property that was removed
# apiVersion: apiextensions.k8s.io/v1
- op: replace
  path: /spec/versions/0/schema/openAPIV3Schema/properties/status/properties/artifact/properties/checksum
  value:
    type: string
    description: Checksum is the SHA256 checksum of the Artifact file (obsolete)
