// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

package v1alpha2

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// StretchCluster defines the CRD for StretchCluster configuration.
// +genclient
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:path=stretchclusters
// +kubebuilder:resource:shortName=stretch
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type==\"Ready\")].status",description=""
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.conditions[?(@.type==\"Ready\")].message",description=""
// +kubebuilder:printcolumn:name="License",type="string",JSONPath=".status.conditions[?(@.type==\"LicenseValid\")].message",description=""
type StretchCluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec StretchClusterSpec `json:"spec,omitempty"`
	// +kubebuilder:default={conditions: {{type: "Ready", status: "Unknown", reason: "NotReconciled", message: "Waiting for controller", lastTransitionTime: "1970-01-01T00:00:00Z"}, {type: "Healthy", status: "Unknown", reason: "NotReconciled", message: "Waiting for controller", lastTransitionTime: "1970-01-01T00:00:00Z"}, {type: "LicenseValid", status: "Unknown", reason: "NotReconciled", message: "Waiting for controller", lastTransitionTime: "1970-01-01T00:00:00Z"}, {type: "ResourcesSynced", status: "Unknown", reason: "NotReconciled", message: "Waiting for controller", lastTransitionTime: "1970-01-01T00:00:00Z"}, {type: "ConfigurationApplied", status: "Unknown", reason: "NotReconciled", message: "Waiting for controller", lastTransitionTime: "1970-01-01T00:00:00Z"}, {type: "Quiesced", status: "Unknown", reason: "NotReconciled", message: "Waiting for controller", lastTransitionTime: "1970-01-01T00:00:00Z"}, {type: "Stable", status: "Unknown", reason: "NotReconciled", message: "Waiting for controller", lastTransitionTime: "1970-01-01T00:00:00Z"}}}
	Status StretchClusterStatus `json:"status,omitempty"`
}

type StretchClusterSpec struct {
	// Customizes the labels `app.kubernetes.io/component=<nameOverride>-statefulset` and `app.kubernetes.io/name=<nameOverride>` on the StatefulSet Pods. The default is `redpanda`.
	NameOverride *string `json:"nameOverride,omitempty"`
	// Deprecated: use FullnameOverride (fullnameOverride).
	DeprecatedFullNameOverride string `json:"fullNameOverride,omitempty"`
	// Customizes the name of the StatefulSet and Services. The default is `redpanda`.
	FullnameOverride *string `json:"fullnameOverride,omitempty"`
	// Customizes the Kubernetes cluster domain. This domain is used to generate the internal domains of the StatefulSet Pods. For details, see https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#stable-network-id. The default is the `cluster.local` domain.
	ClusterDomain *string `json:"clusterDomain,omitempty"`
	// Assigns custom labels to all resources generated by the Redpanda Helm chart. Specify labels as key/value pairs.
	CommonLabels map[string]string `json:"commonLabels,omitempty"`
	// Specifies on which nodes a Pod should be scheduled. These key/value pairs ensure that Pods are scheduled onto nodes with the specified labels.
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
	// Specifies tolerations to allow Pods to be scheduled onto nodes where they otherwise wouldn’t.
	Tolerations []corev1.Toleration `json:"tolerations,omitempty"`

	// Defines the container image settings to use for the Redpanda cluster.
	Image *RedpandaImage `json:"image,omitempty"`
	// Specifies credentials for a private image repository. For details, see https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/.
	ImagePullSecrets []corev1.LocalObjectReference `json:"imagePullSecrets,omitempty"`

	// Defines an Enterprise license.
	Enterprise *Enterprise `json:"enterprise,omitempty"`

	// Defines rack awareness settings.
	RackAwareness *RackAwareness `json:"rackAwareness,omitempty"`

	// Defines authentication settings for listeners.
	Auth *Auth `json:"auth,omitempty"`

	// Defines TLS settings for listeners.
	TLS *TLS `json:"tls,omitempty"`

	// Defines external access settings.
	External *External `json:"external,omitempty"`

	// Defines the log level settings.
	Logging *Logging `json:"logging,omitempty"`

	// Defines the log level settings.
	AuditLogging *AuditLogging `json:"auditLogging,omitempty"`

	// Defines container resource settings.
	Resources *Resources `json:"resources,omitempty"`

	// Defines settings for the headless ClusterIP Service.
	Service *Service `json:"service,omitempty"`

	// Defines storage settings for the Redpanda data directory and the Tiered Storage cache.
	Storage *Storage `json:"storage,omitempty"`

	// Defines settings for the post-install hook, which runs after each install or upgrade. For example, this job is responsible for setting the Enterprise license, if specified.
	PostInstallJob *PostInstallJob `json:"post_install_job,omitempty"`

	// Defines settings for the post-upgrade hook, which runs after each update. For example, this job is responsible for setting cluster configuration properties and restarting services such as Schema Registry, if required.
	PostUpgradeJob *PostUpgradeJob `json:"post_upgrade_job,omitempty"`

	// Defines settings for the autotuner tool in Redpanda. The autotuner identifies the hardware configuration in the container and optimizes the Linux kernel to give you the best performance.
	Tuning *Tuning `json:"tuning,omitempty"`

	// Defines settings for listeners, including HTTP Proxy, Schema Registry, the Admin API and the Kafka API.
	Listeners *Listeners `json:"listeners,omitempty"`

	// Defines configuration properties supported by Redpanda that may not work correctly in a Kubernetes cluster. Changing these values from the defaults comes with some risk. Use these properties to customize various Redpanda configurations that are not available in the rest of properties. These values have no impact on the configuration or behavior of the Kubernetes objects deployed by operator, and therefore should not be modified for the purpose of configuring those objects. Instead, these settings get passed directly to the Redpanda binary at startup.
	Config *Config `json:"config,omitempty"`

	// Defines Role Based Access Control (RBAC) settings.
	RBAC *RBAC `json:"rbac,omitempty"`

	// Defines Service account settings.
	ServiceAccount *ServiceAccount `json:"serviceAccount,omitempty"`

	// Affinity constraints for scheduling Pods, can override this for
	// StatefulSets and Jobs. For details, see the [Kubernetes
	// documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity).
	Affinity *corev1.Affinity `json:"affinity,omitempty"`
}

type StretchClusterStatus struct {
	// Conditions holds the conditions for the StretchCluster.
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// NodePools contains information about the node pools associated
	// with this cluster.
	// +optional
	NodePools []EmbeddedNodePoolStatus `json:"nodePools,omitempty"`

	// ConfigVersion contains the configuration version written in
	// Redpanda used for restarting broker nodes as necessary.
	// +optional
	ConfigVersion string `json:"configVersion,omitempty"`
}

// +kubebuilder:object:root=true
type StretchClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StretchCluster `json:"items"`
}
