// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

package v1alpha2

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// StretchCluster defines the CRD for StretchCluster configuration.
// +genclient
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:path=stretchclusters
// +kubebuilder:resource:shortName=stretch
// +kubebuilder:printcolumn:name="Ready",type="string",JSONPath=".status.conditions[?(@.type==\"Ready\")].status",description=""
// +kubebuilder:printcolumn:name="Status",type="string",JSONPath=".status.conditions[?(@.type==\"Ready\")].message",description=""
// +kubebuilder:printcolumn:name="License",type="string",JSONPath=".status.conditions[?(@.type==\"LicenseValid\")].message",description=""
type StretchCluster struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec StretchClusterSpec `json:"spec,omitempty"`
	// +kubebuilder:default={conditions: {{type: "Ready", status: "Unknown", reason: "NotReconciled", message: "Waiting for controller", lastTransitionTime: "1970-01-01T00:00:00Z"}, {type: "Healthy", status: "Unknown", reason: "NotReconciled", message: "Waiting for controller", lastTransitionTime: "1970-01-01T00:00:00Z"}, {type: "LicenseValid", status: "Unknown", reason: "NotReconciled", message: "Waiting for controller", lastTransitionTime: "1970-01-01T00:00:00Z"}, {type: "ResourcesSynced", status: "Unknown", reason: "NotReconciled", message: "Waiting for controller", lastTransitionTime: "1970-01-01T00:00:00Z"}, {type: "ConfigurationApplied", status: "Unknown", reason: "NotReconciled", message: "Waiting for controller", lastTransitionTime: "1970-01-01T00:00:00Z"}, {type: "Quiesced", status: "Unknown", reason: "NotReconciled", message: "Waiting for controller", lastTransitionTime: "1970-01-01T00:00:00Z"}, {type: "Stable", status: "Unknown", reason: "NotReconciled", message: "Waiting for controller", lastTransitionTime: "1970-01-01T00:00:00Z"}}}
	Status StretchClusterStatus `json:"status,omitempty"`
}

type StretchClusterSpec struct {
	// Assigns custom labels to all resources generated by the operator. Specify labels as key/value pairs.
	CommonLabels map[string]string `json:"commonLabels,omitempty"`

	// Customizes the Kubernetes cluster domain. This domain is used to generate the internal domains of the StatefulSet Pods. The default is the `cluster.local` domain.
	ClusterDomain *string `json:"clusterDomain,omitempty"`

	// Defines the container image settings to use for the Redpanda cluster.
	Image *RedpandaImage `json:"image,omitempty"`
	// Specifies credentials for a private image repository. For details, see https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/.
	ImagePullSecrets []corev1.LocalObjectReference `json:"imagePullSecrets,omitempty"`

	// Defines an Enterprise license.
	Enterprise *Enterprise `json:"enterprise,omitempty"`

	// Defines rack awareness settings.
	RackAwareness *RackAwareness `json:"rackAwareness,omitempty"`

	// Defines authentication settings for listeners.
	Auth *Auth `json:"auth,omitempty"`

	// Defines TLS settings for listeners.
	TLS *TLS `json:"tls,omitempty"`

	// Defines external access settings.
	External *External `json:"external,omitempty"`

	// Defines the log level settings.
	Logging *StretchLogging `json:"logging,omitempty"`

	// Defines audit logging settings.
	AuditLogging *AuditLogging `json:"auditLogging,omitempty"`

	// Defines container resource settings.
	Resources *StretchResources `json:"resources,omitempty"`

	// Defines settings for the headless ClusterIP Service.
	Service *Service `json:"service,omitempty"`

	// Defines storage settings for the Redpanda data directory and the Tiered Storage cache.
	Storage *StretchStorage `json:"storage,omitempty"`

	// Defines settings for the autotuner tool in Redpanda.
	Tuning *StretchTuning `json:"tuning,omitempty"`

	// Defines settings for listeners, including HTTP Proxy, Schema Registry, the Admin API and the Kafka API.
	Listeners *StretchListeners `json:"listeners,omitempty"`

	// Defines configuration properties supported by Redpanda.
	Config *Config `json:"config,omitempty"`

	// Defines Role Based Access Control (RBAC) settings.
	RBAC *RBAC `json:"rbac,omitempty"`

	// Defines Service account settings.
	ServiceAccount *ServiceAccount `json:"serviceAccount,omitempty"`

	// Defines settings for monitoring Redpanda.
	Monitoring *Monitoring `json:"monitoring,omitempty"`
}

type StretchClusterStatus struct {
	// Conditions holds the conditions for the StretchCluster.
	// +optional
	Conditions []metav1.Condition `json:"conditions,omitempty"`

	// NodePools contains information about the node pools associated
	// with this cluster.
	// +optional
	NodePools []EmbeddedNodePoolStatus `json:"nodePools,omitempty"`

	// ConfigVersion contains the configuration version written in
	// Redpanda used for restarting broker nodes as necessary.
	// +optional
	ConfigVersion string `json:"configVersion,omitempty"`

	// LicenseStatus contains information about the current state of any
	// installed license in the Redpanda cluster.
	// +optional
	LicenseStatus *RedpandaLicenseStatus `json:"license,omitempty"`
}

// +kubebuilder:object:root=true
type StretchClusterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []StretchCluster `json:"items"`
}

// StretchResources defines container resource settings for stretch clusters.
//
// Forked from Resources: changed Limits/Requests from *map[corev1.ResourceName]resource.Quantity
// (pointer-to-map) to corev1.ResourceList (standard K8s type alias) for idiomatic usage.
type StretchResources struct {
	// Standard K8s resource limits.
	Limits corev1.ResourceList `json:"limits,omitempty"`
	// Standard K8s resource requests.
	Requests corev1.ResourceList `json:"requests,omitempty"`

	// Specifies the number of CPU cores.
	CPU *CPU `json:"cpu,omitempty"`
	// Specifies the amount of memory.
	Memory *Memory `json:"memory,omitempty"`
}

// StretchTuning defines autotuner settings for stretch clusters.
//
// Forked from Tuning: removed ExtraVolumeMounts and Resources fields which are
// init-container concerns (used by Statefulset.InitContainers.Tuning in the Helm chart)
// and have no meaning as cluster-level tuning configuration.
type StretchTuning struct {
	// Specifies the file path for ballast file.
	BallastFilePath *string `json:"ballast_file_path,omitempty"`
	// Defines the size of the ballast file.
	BallastFileSize *string `json:"ballast_file_size,omitempty"`
	// Specifies whether to increase the number of allowed asynchronous IO events.
	TuneAioEvents *bool `json:"tune_aio_events,omitempty"`
	// Specifies whether to create the ballast file.
	TuneBallastFile *bool `json:"tune_ballast_file,omitempty"`
	// Specifies whether to synchronize NTP.
	TuneClockSource *bool `json:"tune_clocksource,omitempty"`
	// Specifies the vendor, VM type, and storage device type that Redpanda runs on, in the format <vendor>:<vm>:<storage>.
	WellKnownIo *string `json:"well_known_io,omitempty"`
}

// StretchStorage configures storage for stretch clusters.
//
// Forked from Storage: uses StretchTiered instead of Tiered to pick up
// the cleaned-up StretchTieredConfig.
type StretchStorage struct {
	// Specifies the absolute path on the worker node to store the Redpanda data directory.
	HostPath *string `json:"hostPath,omitempty"`
	// Configures a PersistentVolumeClaim (PVC) template to create for each Pod.
	PersistentVolume *PersistentVolume `json:"persistentVolume,omitempty"`
	// Configures storage for the Tiered Storage cache.
	Tiered *StretchTiered `json:"tiered,omitempty"`
}

// StretchTiered configures tiered storage for stretch clusters.
//
// Forked from Tiered: uses StretchTieredConfig instead of TieredConfig.
type StretchTiered struct {
	// mountType: "none", "hostPath", "emptyDir", or "persistentVolume".
	MountType *string `json:"mountType,omitempty"`
	// Specifies the absolute path on the worker node to store the Tiered Storage cache.
	HostPath *string `json:"hostPath,omitempty"`
	// Configures a PersistentVolumeClaim (PVC) template for the Tiered Storage cache.
	PersistentVolume *PersistentVolume `json:"persistentVolume,omitempty"`
	// Configures Tiered Storage properties.
	Config *StretchTieredConfig `json:"config,omitempty"`
	// CredentialsSecretRef sets cloud_storage_secret_key and/or cloud_storage_access_key from a referenced Secret.
	CredentialsSecretRef *CredentialSecretRef `json:"credentialsSecretRef,omitempty"`
}

// StretchTieredConfig configures Tiered Storage properties for stretch clusters.
//
// Forked from TieredConfig: removed deprecated CloudStorageReconciliationIntervalMs
// (see https://docs.redpanda.com/current/reference/tunable-properties/#cloud_storage_reconciliation_interval_ms);
// replaced *apiutil.JSONBoolean with *bool for CloudStorageEnabled (JSONBoolean was a
// Helm-era hack to handle "true" vs true in values files).
type StretchTieredConfig struct {
	CloudStorageEnabled                     *bool   `json:"cloud_storage_enabled,omitempty"`
	CloudStorageAPIEndpoint                 *string `json:"cloud_storage_api_endpoint,omitempty"`
	CloudStorageAPIEndpointPort             *int    `json:"cloud_storage_api_endpoint_port,omitempty"`
	CloudStorageBucket                      *string `json:"cloud_storage_bucket,omitempty"`
	CloudStorageAzureContainer              *string `json:"cloud_storage_azure_container,omitempty"`
	CloudStorageAzureManagedIdentityID      *string `json:"cloud_storage_azure_managed_identity_id,omitempty"`
	CloudStorageAzureStorageAccount         *string `json:"cloud_storage_azure_storage_account,omitempty"`
	CloudStorageAzureSharedKey              *string `json:"cloud_storage_azure_shared_key,omitempty"`
	CloudStorageAzureADLSEndpoint           *string `json:"cloud_storage_azure_adls_endpoint,omitempty"`
	CloudStorageAzureADLSPort               *int    `json:"cloud_storage_azure_adls_port,omitempty"`
	CloudStorageCacheCheckInterval          *int    `json:"cloud_storage_cache_check_interval,omitempty"`
	CloudStorageCacheDirectory              *string `json:"cloud_storage_cache_directory,omitempty"`
	CloudStorageCacheSize                   *string `json:"cloud_storage_cache_size,omitempty"`
	CloudStorageCredentialsSource           *string `json:"cloud_storage_credentials_source,omitempty"`
	CloudStorageDisableTLS                  *bool   `json:"cloud_storage_disable_tls,omitempty"`
	CloudStorageEnableRemoteRead            *bool   `json:"cloud_storage_enable_remote_read,omitempty"`
	CloudStorageEnableRemoteWrite           *bool   `json:"cloud_storage_enable_remote_write,omitempty"`
	CloudStorageInitialBackoffMs            *int    `json:"cloud_storage_initial_backoff_ms,omitempty"`
	CloudStorageManifestUploadTimeoutMs     *int    `json:"cloud_storage_manifest_upload_timeout_ms,omitempty"`
	CloudStorageMaxConnectionIdleTimeMs     *int    `json:"cloud_storage_max_connection_idle_time_ms,omitempty"`
	CloudStorageMaxConnections              *int    `json:"cloud_storage_max_connections,omitempty"`
	CloudStorageRegion                      *string `json:"cloud_storage_region,omitempty"`
	CloudStorageSegmentMaxUploadIntervalSec *int    `json:"cloud_storage_segment_max_upload_interval_sec,omitempty"`
	CloudStorageSegmentUploadTimeoutMs      *int    `json:"cloud_storage_segment_upload_timeout_ms,omitempty"`
	CloudStorageTrustFile                   *string `json:"cloud_storage_trust_file,omitempty"`
	CloudStorageUploadCtrlDCoeff            *int    `json:"cloud_storage_upload_ctrl_d_coeff,omitempty"`
	CloudStorageUploadCtrlMaxShares         *int    `json:"cloud_storage_upload_ctrl_max_shares,omitempty"`
	CloudStorageUploadCtrlMinShares         *int    `json:"cloud_storage_upload_ctrl_min_shares,omitempty"`
	CloudStorageUploadCtrlPCoeff            *int    `json:"cloud_storage_upload_ctrl_p_coeff,omitempty"`
	CloudStorageUploadCtrlUpdateIntervalMs  *int    `json:"cloud_storage_upload_ctrl_update_interval_ms,omitempty"`
}

// StretchLogging defines log level settings for stretch clusters.
//
// Forked from Logging: uses StretchUsageStats instead of UsageStats.
type StretchLogging struct {
	// Specifies the log level.
	LogLevel *string `json:"logLevel,omitempty"`
	// Defines settings for usage statistics reporting.
	UsageStats *StretchUsageStats `json:"usageStats,omitempty"`
}

// StretchUsageStats defines usage statistics settings for stretch clusters.
//
// Forked from UsageStats: removed deprecated Organization field and unused ClusterID field.
type StretchUsageStats struct {
	// Specifies whether usage statistics are enabled.
	Enabled *bool `json:"enabled,omitempty"`
}

// StretchListeners configures listener settings for stretch clusters.
//
// Forked from Listeners: uses StretchAPIListener (collapsed from Admin, HTTP,
// Kafka, SchemaRegistry — all identical after removing deprecated KafkaEndpoint
// from HTTP and SchemaRegistry) and StretchRPC.
type StretchListeners struct {
	// Configures settings for the Admin API listeners.
	Admin *StretchAPIListener `json:"admin,omitempty"`
	// Configures settings for the HTTP Proxy listeners.
	HTTP *StretchAPIListener `json:"http,omitempty"`
	// Configures settings for the Kafka API listeners.
	Kafka *StretchAPIListener `json:"kafka,omitempty"`
	// Configures settings for the RPC API listener.
	RPC *StretchRPC `json:"rpc,omitempty"`
	// Configures settings for the Schema Registry listeners.
	SchemaRegistry *StretchAPIListener `json:"schemaRegistry,omitempty"`
}

// StretchListenerTLS configures TLS for a listener in stretch clusters.
//
// Forked from ListenerTLS: removed deprecated SecretRef field (had no effect).
type StretchListenerTLS struct {
	// References a specific certificate for the listener.
	Cert *string `json:"cert,omitempty"`
	// Specifies whether TLS is enabled for the listener.
	Enabled *bool `json:"enabled,omitempty"`
	// Indicates whether client authentication (mTLS) is required.
	RequireClientAuth *bool `json:"requireClientAuth,omitempty"`
	// TrustStore allows setting the `truststore_path` on this listener.
	TrustStore *TrustStore `json:"trustStore,omitempty"`
}

// StretchListener configures a single listener in stretch clusters.
//
// Forked from Listener: references StretchListenerTLS instead of ListenerTLS.
type StretchListener struct {
	// Specifies whether this Listener is enabled.
	Enabled *bool `json:"enabled,omitempty"`
	// Specifies the authentication method for this listener.
	AuthenticationMethod *string `json:"authenticationMethod,omitempty"`
	AppProtocol          *string `json:"appProtocol,omitempty"`
	// Specifies the container port number for this listener.
	Port *int32 `json:"port,omitempty"`
	// Configures TLS settings for the internal listener.
	TLS *StretchListenerTLS `json:"tls,omitempty"`
	// Specifies the template used for generating the advertised addresses of Services.
	PrefixTemplate *string `json:"prefixTemplate,omitempty"`
}

// StretchExternalListener configures an external listener in stretch clusters.
//
// Forked from ExternalListener: embeds StretchListener instead of Listener.
type StretchExternalListener struct {
	StretchListener `json:",inline"`

	// Specifies the network port that the external Service listens on.
	AdvertisedPorts []int32 `json:"advertisedPorts,omitempty"`
	NodePort        *int32  `json:"nodePort,omitempty"`
}

// StretchRPC configures the RPC API listener for stretch clusters.
//
// Forked from RPC: references StretchListenerTLS instead of ListenerTLS.
type StretchRPC struct {
	// Specifies the container port number for the internal listener.
	Port *int `json:"port,omitempty"`
	// Configures TLS settings for the internal listener.
	TLS *StretchListenerTLS `json:"tls,omitempty"`
}

// StretchAPIListener configures an API listener (Admin, HTTP, Kafka, SchemaRegistry)
// for stretch clusters.
//
// Collapsed from Admin, HTTP, Kafka, SchemaRegistry — all identical after removing
// deprecated KafkaEndpoint field from HTTP and SchemaRegistry (was not respected)
// and deprecated SecretRef from ListenerTLS (had no effect).
type StretchAPIListener struct {
	StretchListener `json:",inline"`

	// Defines settings for the external listeners.
	External map[string]*StretchExternalListener `json:"external,omitempty"`
}
