steps:
  - key: k8s-operator-tests-with-flags
    if: |
      build.env("NIGHTLY_RELEASE") != "true" &&
      build.tag == null ||
      build.env("K8S_NIGHTLY") == "1"
    label: K8s Operator tests with flags
    timeout_in_minutes: 180
    notify:
      - github_commit_status:
          context: k8s-operator-tests-with-flags
    commands:
      - |
        TAG_NAME=$(ci/scripts/tag-check.sh) ./ci/scripts/run-in-nix-docker.sh task ci:run-k8s-tests-with-flags
    agents:
      queue: v6-amd64-builders-m6id
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/active_directory
            - secret-id: sdlc/prod/buildkite/buildkite_analytics_token
            - secret-id: sdlc/prod/buildkite/buildkite_api_token
            - secret-id: sdlc/prod/buildkite/cdt_gcp
            - secret-id: sdlc/prod/buildkite/cdt_runner_aws
            - secret-id: sdlc/prod/buildkite/ci_db
            - secret-id: sdlc/prod/buildkite/cloudsmith
            - secret-id: sdlc/prod/buildkite/dockerhub
            - secret-id: sdlc/prod/buildkite/gh_token
            - secret-id: sdlc/prod/buildkite/github_api_token
            - secret-id: sdlc/prod/buildkite/grafana_token
            - secret-id: sdlc/prod/buildkite/redpanda_sample_license
            - secret-id: sdlc/prod/buildkite/redpanda_second_sample_license
            - secret-id: sdlc/prod/buildkite/rpk_test_client
            - secret-id: sdlc/prod/buildkite/seceng_audit_aws
            - secret-id: sdlc/prod/buildkite/slack_vbot_token
            - secret-id: sdlc/prod/buildkite/teleport_bot_token
            - secret-id: sdlc/prod/buildkite/test_result_dsn
      - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
          message: ":cloud: K8s Operator tests with flags Job failed"
          channel_name: "kubernetes-tests"
          slack_token_env_var_name: "SLACK_VBOT_TOKEN"
          conditions:
            failed: true
            branches:
              - main