---
env:
  BRANCH_NAME: $BUILDKITE_BRANCH
  PULL_REQUEST: $BUILDKITE_PULL_REQUEST
  PULL_REQUEST_BASE_BRANCH_NAME: $BUILDKITE_PULL_REQUEST_BASE_BRANCH
  PIPELINE_NAME: $BUILDKITE_PIPELINE_NAME
  REDPANDA_GITREF: ${REDPANDA_COMMIT:-}
  # CI run podman instead of linux. testcontainer's ryuk is reported to not
  # work well with podman.
  TESTCONTAINERS_RYUK_DISABLED: "true"
# pipeline.yml is the "entrypoint" for all BuildKite pipelines in the operator
# repo. As such, it is executed for ANY trigger (e.g. PR update/created, Tag
# updated/created, Schedule run). Use `if`s to delegate to specific pipeline
# from this file and try to adhere to the below rules.
#
# Do:
# - Use `gen` to generate pipeline files.
# - Use `if` to gate the execution of pipelines.
# - Include a human readable explanation of `if` gates.
# - Separate pipelines into distinct files and use `buildkite-agent pipeline upload`.
# - Chain together tasks (e.g. `task ci:setup ci:run-test ci:tear-down).
#
# Do not:
# - Use taskfile to gate execution of steps.
# - Have a pipeline serve multiple purposes.
steps:
  # ci-entry-point kicks off the complete operator test suite.
  # It is responsible for blocking or allowing GitHub PRs to be merged.
  - key: ci-entry-point
    label: Operator CI Entrypoint
    agents:
      queue: pipeline-uploader
    # Run for:
    # - all pull requests that aren't from forks.
    # - nightly test schedule
    if: |
      (build.pull_request.id != null && !build.pull_request.repository.fork) || (build.source == "schedule" && build.env("K8S_NIGHTLY") == "1")
    command: buildkite-agent pipeline upload .buildkite/testsuite.yml

  - key: release-nightly
    label: ":gandalf: Nightly Operator release"
    timeout_in_minutes: 10
    agents:
      queue: v6-amd64-builders-m6id
    commands:
      - |
        TAG_NAME=$(ci/scripts/tag-check.sh) ./ci/scripts/run-in-nix-docker.sh task ci:configure ci:publish-k8s-nightly-artifacts
    if: build.branch == "main" && build.source == "schedule" && build.env("NIGHTLY_RELEASE") == "true"
    plugins:
      - seek-oss/aws-sm#v2.3.2: &aws-sm-plugin
          json-to-env:
            - secret-id: sdlc/prod/buildkite/buildkite_analytics_token
            - secret-id: sdlc/prod/buildkite/buildkite_api_token
            - secret-id: sdlc/prod/buildkite/dockerhub
            - secret-id: sdlc/prod/buildkite/gh_token
            - secret-id: sdlc/prod/buildkite/github_api_token
            - secret-id: sdlc/prod/buildkite/redpanda_sample_license
            - secret-id: sdlc/prod/buildkite/redpanda_second_sample_license
            - secret-id: sdlc/prod/buildkite/slack_vbot_token
      - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
          message: "Nightly release failed"
          channel_name: "kubernetes-tests"
          slack_token_env_var_name: "SLACK_VBOT_TOKEN"
          conditions:
            failed: true
            branches:
              - main

  # Legacy pipeline that appears to be responsible for minting releases,
  # provided that kuttl-v1 tests pass.
  # TODO: Scope this to just producing releases, both nightly and on tag.
  - key: k8s-operator
    label: Operator v1 E2E tests or release
    timeout_in_minutes: 180
    if: build.env("NIGHTLY_RELEASE") != "true" && build.pull_request.id == null
    commands:
      - |
        TAG_NAME=$(ci/scripts/tag-check.sh) ./ci/scripts/run-in-nix-docker.sh task ci:configure ci:k8s
    agents:
      queue: v6-amd64-builders-m6id
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/active_directory
            - secret-id: sdlc/prod/buildkite/buildkite_analytics_token
            - secret-id: sdlc/prod/buildkite/buildkite_api_token
            - secret-id: sdlc/prod/buildkite/cdt_gcp
            - secret-id: sdlc/prod/buildkite/cdt_runner_aws
            - secret-id: sdlc/prod/buildkite/ci_db
            - secret-id: sdlc/prod/buildkite/cloudsmith
            - secret-id: sdlc/prod/buildkite/dockerhub
            - secret-id: sdlc/prod/buildkite/gh_token
            - secret-id: sdlc/prod/buildkite/github_api_token
            - secret-id: sdlc/prod/buildkite/grafana_token
            - secret-id: sdlc/prod/buildkite/redpanda_sample_license
            - secret-id: sdlc/prod/buildkite/redpanda_second_sample_license
            - secret-id: sdlc/prod/buildkite/rpk_test_client
            - secret-id: sdlc/prod/buildkite/seceng_audit_aws
            - secret-id: sdlc/prod/buildkite/slack_vbot_token
            - secret-id: sdlc/prod/buildkite/teleport_bot_token
            - secret-id: sdlc/prod/buildkite/test_result_dsn
      - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
          message: ":cloud: K8s Operator v1 e2e tests Jobs failed"
          channel_name: "kubernetes-tests"
          slack_token_env_var_name: "SLACK_VBOT_TOKEN"
          conditions:
            failed: true
            branches:
              - main
