---
env:
  BRANCH_NAME: $BUILDKITE_BRANCH
  PULL_REQUEST: $BUILDKITE_PULL_REQUEST
  PULL_REQUEST_BASE_BRANCH_NAME: $BUILDKITE_PULL_REQUEST_BASE_BRANCH
  PIPELINE_NAME: $BUILDKITE_PIPELINE_NAME
  REDPANDA_GITREF: ${REDPANDA_COMMIT:-}
  # CI run podman instead of linux. testcontainer's ryuk is reported to not
  # work well with podman.
  TESTCONTAINERS_RYUK_DISABLED: "true"
steps:
  - key: release-nightly
    label: ":gandalf: Nightly Operator release"
    timeout_in_minutes: 10
    agents:
      queue: k8s-builders
    commands:
      - |
        TAG_NAME=$(ci/scripts/tag-check.sh) ./ci/scripts/run-in-nix-docker.sh task ci:publish-k8s-nightly-artifacts
    if: build.branch == "main" && build.source == "schedule" && build.env("NIGHTLY_RELEASE") == "true"
    plugins:
      - seek-oss/aws-sm#v2.3.2: &aws-sm-plugin
          json-to-env:
            - secret-id: sdlc/prod/buildkite/buildkite_analytics_token
            - secret-id: sdlc/prod/buildkite/buildkite_api_token
            - secret-id: sdlc/prod/buildkite/dockerhub
            - secret-id: sdlc/prod/buildkite/gh_token
            - secret-id: sdlc/prod/buildkite/github_api_token
            - secret-id: sdlc/prod/buildkite/redpanda_sample_license
            - secret-id: sdlc/prod/buildkite/redpanda_second_sample_license
            - secret-id: sdlc/prod/buildkite/slack_vbot_token
      - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
          message: "Nightly release failed"
          channel_name: "kubernetes-tests"
          slack_token_env_var_name: "SLACK_VBOT_TOKEN"
          conditions:
            failed: true
            branches:
              - main

  - key: operator-lint
    label: Lint operator repo
    if: |
      build.env("NIGHTLY_RELEASE") != "true" &&
      build.tag == null ||
      build.env("K8S_NIGHTLY") == "1"
    timeout_in_minutes: 30
    notify:
      - github_commit_status:
          context: charts-lint
    commands:
      - |
        TAG_NAME=$(ci/scripts/tag-check.sh) ./ci/scripts/run-in-nix-docker.sh task ci:lint
      - echo '~~~ pipeline upload unit tests' && buildkite-agent pipeline upload .buildkite/unit-tests.yml
      - echo '~~~ pipeline upload operator e2e tests with flags' && buildkite-agent pipeline upload .buildkite/operator-e2e-tests-with-flags.yml
      - echo '~~~ pipeline upload operator integration tests' && buildkite-agent pipeline upload .buildkite/integration-test.yml
      - echo '~~~ pipeline upload operator v2 e2e tests' && buildkite-agent pipeline upload .buildkite/operator-v2-tests.yml
    agents:
      queue: v6-amd64-builders-m6id
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/github_api_token
            - secret-id: sdlc/prod/buildkite/slack_vbot_token
      - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
          message: ":cloud: K8S operator lint Jobs failed"
          channel_name: "kubernetes-tests"
          slack_token_env_var_name: "SLACK_VBOT_TOKEN"
          conditions:
            failed: true
            branches:
              - main

  - key: k8s-operator
    label: Operator v1 E2E tests or release
    timeout_in_minutes: 180
    if: build.env("NIGHTLY_RELEASE") != "true"
    notify:
      - github_commit_status:
          context: k8s-operator-e2e-tests
    commands:
      - |
        TAG_NAME=$(ci/scripts/tag-check.sh) ./ci/scripts/run-in-nix-docker.sh task ci:k8s
    agents:
      queue: v6-amd64-builders-m6id
    plugins:
      - seek-oss/aws-sm#v2.3.2:
          json-to-env:
            - secret-id: sdlc/prod/buildkite/active_directory
            - secret-id: sdlc/prod/buildkite/buildkite_analytics_token
            - secret-id: sdlc/prod/buildkite/buildkite_api_token
            - secret-id: sdlc/prod/buildkite/cdt_gcp
            - secret-id: sdlc/prod/buildkite/cdt_runner_aws
            - secret-id: sdlc/prod/buildkite/ci_db
            - secret-id: sdlc/prod/buildkite/cloudsmith
            - secret-id: sdlc/prod/buildkite/dockerhub
            - secret-id: sdlc/prod/buildkite/gh_token
            - secret-id: sdlc/prod/buildkite/github_api_token
            - secret-id: sdlc/prod/buildkite/grafana_token
            - secret-id: sdlc/prod/buildkite/redpanda_sample_license
            - secret-id: sdlc/prod/buildkite/redpanda_second_sample_license
            - secret-id: sdlc/prod/buildkite/rpk_test_client
            - secret-id: sdlc/prod/buildkite/seceng_audit_aws
            - secret-id: sdlc/prod/buildkite/slack_vbot_token
            - secret-id: sdlc/prod/buildkite/teleport_bot_token
            - secret-id: sdlc/prod/buildkite/test_result_dsn
      - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
          message: ":cloud: K8s Operator v1 e2e tests Jobs failed"
          channel_name: "kubernetes-tests"
          slack_token_env_var_name: "SLACK_VBOT_TOKEN"
          conditions:
            failed: true
            branches:
              - main
