---
env:
  BRANCH_NAME: $BUILDKITE_BRANCH
  PULL_REQUEST: $BUILDKITE_PULL_REQUEST
  PULL_REQUEST_BASE_BRANCH_NAME: $BUILDKITE_PULL_REQUEST_BASE_BRANCH
  PIPELINE_NAME: $BUILDKITE_PIPELINE_NAME
  REDPANDA_GITREF: ${REDPANDA_COMMIT:-}
  # CI run podman instead of linux. testcontainer's ryuk is reported to not
  # work well with podman.
  TESTCONTAINERS_RYUK_DISABLED: "true"
steps:
  - key: chart-lint
    label: Charts lint
    if: |
      build.env("NIGHTLY_RELEASE") != "true" &&
      build.tag == null ||
      build.env("K8S_NIGHTLY") == "1"
    timeout_in_minutes: 30
    notify:
      - github_commit_status:
          context: charts-lint
    commands:
      - |
        TAG_NAME=$(ci/scripts/tag-check.sh) ./ci/scripts/run-in-nix-docker.sh task ci:lint
    agents:
      queue: v6-amd64-builders-m6id
    plugins:
      - seek-oss/aws-sm#v2.3.2: &aws-sm-plugin
          json-to-env:
            - secret-id: sdlc/prod/buildkite/github_api_token
            - secret-id: sdlc/prod/buildkite/slack_vbot_token
      - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
          message: ":cloud: K8S Chart lint Jobs failed"
          channel_name: "kubernetes-tests"
          slack_token_env_var_name: "SLACK_VBOT_TOKEN"
          conditions:
            failed: true
            branches:
              - main

  - group: Charts tests
    if: |
      build.env("NIGHTLY_RELEASE") != "true" &&
      build.tag == null ||
      build.env("K8S_NIGHTLY") == "1"
    steps:
      - key: charts-tests
        label: Charts tests {{matrix.testpackagename}}
        timeout_in_minutes: 20
        notify:
          - github_commit_status:
              context: charts-tests
        commands:
          - |
            TAG_NAME=$(ci/scripts/tag-check.sh) ./ci/scripts/run-in-nix-docker.sh task ci:pkg:unit-tests PKG_NAME={{matrix.testpackagename}}
        agents:
          queue: v6-amd64-builders-m6id
        matrix:
          setup:
            testpackagename:
              - charts
              - genpartial
              - genschema
              - gotohelm
              - pkg
        plugins:
          - seek-oss/aws-sm#v2.3.2: &aws-sm-plugin
              json-to-env:
                - secret-id: sdlc/prod/buildkite/github_api_token
                - secret-id: sdlc/prod/buildkite/redpanda_sample_license
                - secret-id: sdlc/prod/buildkite/redpanda_second_sample_license
                - secret-id: sdlc/prod/buildkite/slack_vbot_token
          - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
              message: ":cloud: K8S Chart tests {{matrix.testpackagename}} Jobs failed"
              channel_name: "kubernetes-tests"
              slack_token_env_var_name: "SLACK_VBOT_TOKEN"
              conditions:
                failed: true
                branches:
                  - main
      - key: annotate-charts-tests
        label: Parse {{matrix.testpackagename}} tests
        plugins:
          - junit-annotate#v2.4.1:
              artifacts: work/{{matrix.testpackagename}}.xml
              report-slowest: 20
        timeout_in_minutes: 0
        agents:
          queue: pipeline-uploader
        depends_on: charts-tests
        allow_dependency_failure: true
        matrix:
          setup:
            testpackagename:
              - charts
              - genpartial
              - genschema
              - gotohelm
              - pkg

  - key: release-nightly
    label: ":gandalf: Nightly Operator release"
    timeout_in_minutes: 10
    agents:
      queue: k8s-builders
    commands:
      - |
        TAG_NAME=$(ci/scripts/tag-check.sh) ./ci/scripts/run-in-nix-docker.sh task ci:publish-k8s-nightly-artifacts
    if: build.branch == "main" && build.source == "schedule" && build.env("NIGHTLY_RELEASE") == "true"
    plugins:
      - seek-oss/aws-sm#v2.3.2: &aws-sm-plugin
          json-to-env:
            - secret-id: sdlc/prod/buildkite/buildkite_analytics_token
            - secret-id: sdlc/prod/buildkite/buildkite_api_token
            - secret-id: sdlc/prod/buildkite/dockerhub
            - secret-id: sdlc/prod/buildkite/gh_token
            - secret-id: sdlc/prod/buildkite/github_api_token
            - secret-id: sdlc/prod/buildkite/redpanda_sample_license
            - secret-id: sdlc/prod/buildkite/redpanda_second_sample_license
            - secret-id: sdlc/prod/buildkite/slack_vbot_token
      - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
          message: "Nightly release failed"
          channel_name: "kubernetes-tests"
          slack_token_env_var_name: "SLACK_VBOT_TOKEN"
          conditions:
            failed: true
            branches:
              - main

  - key: k8s-operator
    label: K8s Operator
    timeout_in_minutes: 180
    if: build.env("NIGHTLY_RELEASE") != "true"
    notify:
      - github_commit_status:
          context: k8s-operator
    commands:
      - |
        TAG_NAME=$(ci/scripts/tag-check.sh) ./ci/scripts/run-in-nix-docker.sh task ci:k8s
    agents:
      queue: v6-amd64-builders-m6id
    plugins:
      - seek-oss/aws-sm#v2.3.2: &aws-sm-plugin
          json-to-env:
            - secret-id: sdlc/prod/buildkite/active_directory
            - secret-id: sdlc/prod/buildkite/buildkite_analytics_token
            - secret-id: sdlc/prod/buildkite/buildkite_api_token
            - secret-id: sdlc/prod/buildkite/cdt_gcp
            - secret-id: sdlc/prod/buildkite/cdt_runner_aws
            - secret-id: sdlc/prod/buildkite/ci_db
            - secret-id: sdlc/prod/buildkite/cloudsmith
            - secret-id: sdlc/prod/buildkite/dockerhub
            - secret-id: sdlc/prod/buildkite/gh_token
            - secret-id: sdlc/prod/buildkite/github_api_token
            - secret-id: sdlc/prod/buildkite/grafana_token
            - secret-id: sdlc/prod/buildkite/redpanda_sample_license
            - secret-id: sdlc/prod/buildkite/redpanda_second_sample_license
            - secret-id: sdlc/prod/buildkite/rpk_test_client
            - secret-id: sdlc/prod/buildkite/seceng_audit_aws
            - secret-id: sdlc/prod/buildkite/slack_vbot_token
            - secret-id: sdlc/prod/buildkite/teleport_bot_token
            - secret-id: sdlc/prod/buildkite/test_result_dsn
      - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
          message: ":cloud: K8s Operator v1 Jobs failed"
          channel_name: "kubernetes-tests"
          slack_token_env_var_name: "SLACK_VBOT_TOKEN"
          conditions:
            failed: true
            branches:
              - main

  - key: k8s-operator-tests-with-flags
    if: |
      build.env("NIGHTLY_RELEASE") != "true" &&
      build.tag == null ||
      build.env("K8S_NIGHTLY") == "1"
    label: K8s Operator tests with flags
    timeout_in_minutes: 180
    notify:
      - github_commit_status:
          context: k8s-operator-tests-with-flags
    commands:
      - |
        TAG_NAME=$(ci/scripts/tag-check.sh) ./ci/scripts/run-in-nix-docker.sh task ci:run-k8s-tests-with-flags
    agents:
      queue: v6-amd64-builders-m6id
    plugins:
      - seek-oss/aws-sm#v2.3.2: &aws-sm-plugin
          json-to-env:
            - secret-id: sdlc/prod/buildkite/active_directory
            - secret-id: sdlc/prod/buildkite/buildkite_analytics_token
            - secret-id: sdlc/prod/buildkite/buildkite_api_token
            - secret-id: sdlc/prod/buildkite/cdt_gcp
            - secret-id: sdlc/prod/buildkite/cdt_runner_aws
            - secret-id: sdlc/prod/buildkite/ci_db
            - secret-id: sdlc/prod/buildkite/cloudsmith
            - secret-id: sdlc/prod/buildkite/dockerhub
            - secret-id: sdlc/prod/buildkite/gh_token
            - secret-id: sdlc/prod/buildkite/github_api_token
            - secret-id: sdlc/prod/buildkite/grafana_token
            - secret-id: sdlc/prod/buildkite/redpanda_sample_license
            - secret-id: sdlc/prod/buildkite/redpanda_second_sample_license
            - secret-id: sdlc/prod/buildkite/rpk_test_client
            - secret-id: sdlc/prod/buildkite/seceng_audit_aws
            - secret-id: sdlc/prod/buildkite/slack_vbot_token
            - secret-id: sdlc/prod/buildkite/teleport_bot_token
            - secret-id: sdlc/prod/buildkite/test_result_dsn
      - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
          message: ":cloud: K8s Operator v1 Jobs failed"
          channel_name: "kubernetes-tests"
          slack_token_env_var_name: "SLACK_VBOT_TOKEN"
          conditions:
            failed: true
            branches:
              - main

  - group: K8s Operator v2 Jobs
    if: |
      build.env("NIGHTLY_RELEASE") != "true" &&
      build.tag == null ||
      build.env("K8S_NIGHTLY") == "1"
    steps:
      - key: k8s-operator-v2
        label: K8s Operator v2
        timeout: 100
        notify:
          - github_commit_status:
              context: k8s-operator-v2
        commands:
          - ./ci/scripts/run-in-nix-docker.sh task ci:k8s-v2
        agents:
          queue: v6-amd64-builders-m6id
        plugins:
          - seek-oss/aws-sm#v2.3.2: *aws-sm-plugin
          - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
              message: ":cloud: K8s Operator v2 Jobs failed"
              channel_name: "kubernetes-tests"
              slack_token_env_var_name: "SLACK_VBOT_TOKEN"
              conditions:
                failed: true
                branches:
                  - main
      - key: annotate-v2-testresults
        label: Parse Operator v2 Test Results
        plugins:
          - seek-oss/aws-sm#v2.3.2: *aws-sm-plugin
          - junit-annotate#v2.4.1:
              artifacts: work/operator/tests/_e2e_artifacts_v2/kuttl-report.xml
              report-slowest: 5
        timeout_in_minutes: 0
        agents:
          queue: pipeline-uploader
        depends_on: k8s-operator-v2
        allow_dependency_failure: true

  - group: K8s Operator v2 Helm Jobs
    if: |
      build.env("NIGHTLY_RELEASE") != "true" &&
      build.tag == null ||
      build.env("K8S_NIGHTLY") == "1"
    steps:
      - key: k8s-operator-v2-helm
        label: K8s Operator v2 Helm
        timeout_in_minutes: 50
        notify:
          - github_commit_status:
              context: k8s-operator-v2-helm
        commands:
          # - ./ci/scripts/run-in-nix-docker.sh task ci:k8s-v2-helm
          - mkdir -p operator/tests/_e2e_helm_artifacts_v2
          # The tests that are generated from `ci` folder of the Redpanda helm chart
          # generated too many test cases after introduction files with the `-novalues.yaml`
          # suffix. Those would not be taken by chart testing (`ct`) program, but
          # `hack/v2-helm-setup.sh` takes all files currently and disables only handful of them.

          - touch operator/tests/_e2e_helm_artifacts_v2/kuttl-report.xml
          - buildkite-agent artifact upload operator/tests/_e2e_helm_artifacts_v2/kuttl-report.xml
          - echo Noop
        agents:
          queue: v6-amd64-builders-m6id
        plugins:
          - seek-oss/aws-sm#v2.3.2: *aws-sm-plugin
          - https://$GITHUB_API_TOKEN@github.com/redpanda-data/step-slack-notify-buildkite-plugin.git#main:
              message: ":cloud: K8s Operator v2 Helm Jobs failed"
              channel_name: "kubernetes-tests"
              slack_token_env_var_name: "SLACK_VBOT_TOKEN"
              conditions:
                failed: true
                branches:
                  - main
      - key: annotate-v2-helm-testresults
        label: Parse Operator v2 Helm Test Results
        plugins:
          - seek-oss/aws-sm#v2.3.2: *aws-sm-plugin
          - junit-annotate#v2.0.2:
              artifacts: operator/tests/_e2e_helm_artifacts_v2/kuttl-report.xml
              report-slowest: 5
        timeout_in_minutes: 0
        agents:
          queue: pipeline-uploader
        depends_on: k8s-operator-v2-helm
        allow_dependency_failure: true
