//go:build !ignore_autogenerated

// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Auth) DeepCopyInto(out *Auth) {
	*out = *in
	if in.SASL != nil {
		in, out := &in.SASL, &out.SASL
		*out = new(SASL)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Auth.
func (in *Auth) DeepCopy() *Auth {
	if in == nil {
		return nil
	}
	out := new(Auth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapUser) DeepCopyInto(out *BootstrapUser) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Mechanism != nil {
		in, out := &in.Mechanism, &out.Mechanism
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapUser.
func (in *BootstrapUser) DeepCopy() *BootstrapUser {
	if in == nil {
		return nil
	}
	out := new(BootstrapUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerPoolSpec) DeepCopyInto(out *BrokerPoolSpec) {
	*out = *in
	in.EmbeddedBrokerPoolSpec.DeepCopyInto(&out.EmbeddedBrokerPoolSpec)
	in.ClusterRef.DeepCopyInto(&out.ClusterRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerPoolSpec.
func (in *BrokerPoolSpec) DeepCopy() *BrokerPoolSpec {
	if in == nil {
		return nil
	}
	out := new(BrokerPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerPoolStatus) DeepCopyInto(out *BrokerPoolStatus) {
	*out = *in
	out.EmbeddedBrokerPoolStatus = in.EmbeddedBrokerPoolStatus
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerPoolStatus.
func (in *BrokerPoolStatus) DeepCopy() *BrokerPoolStatus {
	if in == nil {
		return nil
	}
	out := new(BrokerPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPU) DeepCopyInto(out *CPU) {
	*out = *in
	if in.Cores != nil {
		in, out := &in.Cores, &out.Cores
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Overprovisioned != nil {
		in, out := &in.Overprovisioned, &out.Overprovisioned
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPU.
func (in *CPU) DeepCopy() *CPU {
	if in == nil {
		return nil
	}
	out := new(CPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Certificate) DeepCopyInto(out *Certificate) {
	*out = *in
	if in.IssuerRef != nil {
		in, out := &in.IssuerRef, &out.IssuerRef
		*out = new(IssuerRef)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretRef)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientSecretRef != nil {
		in, out := &in.ClientSecretRef, &out.ClientSecretRef
		*out = new(SecretRef)
		(*in).DeepCopyInto(*out)
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.CAEnabled != nil {
		in, out := &in.CAEnabled, &out.CAEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ApplyInternalDNSNames != nil {
		in, out := &in.ApplyInternalDNSNames, &out.ApplyInternalDNSNames
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Certificate.
func (in *Certificate) DeepCopy() *Certificate {
	if in == nil {
		return nil
	}
	out := new(Certificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConfigValue) DeepCopyInto(out *ClusterConfigValue) {
	*out = *in
	if in.Repr != nil {
		in, out := &in.Repr, &out.Repr
		*out = new(YAMLRepresentation)
		**out = **in
	}
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(corev1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalSecretRef != nil {
		in, out := &in.ExternalSecretRef, &out.ExternalSecretRef
		*out = new(string)
		**out = **in
	}
	if in.ExternalSecretRefSelector != nil {
		in, out := &in.ExternalSecretRefSelector, &out.ExternalSecretRefSelector
		*out = new(ConfigExternalSecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConfigValue.
func (in *ClusterConfigValue) DeepCopy() *ClusterConfigValue {
	if in == nil {
		return nil
	}
	out := new(ClusterConfigValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ClusterConfiguration) DeepCopyInto(out *ClusterConfiguration) {
	{
		in := &in
		*out = make(ClusterConfiguration, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConfiguration.
func (in ClusterConfiguration) DeepCopy() ClusterConfiguration {
	if in == nil {
		return nil
	}
	out := new(ClusterConfiguration)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRef) DeepCopyInto(out *ClusterRef) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRef.
func (in *ClusterRef) DeepCopy() *ClusterRef {
	if in == nil {
		return nil
	}
	out := new(ClusterRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	if in.RPK != nil {
		in, out := &in.RPK, &out.RPK
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraClusterConfiguration != nil {
		in, out := &in.ExtraClusterConfiguration, &out.ExtraClusterConfiguration
		*out = make(ClusterConfiguration, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Node != nil {
		in, out := &in.Node, &out.Node
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Tunable != nil {
		in, out := &in.Tunable, &out.Tunable
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.SchemaRegistryClient != nil {
		in, out := &in.SchemaRegistryClient, &out.SchemaRegistryClient
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.PandaProxyClient != nil {
		in, out := &in.PandaProxyClient, &out.PandaProxyClient
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigExternalSecretKeySelector) DeepCopyInto(out *ConfigExternalSecretKeySelector) {
	*out = *in
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigExternalSecretKeySelector.
func (in *ConfigExternalSecretKeySelector) DeepCopy() *ConfigExternalSecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(ConfigExternalSecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResources) DeepCopyInto(out *ContainerResources) {
	*out = *in
	if in.Max != nil {
		in, out := &in.Max, &out.Max
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Min != nil {
		in, out := &in.Min, &out.Min
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResources.
func (in *ContainerResources) DeepCopy() *ContainerResources {
	if in == nil {
		return nil
	}
	out := new(ContainerResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialSecretRef) DeepCopyInto(out *CredentialSecretRef) {
	*out = *in
	if in.AccessKey != nil {
		in, out := &in.AccessKey, &out.AccessKey
		*out = new(SecretWithConfigField)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretKey != nil {
		in, out := &in.SecretKey, &out.SecretKey
		*out = new(SecretWithConfigField)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialSecretRef.
func (in *CredentialSecretRef) DeepCopy() *CredentialSecretRef {
	if in == nil {
		return nil
	}
	out := new(CredentialSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddedBrokerPoolSpec) DeepCopyInto(out *EmbeddedBrokerPoolSpec) {
	*out = *in
	if in.AdditionalSelectorLabels != nil {
		in, out := &in.AdditionalSelectorLabels, &out.AdditionalSelectorLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.AdditionalRedpandaCmdFlags != nil {
		in, out := &in.AdditionalRedpandaCmdFlags, &out.AdditionalRedpandaCmdFlags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodTemplate != nil {
		in, out := &in.PodTemplate, &out.PodTemplate
		*out = (*in).DeepCopy()
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = (*in).DeepCopy()
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = new(PoolInitContainers)
		(*in).DeepCopyInto(*out)
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(RedpandaImage)
		(*in).DeepCopyInto(*out)
	}
	if in.SidecarImage != nil {
		in, out := &in.SidecarImage, &out.SidecarImage
		*out = new(RedpandaImage)
		(*in).DeepCopyInto(*out)
	}
	if in.InitContainerImage != nil {
		in, out := &in.InitContainerImage, &out.InitContainerImage
		*out = new(InitContainerImage)
		(*in).DeepCopyInto(*out)
	}
	if in.PersistentVolumeClaimRetentionPolicy != nil {
		in, out := &in.PersistentVolumeClaimRetentionPolicy, &out.PersistentVolumeClaimRetentionPolicy
		*out = new(v1.StatefulSetPersistentVolumeClaimRetentionPolicy)
		**out = **in
	}
	if in.ClusterDomain != nil {
		in, out := &in.ClusterDomain, &out.ClusterDomain
		*out = new(string)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLS)
		(*in).DeepCopyInto(*out)
	}
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(External)
		(*in).DeepCopyInto(*out)
	}
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = new(StretchListeners)
		(*in).DeepCopyInto(*out)
	}
	if in.RBAC != nil {
		in, out := &in.RBAC, &out.RBAC
		*out = new(RBAC)
		(*in).DeepCopyInto(*out)
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(ServiceAccount)
		(*in).DeepCopyInto(*out)
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(Monitoring)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StretchStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(StretchResources)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.RackAwareness != nil {
		in, out := &in.RackAwareness, &out.RackAwareness
		*out = new(RackAwareness)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(StretchLogging)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddedBrokerPoolSpec.
func (in *EmbeddedBrokerPoolSpec) DeepCopy() *EmbeddedBrokerPoolSpec {
	if in == nil {
		return nil
	}
	out := new(EmbeddedBrokerPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmbeddedBrokerPoolStatus) DeepCopyInto(out *EmbeddedBrokerPoolStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmbeddedBrokerPoolStatus.
func (in *EmbeddedBrokerPoolStatus) DeepCopy() *EmbeddedBrokerPoolStatus {
	if in == nil {
		return nil
	}
	out := new(EmbeddedBrokerPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Enterprise) DeepCopyInto(out *Enterprise) {
	*out = *in
	if in.License != nil {
		in, out := &in.License, &out.License
		*out = new(string)
		**out = **in
	}
	if in.LicenseSecretRef != nil {
		in, out := &in.LicenseSecretRef, &out.LicenseSecretRef
		*out = new(EnterpriseLicenseSecretRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Enterprise.
func (in *Enterprise) DeepCopy() *Enterprise {
	if in == nil {
		return nil
	}
	out := new(Enterprise)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnterpriseLicenseSecretRef) DeepCopyInto(out *EnterpriseLicenseSecretRef) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnterpriseLicenseSecretRef.
func (in *EnterpriseLicenseSecretRef) DeepCopy() *EnterpriseLicenseSecretRef {
	if in == nil {
		return nil
	}
	out := new(EnterpriseLicenseSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *External) DeepCopyInto(out *External) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Domain != nil {
		in, out := &in.Domain, &out.Domain
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ExternalService)
		(*in).DeepCopyInto(*out)
	}
	if in.SourceRanges != nil {
		in, out := &in.SourceRanges, &out.SourceRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.ExternalDNS != nil {
		in, out := &in.ExternalDNS, &out.ExternalDNS
		*out = new(ExternalDNS)
		(*in).DeepCopyInto(*out)
	}
	if in.PrefixTemplate != nil {
		in, out := &in.PrefixTemplate, &out.PrefixTemplate
		*out = new(string)
		**out = **in
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewayExternalConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new External.
func (in *External) DeepCopy() *External {
	if in == nil {
		return nil
	}
	out := new(External)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalDNS) DeepCopyInto(out *ExternalDNS) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalDNS.
func (in *ExternalDNS) DeepCopy() *ExternalDNS {
	if in == nil {
		return nil
	}
	out := new(ExternalDNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalService) DeepCopyInto(out *ExternalService) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalService.
func (in *ExternalService) DeepCopy() *ExternalService {
	if in == nil {
		return nil
	}
	out := new(ExternalService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayExternalConfig) DeepCopyInto(out *GatewayExternalConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ParentRefs != nil {
		in, out := &in.ParentRefs, &out.ParentRefs
		*out = make([]GatewayParentRefConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AdvertisedPort != nil {
		in, out := &in.AdvertisedPort, &out.AdvertisedPort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayExternalConfig.
func (in *GatewayExternalConfig) DeepCopy() *GatewayExternalConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayExternalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayParentRefConfig) DeepCopyInto(out *GatewayParentRefConfig) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
	if in.SectionName != nil {
		in, out := &in.SectionName, &out.SectionName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayParentRefConfig.
func (in *GatewayParentRefConfig) DeepCopy() *GatewayParentRefConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayParentRefConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitContainerImage) DeepCopyInto(out *InitContainerImage) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitContainerImage.
func (in *InitContainerImage) DeepCopy() *InitContainerImage {
	if in == nil {
		return nil
	}
	out := new(InitContainerImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IssuerRef) DeepCopyInto(out *IssuerRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IssuerRef.
func (in *IssuerRef) DeepCopy() *IssuerRef {
	if in == nil {
		return nil
	}
	out := new(IssuerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Memory) DeepCopyInto(out *Memory) {
	*out = *in
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(ContainerResources)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableMemoryLocking != nil {
		in, out := &in.EnableMemoryLocking, &out.EnableMemoryLocking
		*out = new(bool)
		**out = **in
	}
	if in.Redpanda != nil {
		in, out := &in.Redpanda, &out.Redpanda
		*out = new(RedpandaMemory)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Memory.
func (in *Memory) DeepCopy() *Memory {
	if in == nil {
		return nil
	}
	out := new(Memory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitoring) DeepCopyInto(out *Monitoring) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ScrapeInterval != nil {
		in, out := &in.ScrapeInterval, &out.ScrapeInterval
		*out = new(string)
		**out = **in
	}
	if in.TLSConfig != nil {
		in, out := &in.TLSConfig, &out.TLSConfig
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableHTTP2 != nil {
		in, out := &in.EnableHTTP2, &out.EnableHTTP2
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitoring.
func (in *Monitoring) DeepCopy() *Monitoring {
	if in == nil {
		return nil
	}
	out := new(Monitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Networking) DeepCopyInto(out *Networking) {
	*out = *in
	if in.CrossClusterMode != nil {
		in, out := &in.CrossClusterMode, &out.CrossClusterMode
		*out = new(CrossClusterMode)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Networking.
func (in *Networking) DeepCopy() *Networking {
	if in == nil {
		return nil
	}
	out := new(Networking)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodePoolServices) DeepCopyInto(out *NodePoolServices) {
	clone := in.DeepCopy()
	*out = *clone
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerPodServiceOverride) DeepCopyInto(out *PerPodServiceOverride) {
	clone := in.DeepCopy()
	*out = *clone
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerPodServices) DeepCopyInto(out *PerPodServices) {
	clone := in.DeepCopy()
	*out = *clone
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolume) DeepCopyInto(out *PersistentVolume) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
	if in.NameOverwrite != nil {
		in, out := &in.NameOverwrite, &out.NameOverwrite
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolume.
func (in *PersistentVolume) DeepCopy() *PersistentVolume {
	if in == nil {
		return nil
	}
	out := new(PersistentVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodTemplate) DeepCopyInto(out *PodTemplate) {
	clone := in.DeepCopy()
	*out = *clone
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolConfigurator) DeepCopyInto(out *PoolConfigurator) {
	*out = *in
	if in.AdditionalCLIArgs != nil {
		in, out := &in.AdditionalCLIArgs, &out.AdditionalCLIArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolConfigurator.
func (in *PoolConfigurator) DeepCopy() *PoolConfigurator {
	if in == nil {
		return nil
	}
	out := new(PoolConfigurator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolFSValidator) DeepCopyInto(out *PoolFSValidator) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ExpectedFS != nil {
		in, out := &in.ExpectedFS, &out.ExpectedFS
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolFSValidator.
func (in *PoolFSValidator) DeepCopy() *PoolFSValidator {
	if in == nil {
		return nil
	}
	out := new(PoolFSValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolInitContainers) DeepCopyInto(out *PoolInitContainers) {
	*out = *in
	if in.FSValidator != nil {
		in, out := &in.FSValidator, &out.FSValidator
		*out = new(PoolFSValidator)
		(*in).DeepCopyInto(*out)
	}
	if in.SetDataDirOwnership != nil {
		in, out := &in.SetDataDirOwnership, &out.SetDataDirOwnership
		*out = new(PoolSetDataDirOwnership)
		(*in).DeepCopyInto(*out)
	}
	if in.Configurator != nil {
		in, out := &in.Configurator, &out.Configurator
		*out = new(PoolConfigurator)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolInitContainers.
func (in *PoolInitContainers) DeepCopy() *PoolInitContainers {
	if in == nil {
		return nil
	}
	out := new(PoolInitContainers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolSetDataDirOwnership) DeepCopyInto(out *PoolSetDataDirOwnership) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolSetDataDirOwnership.
func (in *PoolSetDataDirOwnership) DeepCopy() *PoolSetDataDirOwnership {
	if in == nil {
		return nil
	}
	out := new(PoolSetDataDirOwnership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RBAC) DeepCopyInto(out *RBAC) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RPKDebugBundle != nil {
		in, out := &in.RPKDebugBundle, &out.RPKDebugBundle
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RBAC.
func (in *RBAC) DeepCopy() *RBAC {
	if in == nil {
		return nil
	}
	out := new(RBAC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RackAwareness) DeepCopyInto(out *RackAwareness) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.NodeAnnotation != nil {
		in, out := &in.NodeAnnotation, &out.NodeAnnotation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RackAwareness.
func (in *RackAwareness) DeepCopy() *RackAwareness {
	if in == nil {
		return nil
	}
	out := new(RackAwareness)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedpandaBrokerPool) DeepCopyInto(out *RedpandaBrokerPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedpandaBrokerPool.
func (in *RedpandaBrokerPool) DeepCopy() *RedpandaBrokerPool {
	if in == nil {
		return nil
	}
	out := new(RedpandaBrokerPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RedpandaBrokerPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedpandaBrokerPoolList) DeepCopyInto(out *RedpandaBrokerPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RedpandaBrokerPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedpandaBrokerPoolList.
func (in *RedpandaBrokerPoolList) DeepCopy() *RedpandaBrokerPoolList {
	if in == nil {
		return nil
	}
	out := new(RedpandaBrokerPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RedpandaBrokerPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedpandaImage) DeepCopyInto(out *RedpandaImage) {
	*out = *in
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
	if in.PullPolicy != nil {
		in, out := &in.PullPolicy, &out.PullPolicy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedpandaImage.
func (in *RedpandaImage) DeepCopy() *RedpandaImage {
	if in == nil {
		return nil
	}
	out := new(RedpandaImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedpandaLicenseStatus) DeepCopyInto(out *RedpandaLicenseStatus) {
	*out = *in
	if in.InUseFeatures != nil {
		in, out := &in.InUseFeatures, &out.InUseFeatures
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Expired != nil {
		in, out := &in.Expired, &out.Expired
		*out = new(bool)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Organization != nil {
		in, out := &in.Organization, &out.Organization
		*out = new(string)
		**out = **in
	}
	if in.Expiration != nil {
		in, out := &in.Expiration, &out.Expiration
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedpandaLicenseStatus.
func (in *RedpandaLicenseStatus) DeepCopy() *RedpandaLicenseStatus {
	if in == nil {
		return nil
	}
	out := new(RedpandaLicenseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedpandaMemory) DeepCopyInto(out *RedpandaMemory) {
	*out = *in
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ReserveMemory != nil {
		in, out := &in.ReserveMemory, &out.ReserveMemory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedpandaMemory.
func (in *RedpandaMemory) DeepCopy() *RedpandaMemory {
	if in == nil {
		return nil
	}
	out := new(RedpandaMemory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SASL) DeepCopyInto(out *SASL) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Mechanism != nil {
		in, out := &in.Mechanism, &out.Mechanism
		*out = new(string)
		**out = **in
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(string)
		**out = **in
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]UsersItems, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BootstrapUser != nil {
		in, out := &in.BootstrapUser, &out.BootstrapUser
		*out = new(BootstrapUser)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SASL.
func (in *SASL) DeepCopy() *SASL {
	if in == nil {
		return nil
	}
	out := new(SASL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretWithConfigField) DeepCopyInto(out *SecretWithConfigField) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ConfigurationKey != nil {
		in, out := &in.ConfigurationKey, &out.ConfigurationKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretWithConfigField.
func (in *SecretWithConfigField) DeepCopy() *SecretWithConfigField {
	if in == nil {
		return nil
	}
	out := new(SecretWithConfigField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccount) DeepCopyInto(out *ServiceAccount) {
	*out = *in
	if in.AutomountServiceAccountToken != nil {
		in, out := &in.AutomountServiceAccountToken, &out.AutomountServiceAccountToken
		*out = new(bool)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccount.
func (in *ServiceAccount) DeepCopy() *ServiceAccount {
	if in == nil {
		return nil
	}
	out := new(ServiceAccount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchAPIListener) DeepCopyInto(out *StretchAPIListener) {
	*out = *in
	in.StretchListener.DeepCopyInto(&out.StretchListener)
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = make(map[string]*StretchExternalListener, len(*in))
		for key, val := range *in {
			var outVal *StretchExternalListener
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(StretchExternalListener)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchAPIListener.
func (in *StretchAPIListener) DeepCopy() *StretchAPIListener {
	if in == nil {
		return nil
	}
	out := new(StretchAPIListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchAuditLogging) DeepCopyInto(out *StretchAuditLogging) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Partitions != nil {
		in, out := &in.Partitions, &out.Partitions
		*out = new(int)
		**out = **in
	}
	if in.EnabledEventTypes != nil {
		in, out := &in.EnabledEventTypes, &out.EnabledEventTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedTopics != nil {
		in, out := &in.ExcludedTopics, &out.ExcludedTopics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedPrincipals != nil {
		in, out := &in.ExcludedPrincipals, &out.ExcludedPrincipals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClientMaxBufferSize != nil {
		in, out := &in.ClientMaxBufferSize, &out.ClientMaxBufferSize
		*out = new(int)
		**out = **in
	}
	if in.QueueDrainIntervalMs != nil {
		in, out := &in.QueueDrainIntervalMs, &out.QueueDrainIntervalMs
		*out = new(int)
		**out = **in
	}
	if in.QueueMaxBufferSizePerShard != nil {
		in, out := &in.QueueMaxBufferSizePerShard, &out.QueueMaxBufferSizePerShard
		*out = new(int)
		**out = **in
	}
	if in.ReplicationFactor != nil {
		in, out := &in.ReplicationFactor, &out.ReplicationFactor
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchAuditLogging.
func (in *StretchAuditLogging) DeepCopy() *StretchAuditLogging {
	if in == nil {
		return nil
	}
	out := new(StretchAuditLogging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchCluster) DeepCopyInto(out *StretchCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchCluster.
func (in *StretchCluster) DeepCopy() *StretchCluster {
	if in == nil {
		return nil
	}
	out := new(StretchCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StretchCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchClusterList) DeepCopyInto(out *StretchClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StretchCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchClusterList.
func (in *StretchClusterList) DeepCopy() *StretchClusterList {
	if in == nil {
		return nil
	}
	out := new(StretchClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StretchClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchClusterSpec) DeepCopyInto(out *StretchClusterSpec) {
	*out = *in
	if in.CommonLabels != nil {
		in, out := &in.CommonLabels, &out.CommonLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(RedpandaImage)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.Enterprise != nil {
		in, out := &in.Enterprise, &out.Enterprise
		*out = new(Enterprise)
		(*in).DeepCopyInto(*out)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(Auth)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(StretchLogging)
		(*in).DeepCopyInto(*out)
	}
	if in.AuditLogging != nil {
		in, out := &in.AuditLogging, &out.AuditLogging
		*out = new(StretchAuditLogging)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(StretchResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StretchStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.Tuning != nil {
		in, out := &in.Tuning, &out.Tuning
		*out = new(StretchTuning)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(Config)
		(*in).DeepCopyInto(*out)
	}
	if in.Networking != nil {
		in, out := &in.Networking, &out.Networking
		*out = new(Networking)
		(*in).DeepCopyInto(*out)
	}
	if in.InternalServiceAnnotations != nil {
		in, out := &in.InternalServiceAnnotations, &out.InternalServiceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchClusterSpec.
func (in *StretchClusterSpec) DeepCopy() *StretchClusterSpec {
	if in == nil {
		return nil
	}
	out := new(StretchClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchClusterStatus) DeepCopyInto(out *StretchClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodePools != nil {
		in, out := &in.NodePools, &out.NodePools
		*out = make([]EmbeddedBrokerPoolStatus, len(*in))
		copy(*out, *in)
	}
	if in.LicenseStatus != nil {
		in, out := &in.LicenseStatus, &out.LicenseStatus
		*out = new(RedpandaLicenseStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchClusterStatus.
func (in *StretchClusterStatus) DeepCopy() *StretchClusterStatus {
	if in == nil {
		return nil
	}
	out := new(StretchClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchExternalListener) DeepCopyInto(out *StretchExternalListener) {
	*out = *in
	in.StretchListener.DeepCopyInto(&out.StretchListener)
	if in.AdvertisedPorts != nil {
		in, out := &in.AdvertisedPorts, &out.AdvertisedPorts
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchExternalListener.
func (in *StretchExternalListener) DeepCopy() *StretchExternalListener {
	if in == nil {
		return nil
	}
	out := new(StretchExternalListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchListener) DeepCopyInto(out *StretchListener) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.AuthenticationMethod != nil {
		in, out := &in.AuthenticationMethod, &out.AuthenticationMethod
		*out = new(string)
		**out = **in
	}
	if in.AppProtocol != nil {
		in, out := &in.AppProtocol, &out.AppProtocol
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(StretchListenerTLS)
		(*in).DeepCopyInto(*out)
	}
	if in.PrefixTemplate != nil {
		in, out := &in.PrefixTemplate, &out.PrefixTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchListener.
func (in *StretchListener) DeepCopy() *StretchListener {
	if in == nil {
		return nil
	}
	out := new(StretchListener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchListenerTLS) DeepCopyInto(out *StretchListenerTLS) {
	*out = *in
	if in.Cert != nil {
		in, out := &in.Cert, &out.Cert
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RequireClientAuth != nil {
		in, out := &in.RequireClientAuth, &out.RequireClientAuth
		*out = new(bool)
		**out = **in
	}
	if in.TrustStore != nil {
		in, out := &in.TrustStore, &out.TrustStore
		*out = new(TrustStore)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchListenerTLS.
func (in *StretchListenerTLS) DeepCopy() *StretchListenerTLS {
	if in == nil {
		return nil
	}
	out := new(StretchListenerTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchListeners) DeepCopyInto(out *StretchListeners) {
	*out = *in
	if in.Admin != nil {
		in, out := &in.Admin, &out.Admin
		*out = new(StretchAPIListener)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(StretchAPIListener)
		(*in).DeepCopyInto(*out)
	}
	if in.Kafka != nil {
		in, out := &in.Kafka, &out.Kafka
		*out = new(StretchAPIListener)
		(*in).DeepCopyInto(*out)
	}
	if in.RPC != nil {
		in, out := &in.RPC, &out.RPC
		*out = new(StretchRPC)
		(*in).DeepCopyInto(*out)
	}
	if in.SchemaRegistry != nil {
		in, out := &in.SchemaRegistry, &out.SchemaRegistry
		*out = new(StretchAPIListener)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchListeners.
func (in *StretchListeners) DeepCopy() *StretchListeners {
	if in == nil {
		return nil
	}
	out := new(StretchListeners)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchLogging) DeepCopyInto(out *StretchLogging) {
	*out = *in
	if in.LogLevel != nil {
		in, out := &in.LogLevel, &out.LogLevel
		*out = new(string)
		**out = **in
	}
	if in.UsageStats != nil {
		in, out := &in.UsageStats, &out.UsageStats
		*out = new(StretchUsageStats)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchLogging.
func (in *StretchLogging) DeepCopy() *StretchLogging {
	if in == nil {
		return nil
	}
	out := new(StretchLogging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchRPC) DeepCopyInto(out *StretchRPC) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(StretchListenerTLS)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchRPC.
func (in *StretchRPC) DeepCopy() *StretchRPC {
	if in == nil {
		return nil
	}
	out := new(StretchRPC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchResources) DeepCopyInto(out *StretchResources) {
	*out = *in
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(corev1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(CPU)
		(*in).DeepCopyInto(*out)
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(Memory)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchResources.
func (in *StretchResources) DeepCopy() *StretchResources {
	if in == nil {
		return nil
	}
	out := new(StretchResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchStorage) DeepCopyInto(out *StretchStorage) {
	*out = *in
	if in.HostPath != nil {
		in, out := &in.HostPath, &out.HostPath
		*out = new(string)
		**out = **in
	}
	if in.PersistentVolume != nil {
		in, out := &in.PersistentVolume, &out.PersistentVolume
		*out = new(PersistentVolume)
		(*in).DeepCopyInto(*out)
	}
	if in.Tiered != nil {
		in, out := &in.Tiered, &out.Tiered
		*out = new(StretchTiered)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchStorage.
func (in *StretchStorage) DeepCopy() *StretchStorage {
	if in == nil {
		return nil
	}
	out := new(StretchStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchTiered) DeepCopyInto(out *StretchTiered) {
	*out = *in
	if in.MountType != nil {
		in, out := &in.MountType, &out.MountType
		*out = new(string)
		**out = **in
	}
	if in.HostPath != nil {
		in, out := &in.HostPath, &out.HostPath
		*out = new(string)
		**out = **in
	}
	if in.PersistentVolume != nil {
		in, out := &in.PersistentVolume, &out.PersistentVolume
		*out = new(PersistentVolume)
		(*in).DeepCopyInto(*out)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(StretchTieredConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(CredentialSecretRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchTiered.
func (in *StretchTiered) DeepCopy() *StretchTiered {
	if in == nil {
		return nil
	}
	out := new(StretchTiered)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchTieredConfig) DeepCopyInto(out *StretchTieredConfig) {
	*out = *in
	if in.CloudStorageEnabled != nil {
		in, out := &in.CloudStorageEnabled, &out.CloudStorageEnabled
		*out = new(bool)
		**out = **in
	}
	if in.CloudStorageAPIEndpoint != nil {
		in, out := &in.CloudStorageAPIEndpoint, &out.CloudStorageAPIEndpoint
		*out = new(string)
		**out = **in
	}
	if in.CloudStorageAPIEndpointPort != nil {
		in, out := &in.CloudStorageAPIEndpointPort, &out.CloudStorageAPIEndpointPort
		*out = new(int)
		**out = **in
	}
	if in.CloudStorageBucket != nil {
		in, out := &in.CloudStorageBucket, &out.CloudStorageBucket
		*out = new(string)
		**out = **in
	}
	if in.CloudStorageAzureContainer != nil {
		in, out := &in.CloudStorageAzureContainer, &out.CloudStorageAzureContainer
		*out = new(string)
		**out = **in
	}
	if in.CloudStorageAzureManagedIdentityID != nil {
		in, out := &in.CloudStorageAzureManagedIdentityID, &out.CloudStorageAzureManagedIdentityID
		*out = new(string)
		**out = **in
	}
	if in.CloudStorageAzureStorageAccount != nil {
		in, out := &in.CloudStorageAzureStorageAccount, &out.CloudStorageAzureStorageAccount
		*out = new(string)
		**out = **in
	}
	if in.CloudStorageAzureSharedKey != nil {
		in, out := &in.CloudStorageAzureSharedKey, &out.CloudStorageAzureSharedKey
		*out = new(string)
		**out = **in
	}
	if in.CloudStorageAzureADLSEndpoint != nil {
		in, out := &in.CloudStorageAzureADLSEndpoint, &out.CloudStorageAzureADLSEndpoint
		*out = new(string)
		**out = **in
	}
	if in.CloudStorageAzureADLSPort != nil {
		in, out := &in.CloudStorageAzureADLSPort, &out.CloudStorageAzureADLSPort
		*out = new(int)
		**out = **in
	}
	if in.CloudStorageCacheCheckInterval != nil {
		in, out := &in.CloudStorageCacheCheckInterval, &out.CloudStorageCacheCheckInterval
		*out = new(int)
		**out = **in
	}
	if in.CloudStorageCacheDirectory != nil {
		in, out := &in.CloudStorageCacheDirectory, &out.CloudStorageCacheDirectory
		*out = new(string)
		**out = **in
	}
	if in.CloudStorageCacheSize != nil {
		in, out := &in.CloudStorageCacheSize, &out.CloudStorageCacheSize
		*out = new(string)
		**out = **in
	}
	if in.CloudStorageCredentialsSource != nil {
		in, out := &in.CloudStorageCredentialsSource, &out.CloudStorageCredentialsSource
		*out = new(string)
		**out = **in
	}
	if in.CloudStorageDisableTLS != nil {
		in, out := &in.CloudStorageDisableTLS, &out.CloudStorageDisableTLS
		*out = new(bool)
		**out = **in
	}
	if in.CloudStorageEnableRemoteRead != nil {
		in, out := &in.CloudStorageEnableRemoteRead, &out.CloudStorageEnableRemoteRead
		*out = new(bool)
		**out = **in
	}
	if in.CloudStorageEnableRemoteWrite != nil {
		in, out := &in.CloudStorageEnableRemoteWrite, &out.CloudStorageEnableRemoteWrite
		*out = new(bool)
		**out = **in
	}
	if in.CloudStorageInitialBackoffMs != nil {
		in, out := &in.CloudStorageInitialBackoffMs, &out.CloudStorageInitialBackoffMs
		*out = new(int)
		**out = **in
	}
	if in.CloudStorageManifestUploadTimeoutMs != nil {
		in, out := &in.CloudStorageManifestUploadTimeoutMs, &out.CloudStorageManifestUploadTimeoutMs
		*out = new(int)
		**out = **in
	}
	if in.CloudStorageMaxConnectionIdleTimeMs != nil {
		in, out := &in.CloudStorageMaxConnectionIdleTimeMs, &out.CloudStorageMaxConnectionIdleTimeMs
		*out = new(int)
		**out = **in
	}
	if in.CloudStorageMaxConnections != nil {
		in, out := &in.CloudStorageMaxConnections, &out.CloudStorageMaxConnections
		*out = new(int)
		**out = **in
	}
	if in.CloudStorageRegion != nil {
		in, out := &in.CloudStorageRegion, &out.CloudStorageRegion
		*out = new(string)
		**out = **in
	}
	if in.CloudStorageSegmentMaxUploadIntervalSec != nil {
		in, out := &in.CloudStorageSegmentMaxUploadIntervalSec, &out.CloudStorageSegmentMaxUploadIntervalSec
		*out = new(int)
		**out = **in
	}
	if in.CloudStorageSegmentUploadTimeoutMs != nil {
		in, out := &in.CloudStorageSegmentUploadTimeoutMs, &out.CloudStorageSegmentUploadTimeoutMs
		*out = new(int)
		**out = **in
	}
	if in.CloudStorageTrustFile != nil {
		in, out := &in.CloudStorageTrustFile, &out.CloudStorageTrustFile
		*out = new(string)
		**out = **in
	}
	if in.CloudStorageUploadCtrlDCoeff != nil {
		in, out := &in.CloudStorageUploadCtrlDCoeff, &out.CloudStorageUploadCtrlDCoeff
		*out = new(int)
		**out = **in
	}
	if in.CloudStorageUploadCtrlMaxShares != nil {
		in, out := &in.CloudStorageUploadCtrlMaxShares, &out.CloudStorageUploadCtrlMaxShares
		*out = new(int)
		**out = **in
	}
	if in.CloudStorageUploadCtrlMinShares != nil {
		in, out := &in.CloudStorageUploadCtrlMinShares, &out.CloudStorageUploadCtrlMinShares
		*out = new(int)
		**out = **in
	}
	if in.CloudStorageUploadCtrlPCoeff != nil {
		in, out := &in.CloudStorageUploadCtrlPCoeff, &out.CloudStorageUploadCtrlPCoeff
		*out = new(int)
		**out = **in
	}
	if in.CloudStorageUploadCtrlUpdateIntervalMs != nil {
		in, out := &in.CloudStorageUploadCtrlUpdateIntervalMs, &out.CloudStorageUploadCtrlUpdateIntervalMs
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchTieredConfig.
func (in *StretchTieredConfig) DeepCopy() *StretchTieredConfig {
	if in == nil {
		return nil
	}
	out := new(StretchTieredConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchTuning) DeepCopyInto(out *StretchTuning) {
	*out = *in
	if in.BallastFilePath != nil {
		in, out := &in.BallastFilePath, &out.BallastFilePath
		*out = new(string)
		**out = **in
	}
	if in.BallastFileSize != nil {
		in, out := &in.BallastFileSize, &out.BallastFileSize
		*out = new(string)
		**out = **in
	}
	if in.TuneAioEvents != nil {
		in, out := &in.TuneAioEvents, &out.TuneAioEvents
		*out = new(bool)
		**out = **in
	}
	if in.TuneBallastFile != nil {
		in, out := &in.TuneBallastFile, &out.TuneBallastFile
		*out = new(bool)
		**out = **in
	}
	if in.TuneClockSource != nil {
		in, out := &in.TuneClockSource, &out.TuneClockSource
		*out = new(bool)
		**out = **in
	}
	if in.WellKnownIo != nil {
		in, out := &in.WellKnownIo, &out.WellKnownIo
		*out = new(string)
		**out = **in
	}
	if in.ApplyHostTuners != nil {
		in, out := &in.ApplyHostTuners, &out.ApplyHostTuners
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchTuning.
func (in *StretchTuning) DeepCopy() *StretchTuning {
	if in == nil {
		return nil
	}
	out := new(StretchTuning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StretchUsageStats) DeepCopyInto(out *StretchUsageStats) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StretchUsageStats.
func (in *StretchUsageStats) DeepCopy() *StretchUsageStats {
	if in == nil {
		return nil
	}
	out := new(StretchUsageStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLS) DeepCopyInto(out *TLS) {
	*out = *in
	if in.Certs != nil {
		in, out := &in.Certs, &out.Certs
		*out = make(map[string]*Certificate, len(*in))
		for key, val := range *in {
			var outVal *Certificate
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(Certificate)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLS.
func (in *TLS) DeepCopy() *TLS {
	if in == nil {
		return nil
	}
	out := new(TLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustStore) DeepCopyInto(out *TrustStore) {
	*out = *in
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(corev1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustStore.
func (in *TrustStore) DeepCopy() *TrustStore {
	if in == nil {
		return nil
	}
	out := new(TrustStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsersItems) DeepCopyInto(out *UsersItems) {
	*out = *in
	if in.Mechanism != nil {
		in, out := &in.Mechanism, &out.Mechanism
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsersItems.
func (in *UsersItems) DeepCopy() *UsersItems {
	if in == nil {
		return nil
	}
	out := new(UsersItems)
	in.DeepCopyInto(out)
	return out
}
