{{- $root := . }}
{{- range $path, $_ :=  .Files.Glob  "**.yaml" }}
---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
delete:
  - apiVersion: cluster.redpanda.com/v1alpha2
    kind: Redpanda
    name: redpanda-{{ substr 0 2 (base $path) }}
  - apiVersion: batch/v1
    kind: Job
  - apiVersion: v1
    kind: PersistentVolumeClaim
  - apiVersion: v1
    kind: Pod
    labels:
      app.kubernetes.io/name: redpanda
  - apiVersion: v1
    kind: Pod
    labels:
      app.kubernetes.io/name: console
  - apiVersion: v1
    kind: Service
    labels:
      app.kubernetes.io/name: redpanda
{{- end }}