{{- $root := . }}
{{- range $path, $_ :=  .Files.Glob  "**.yaml" }}
---
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: redpanda-{{ substr 0 2 (base $path) }}
spec:
  chartRef:
    chartVersion: "5.6.58"
  {{- with $root }}
  clusterSpec:
  {{- .Files.Get $path | nindent 4 }}
  {{- end }}
{{- end }}
