---
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: basic
spec:
  clusterSpec:
    statefulset:
      replicas: 1
      sideCars:
        image:
          tag: dev
          repository: localhost/redpanda-operator
        controllers:
          image:
            tag: dev
            repository: localhost/redpanda-operator
