---
apiVersion: cluster.redpanda.com/v1alpha2
kind: Redpanda
metadata:
  name: basic
spec:
  clusterSpec:
    image:
      repository: ${DEFAULT_REDPANDA_REPO}
      tag: ${DEFAULT_REDPANDA_TAG}
    external:
      enabled: false
    statefulset:
      replicas: 1
      sideCars:
        image:
          tag: dev
          repository: localhost/redpanda-operator
        controllers:
          image:
            tag: dev
            repository: localhost/redpanda-operator
