{{/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- include "fail-on-unsupported-helm-version" . -}}
{{- include "fail-on-insecure-sasl-logging" . -}}

{{- $values := .Values }}
{{- $internalAdvertiseAddress := printf "%s.%s" "$(SERVICE_NAME)" (include "redpanda.internal.domain" .) -}}
{{- $uid := dig "podSecurityContext" "runAsUser" .Values.statefulset.securityContext.runAsUser .Values.statefulset -}}
{{- $gid := dig "podSecurityContext" "fsGroup" .Values.statefulset.securityContext.fsGroup .Values.statefulset -}}

{{- if not (include "redpanda-atleast-22-2-0" . | fromJson).bool -}}
  {{- if eq (get .Values "force" | default false) false -}}
    {{- fail (
    printf "\n\nError: The Redpanda version (%s) is no longer supported \nTo accept this risk, run the upgrade again adding `--force=true`\n" (( include "redpanda.semver" . ))
        )
    -}}
  {{- end -}}
{{- end -}}

{{- $initContainers := (get ((include "redpanda.StatefulSetInitContainers" (dict "a" (list .))) | fromJson) "r") -}}
{{- $containers := (get ((include "redpanda.StatefulSetContainers" (dict "a" (list .))) | fromJson) "r") -}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "redpanda.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{- with include "full.labels" . }}
  {{- . | nindent 4 }}
{{- end }}
spec:
  selector:
    matchLabels: {{ (include "statefulset-pod-labels-selector" .) | nindent 6 }}
  serviceName: {{ template "redpanda.servicename" . }}
  replicas: {{ .Values.statefulset.replicas | int64 }}
  updateStrategy:
    {{- toYaml .Values.statefulset.updateStrategy | nindent 4 }}
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels: {{ (include "statefulset-pod-labels" .) | nindent 8 }}
      annotations:{{ ( get ( (include "redpanda.StatefulSetPodAnnotations" (dict "a" (list . (include "statefulset-checksum-annotation" .) )) ) | fromJson) "r" ) | toYaml | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.statefulset.terminationGracePeriodSeconds }}
      securityContext: {{ include "pod-security-context" . | nindent 8 }}
      serviceAccountName: {{ include "redpanda.serviceAccountName" . }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
{{- if not (empty $initContainers) }}
{{- toYaml $initContainers | nindent 8 }}
{{- end }}
      containers:
{{- if not (empty $containers) }}
{{- toYaml $containers | nindent 8 }}
{{- end }}
      volumes: {{ (get ((include "redpanda.StatefulSetVolumes" (dict "a" (list .))) | fromJson) "r") | toYaml | nindent 8 }}
        - name: datadir
      {{- if .Values.storage.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: datadir
      {{- else if .Values.storage.hostPath }}
          hostPath:
            path: {{ .Values.storage.hostPath | quote }}
      {{- else }}
          emptyDir: {}
      {{- end }}
      {{- if (include "storage-tiered-config" .|fromJson).cloud_storage_enabled }}
        {{- $tieredType := include "storage-tiered-mountType" . }}
        {{- if and (ne $tieredType "none") (ne $tieredType "persistentVolume") }}
        - name: tiered-storage-dir
          {{- if eq $tieredType "hostPath" }}
          hostPath:
            path: {{ include "storage-tiered-hostpath" . }}
          {{- else }}
          emptyDir:
            sizeLimit: {{ (include "storage-tiered-config" . | fromJson).cloud_storage_cache_size }}
          {{- end }}
        {{- end }}
      {{- end }}
{{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.GitVersion }}
      topologySpreadConstraints:
    {{- range $v := .Values.statefulset.topologySpreadConstraints }}
        - maxSkew: {{ $v.maxSkew }}
          topologyKey: {{ $v.topologyKey }}
          whenUnsatisfiable: {{ $v.whenUnsatisfiable }}
          labelSelector:
            matchLabels: {{ include "statefulset-pod-labels-selector" $ | nindent 14 }}
    {{- end }}
{{- end }}
{{- with ( include "statefulset-nodeSelectors" . ) }}
      nodeSelector: {{- . | nindent 8 }}
{{- end }}
{{- with ( include "statefulset-affinity" . ) }}
      affinity: {{- . | nindent 8 }}
{{- end }}
{{- if .Values.statefulset.priorityClassName }}
      priorityClassName: {{ .Values.statefulset.priorityClassName }}
{{- end }}
{{- with ( include "statefulset-tolerations" . ) }}
      tolerations: {{- . | nindent 8 }}
{{- end }}
{{- if or .Values.storage.persistentVolume.enabled (and (include "storage-tiered-config" .|fromJson).cloud_storage_enabled (eq (include "storage-tiered-mountType" .) "persistentVolume" )) }}
  volumeClaimTemplates:
{{- if .Values.storage.persistentVolume.enabled }}
    - metadata:
        name: datadir
        labels:
          app.kubernetes.io/name: {{ template "redpanda.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name | quote }}
          app.kubernetes.io/component: {{ template "redpanda.name" . }}
  {{- with .Values.storage.persistentVolume.labels }}
    {{- toYaml . | nindent 10 }}
  {{- end }}
  {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 10 }}
  {{- end }}
  {{- with .Values.storage.persistentVolume.annotations }}
        annotations: {{- toYaml . | nindent 10 }}
  {{- end }}
      spec:
        accessModes: ["ReadWriteOnce"]
  {{- if .Values.storage.persistentVolume.storageClass }}
    {{- if (eq "-" .Values.storage.persistentVolume.storageClass) }}
        storageClassName: ""
    {{- else }}
        storageClassName: {{ .Values.storage.persistentVolume.storageClass | quote }}
    {{- end }}
  {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.persistentVolume.size | quote }}
{{- end }}
{{- if and (include "storage-tiered-config" .|fromJson).cloud_storage_enabled (eq (include "storage-tiered-mountType" .) "persistentVolume") }}
    - metadata:
        name: {{ default "tiered-storage-dir" .Values.storage.persistentVolume.nameOverwrite }}
        labels:
          app.kubernetes.io/name: {{ template "redpanda.name" . }}
          app.kubernetes.io/instance: {{ .Release.Name | quote }}
          app.kubernetes.io/component: {{ template "redpanda.name" . }}
  {{- with (include "storage-tiered-persistentvolume" . | fromJson).labels }}
    {{ toYaml . | nindent 10 }}
  {{- end }}
  {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 10 }}
  {{- end }}
  {{- with (include "storage-tiered-persistentvolume" . | fromJson).annotations }}
        annotations: {{ toYaml . | nindent 10 }}
  {{- end }}
      spec:
        accessModes: ["ReadWriteOnce"]
  {{- with (include "storage-tiered-persistentvolume" . | fromJson).storageClass }}
    {{- if eq "-" . }}
        storageClassName: ""
    {{- else }}
        storageClassName: {{ . }}
    {{- end }}
  {{- end }}
        resources:
          requests:
            storage: {{ (include "storage-tiered-config" .|fromJson).cloud_storage_cache_size }}
{{- end }}
{{- end }}
