version: '3'

tasks:
  genpartial:
    dir: ./genpartial
    sources:
    - ./*.go
    - ./go.*
    cmds:
    - go build -o ../.build/genpartial .

  genschema:
    dir: genschema
    sources:
    - ./*.go
    - ./go.*
    cmds:
    - go build -o ../.build/genschema .

  gotohelm:
    dir: gotohelm
    sources:
    - ./*.go
    - ./go.*
    cmds:
    - go build -o ../.build/gotohelm .

  licenseupdater:
    dir: licenseupdater
    cmds:
    - go build -o ../.build/licenseupdater .
