version: '3'

# NB: Task's globbing appears to be a bit finicky WRT it's recursion. We'll
# instead rely on go build's caching as it's quite good and eliminates false
# negatives.

tasks:
  gen:
    dir: ./gen
    cmds:
    - go build -o ../.build/gen main.go

  gotohelm:
    dir: gotohelm
    cmds:
    - go build -o ../.build/gotohelm .

  licenseupdater:
    dir: licenseupdater
    cmds:
    - go build -o ../.build/licenseupdater .
