version: '3'

tasks:
  retry-task:
    vars:
      TASK_EXEC: '{{default "task" .TASK_EXEC}}'
      RETRY_COUNT: '{{default 3 .RETRY_COUNT}}'
      SLEEP_INTERVAL: '{{default 3 .SLEEP_INTERVAL}}'
    cmds:
      - echo "will retry task {{.TASK}}"
      - |
        retry_times={{.RETRY_COUNT}}
        retry_index=0
        while ((retry_index < retry_times)); do
          set +e
          {{.TASK_EXEC}} {{.TASK}} {{.PARAMS}}
          cmd_code="$?"
          set -e
          if [[ $cmd_code == "0" ]]; then
            break
          fi
          let retry_index=retry_index+1
          echo "retrying task {{.TASK}}, attempt $retry_index, after sleep {{.SLEEP_INTERVAL}}"
          sleep {{.SLEEP_INTERVAL}}
        done
        if [[ $cmd_code != "0" ]]; then
          echo "retried '{{.TASK}}' task {{.RETRY_COUNT}} times and failed"
          exit $cmd_code
        fi
    preconditions:
      - test -n '{{.TASK}}'

  download-integration-artifacts:
    silent: true
    vars:
      BRANCH: '{{default "" .BRANCH}}'
    cmds:
      - ./ci/scripts/download-otel-artifacts.sh "{{.BRANCH}}" integration

  create-buildx-builder:
    cmds:
      - task: :dev:retry-task
        vars:
          TASK: dev:retry-create-buildx-builder
    status:
      - docker buildx ls | grep -q v-builder

  retry-create-buildx-builder:
    cmds:
      - docker buildx create --driver-opt env.BUILDKIT_STEP_LOG_MAX_SIZE=-1 --driver-opt env.BUILDKIT_STEP_LOG_MAX_SPEED=-1 --platform linux/amd64,linux/arm64 --name v-builder --use
      - '{{if eq ARCH "amd64"}} docker run --rm --privileged linuxkit/binfmt:v0.8 {{else}} echo "" {{end}}'

  update-licenses:
    cmds:
      - go run ./licenseupdater ./... -config .licenseupdater.yaml

  install-local-plugin:
    cmds:
      - task: :build:plugin
      - go run -C ./plugin -tags install install.go

  cluster-fleet:
    cmds:
      - task: :build:images
      - task: :dev:install-local-plugin
      - k3d cluster create --image rancher/k3s:v1.34.1-k3s1 left --network multicluster-dev -p "9443:9443@loadbalancer"
      - k3d cluster create --image rancher/k3s:v1.34.1-k3s1 middle --network multicluster-dev -p "9444:9443@loadbalancer"
      - k3d cluster create --image rancher/k3s:v1.34.1-k3s1 right --network multicluster-dev -p "9445:9443@loadbalancer"
      - k3d image import --cluster left localhost/redpanda-operator:dev
      - k3d image import --cluster middle localhost/redpanda-operator:dev
      - k3d image import --cluster right localhost/redpanda-operator:dev

  multicluster:
    vars:
      LEFT_IP:
        sh: kubectl get svc --context k3d-left -n kube-system traefik --template {{ "'{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}'" }}
      MIDDLE_IP:
        sh: kubectl get svc --context k3d-middle -n kube-system traefik --template {{ "'{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}'" }}
      RIGHT_IP:
        sh: kubectl get svc --context k3d-right -n kube-system traefik --template {{ "'{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}'" }}
    cmds:
      - rpk k8s multicluster rotate-certificates --cluster k3d-middle://{{ .MIDDLE_IP }} --cluster k3d-left://{{ .LEFT_IP }} --cluster k3d-right://{{ .RIGHT_IP }}
      - helm install --kube-context k3d-left --namespace=redpanda-system redpanda-multicluster-operator ./charts/multicluster --set="node=left" --set="apiServerExternalAddress=https://{{ .LEFT_IP }}:6443" --set="peers[0].name=left" --set="peers[0].address={{ .LEFT_IP }}" --set="peers[1].name=middle" --set="peers[1].address={{ .MIDDLE_IP }}" --set="peers[2].name=right" --set="peers[2].address={{ .RIGHT_IP }}" --set="image.tag=dev" --set="image.repository=localhost/redpanda-operator"
      - helm install --kube-context k3d-middle --namespace=redpanda-system redpanda-multicluster-operator ./charts/multicluster --set="node=middle" --set="apiServerExternalAddress=https://{{ .MIDDLE_IP }}:6443" --set="peers[0].name=left" --set="peers[0].address={{ .LEFT_IP }}" --set="peers[1].name=middle" --set="peers[1].address={{ .MIDDLE_IP }}" --set="peers[2].name=right" --set="peers[2].address={{ .RIGHT_IP }}" --set="image.tag=dev" --set="image.repository=localhost/redpanda-operator"
      - helm install --kube-context k3d-right --namespace=redpanda-system redpanda-multicluster-operator ./charts/multicluster --set="node=right" --set="apiServerExternalAddress=https://{{ .RIGHT_IP }}:6443" --set="peers[0].name=left" --set="peers[0].address={{ .LEFT_IP }}" --set="peers[1].name=middle" --set="peers[1].address={{ .MIDDLE_IP }}" --set="peers[2].name=right" --set="peers[2].address={{ .RIGHT_IP }}" --set="image.tag=dev" --set="image.repository=localhost/redpanda-operator"

  multicluster-fixtures:
    cmds:
      - kubectl apply -f ./charts/multicluster/fixtures/cluster.yaml --context k3d-left
      - kubectl apply -f ./charts/multicluster/fixtures/cluster.yaml --context k3d-right
      - kubectl apply -f ./charts/multicluster/fixtures/cluster.yaml --context k3d-middle

  rm-multicluster-fixtures:
    cmds:
      - kubectl delete -f ./charts/multicluster/fixtures/cluster.yaml --context k3d-left
      - kubectl delete -f ./charts/multicluster/fixtures/cluster.yaml --context k3d-right
      - kubectl delete -f ./charts/multicluster/fixtures/cluster.yaml --context k3d-middle

  rm-multicluster:
    cmds:
      - helm delete --kube-context k3d-left --namespace=redpanda-system redpanda-multicluster-operator
      - helm delete --kube-context k3d-middle --namespace=redpanda-system redpanda-multicluster-operator
      - helm delete --kube-context k3d-right --namespace=redpanda-system redpanda-multicluster-operator