# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bases/redpanda.vectorized.io_clusters.yaml
- bases/redpanda.vectorized.io_consoles.yaml
- bases/cluster.redpanda.com_redpandas.yaml
- bases/cluster.redpanda.com_topics.yaml
#+kubebuilder:scaffold:crdkustomizeresource
- bases/toolkit.fluxcd.io/helm-controller.yaml
- bases/toolkit.fluxcd.io/source-controller.yaml

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- path: patches/webhook_in_clusters.yaml
- path: patches/webhook_in_redpanda_consoles.yaml
- path: patches/webhook_in_cluster.redpanda.com_topics.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- path: patches/cainjection_in_clusters.yaml
- path: patches/cainjection_in_redpanda_consoles.yaml
- path: patches/cainjection_in_cluster.redpanda.com_topics.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# patches CRD to re-add removed fields from beta CRDs
- path: patches/re-add-checksum-field_in_source.toolkit.fluxcd.io.yaml
  target:
    kind: CustomResourceDefinition
    name: "^(buckets|helmcharts|helmrepositories).source.toolkit.fluxcd.io$"
- path: patches/re-add-checksum-field_in_gitrepositories.source.toolkit.fluxcd.io.yaml
  target:
    kind: CustomResourceDefinition
    name: gitrepositories.source.toolkit.fluxcd.io
- path: patches/re-add-checksum-field_in_ocirepositories.source.toolkit.fluxcd.io.yaml
  target:
    kind: CustomResourceDefinition
    name: ocirepositories.source.toolkit.fluxcd.io
- path: patches/re-add-timeout-default_in_helmrepositories.source.toolkit.fluxcd.io.yaml
  target:
    kind: CustomResourceDefinition
    name: helmrepositories.source.toolkit.fluxcd.io

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
