resources:
- bases/operator/role.yaml
- bases/operator/role_binding.yaml
# Comment the following line if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
- bases/auth_proxy
