// Copyright 2025 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// NodePoolStatusApplyConfiguration represents an declarative configuration of the NodePoolStatus type for use
// with apply.
type NodePoolStatusApplyConfiguration struct {
	Replicas          *int32 `json:"replicas,omitempty"`
	DesiredReplicas   *int32 `json:"desiredReplicas,omitempty"`
	OutOfDateReplicas *int32 `json:"outOfDateReplicas,omitempty"`
	UpToDateReplicas  *int32 `json:"upToDateReplicas,omitempty"`
	CondemnedReplicas *int32 `json:"condemnedReplicas,omitempty"`
	ReadyReplicas     *int32 `json:"readyReplicas,omitempty"`
	RunningReplicas   *int32 `json:"runningReplicas,omitempty"`
}

// NodePoolStatusApplyConfiguration constructs an declarative configuration of the NodePoolStatus type for use with
// apply.
func NodePoolStatus() *NodePoolStatusApplyConfiguration {
	return &NodePoolStatusApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *NodePoolStatusApplyConfiguration) WithReplicas(value int32) *NodePoolStatusApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithDesiredReplicas sets the DesiredReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredReplicas field is set to the value of the last call.
func (b *NodePoolStatusApplyConfiguration) WithDesiredReplicas(value int32) *NodePoolStatusApplyConfiguration {
	b.DesiredReplicas = &value
	return b
}

// WithOutOfDateReplicas sets the OutOfDateReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OutOfDateReplicas field is set to the value of the last call.
func (b *NodePoolStatusApplyConfiguration) WithOutOfDateReplicas(value int32) *NodePoolStatusApplyConfiguration {
	b.OutOfDateReplicas = &value
	return b
}

// WithUpToDateReplicas sets the UpToDateReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpToDateReplicas field is set to the value of the last call.
func (b *NodePoolStatusApplyConfiguration) WithUpToDateReplicas(value int32) *NodePoolStatusApplyConfiguration {
	b.UpToDateReplicas = &value
	return b
}

// WithCondemnedReplicas sets the CondemnedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CondemnedReplicas field is set to the value of the last call.
func (b *NodePoolStatusApplyConfiguration) WithCondemnedReplicas(value int32) *NodePoolStatusApplyConfiguration {
	b.CondemnedReplicas = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *NodePoolStatusApplyConfiguration) WithReadyReplicas(value int32) *NodePoolStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithRunningReplicas sets the RunningReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RunningReplicas field is set to the value of the last call.
func (b *NodePoolStatusApplyConfiguration) WithRunningReplicas(value int32) *NodePoolStatusApplyConfiguration {
	b.RunningReplicas = &value
	return b
}
