// Copyright 2025 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// AdminAPISpecApplyConfiguration represents an declarative configuration of the AdminAPISpec type for use
// with apply.
type AdminAPISpecApplyConfiguration struct {
	URLs []string                     `json:"urls,omitempty"`
	TLS  *CommonTLSApplyConfiguration `json:"tls,omitempty"`
	SASL *AdminSASLApplyConfiguration `json:"sasl,omitempty"`
}

// AdminAPISpecApplyConfiguration constructs an declarative configuration of the AdminAPISpec type for use with
// apply.
func AdminAPISpec() *AdminAPISpecApplyConfiguration {
	return &AdminAPISpecApplyConfiguration{}
}

// WithURLs adds the given value to the URLs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the URLs field.
func (b *AdminAPISpecApplyConfiguration) WithURLs(values ...string) *AdminAPISpecApplyConfiguration {
	for i := range values {
		b.URLs = append(b.URLs, values[i])
	}
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *AdminAPISpecApplyConfiguration) WithTLS(value *CommonTLSApplyConfiguration) *AdminAPISpecApplyConfiguration {
	b.TLS = value
	return b
}

// WithSASL sets the SASL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SASL field is set to the value of the last call.
func (b *AdminAPISpecApplyConfiguration) WithSASL(value *AdminSASLApplyConfiguration) *AdminAPISpecApplyConfiguration {
	b.SASL = value
	return b
}
