// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// AuthApplyConfiguration represents a declarative configuration of the Auth type for use
// with apply.
type AuthApplyConfiguration struct {
	SASL *SASLApplyConfiguration `json:"sasl,omitempty"`
}

// AuthApplyConfiguration constructs a declarative configuration of the Auth type for use with
// apply.
func Auth() *AuthApplyConfiguration {
	return &AuthApplyConfiguration{}
}

// WithSASL sets the SASL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SASL field is set to the value of the last call.
func (b *AuthApplyConfiguration) WithSASL(value *SASLApplyConfiguration) *AuthApplyConfiguration {
	b.SASL = value
	return b
}
