// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// BrokerPoolStatusApplyConfiguration represents a declarative configuration of the BrokerPoolStatus type for use
// with apply.
type BrokerPoolStatusApplyConfiguration struct {
	EmbeddedBrokerPoolStatusApplyConfiguration `json:",inline"`
	DeployedGeneration                         *int64                           `json:"deployedGeneration,omitempty"`
	Conditions                                 []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// BrokerPoolStatusApplyConfiguration constructs a declarative configuration of the BrokerPoolStatus type for use with
// apply.
func BrokerPoolStatus() *BrokerPoolStatusApplyConfiguration {
	return &BrokerPoolStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *BrokerPoolStatusApplyConfiguration) WithName(value string) *BrokerPoolStatusApplyConfiguration {
	b.EmbeddedBrokerPoolStatusApplyConfiguration.Name = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *BrokerPoolStatusApplyConfiguration) WithReplicas(value int32) *BrokerPoolStatusApplyConfiguration {
	b.EmbeddedBrokerPoolStatusApplyConfiguration.Replicas = &value
	return b
}

// WithDesiredReplicas sets the DesiredReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredReplicas field is set to the value of the last call.
func (b *BrokerPoolStatusApplyConfiguration) WithDesiredReplicas(value int32) *BrokerPoolStatusApplyConfiguration {
	b.EmbeddedBrokerPoolStatusApplyConfiguration.DesiredReplicas = &value
	return b
}

// WithOutOfDateReplicas sets the OutOfDateReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OutOfDateReplicas field is set to the value of the last call.
func (b *BrokerPoolStatusApplyConfiguration) WithOutOfDateReplicas(value int32) *BrokerPoolStatusApplyConfiguration {
	b.EmbeddedBrokerPoolStatusApplyConfiguration.OutOfDateReplicas = &value
	return b
}

// WithUpToDateReplicas sets the UpToDateReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpToDateReplicas field is set to the value of the last call.
func (b *BrokerPoolStatusApplyConfiguration) WithUpToDateReplicas(value int32) *BrokerPoolStatusApplyConfiguration {
	b.EmbeddedBrokerPoolStatusApplyConfiguration.UpToDateReplicas = &value
	return b
}

// WithCondemnedReplicas sets the CondemnedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CondemnedReplicas field is set to the value of the last call.
func (b *BrokerPoolStatusApplyConfiguration) WithCondemnedReplicas(value int32) *BrokerPoolStatusApplyConfiguration {
	b.EmbeddedBrokerPoolStatusApplyConfiguration.CondemnedReplicas = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *BrokerPoolStatusApplyConfiguration) WithReadyReplicas(value int32) *BrokerPoolStatusApplyConfiguration {
	b.EmbeddedBrokerPoolStatusApplyConfiguration.ReadyReplicas = &value
	return b
}

// WithRunningReplicas sets the RunningReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RunningReplicas field is set to the value of the last call.
func (b *BrokerPoolStatusApplyConfiguration) WithRunningReplicas(value int32) *BrokerPoolStatusApplyConfiguration {
	b.EmbeddedBrokerPoolStatusApplyConfiguration.RunningReplicas = &value
	return b
}

// WithDeployedGeneration sets the DeployedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeployedGeneration field is set to the value of the last call.
func (b *BrokerPoolStatusApplyConfiguration) WithDeployedGeneration(value int64) *BrokerPoolStatusApplyConfiguration {
	b.DeployedGeneration = &value
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *BrokerPoolStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *BrokerPoolStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
