// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// BrokerPerPodServicesApplyConfiguration represents a declarative configuration of the BrokerPerPodServices type for use
// with apply.
type BrokerPerPodServicesApplyConfiguration struct {
	Local  *BrokerPerPodServiceOverrideApplyConfiguration `json:"local,omitempty"`
	Remote *BrokerPerPodServiceOverrideApplyConfiguration `json:"remote,omitempty"`
}

// BrokerPerPodServicesApplyConfiguration constructs a declarative configuration of the BrokerPerPodServices type for use with
// apply.
func BrokerPerPodServices() *BrokerPerPodServicesApplyConfiguration {
	return &BrokerPerPodServicesApplyConfiguration{}
}

// WithLocal sets the Local field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Local field is set to the value of the last call.
func (b *BrokerPerPodServicesApplyConfiguration) WithLocal(value *BrokerPerPodServiceOverrideApplyConfiguration) *BrokerPerPodServicesApplyConfiguration {
	b.Local = value
	return b
}

// WithRemote sets the Remote field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Remote field is set to the value of the last call.
func (b *BrokerPerPodServicesApplyConfiguration) WithRemote(value *BrokerPerPodServiceOverrideApplyConfiguration) *BrokerPerPodServicesApplyConfiguration {
	b.Remote = value
	return b
}
