// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
)

// BrokerPoolSpecApplyConfiguration represents a declarative configuration of the BrokerPoolSpec type for use
// with apply.
type BrokerPoolSpecApplyConfiguration struct {
	EmbeddedBrokerPoolSpecApplyConfiguration `json:",inline"`
	ClusterRef                               *ClusterRefApplyConfiguration `json:"clusterRef,omitempty"`
}

// BrokerPoolSpecApplyConfiguration constructs a declarative configuration of the BrokerPoolSpec type for use with
// apply.
func BrokerPoolSpec() *BrokerPoolSpecApplyConfiguration {
	return &BrokerPoolSpecApplyConfiguration{}
}

// WithAdditionalSelectorLabels puts the entries into the AdditionalSelectorLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the AdditionalSelectorLabels field,
// overwriting an existing map entries in AdditionalSelectorLabels field with the same key.
func (b *BrokerPoolSpecApplyConfiguration) WithAdditionalSelectorLabels(entries map[string]string) *BrokerPoolSpecApplyConfiguration {
	if b.EmbeddedBrokerPoolSpecApplyConfiguration.AdditionalSelectorLabels == nil && len(entries) > 0 {
		b.EmbeddedBrokerPoolSpecApplyConfiguration.AdditionalSelectorLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.EmbeddedBrokerPoolSpecApplyConfiguration.AdditionalSelectorLabels[k] = v
	}
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithReplicas(value int32) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.Replicas = &value
	return b
}

// WithAdditionalRedpandaCmdFlags adds the given value to the AdditionalRedpandaCmdFlags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalRedpandaCmdFlags field.
func (b *BrokerPoolSpecApplyConfiguration) WithAdditionalRedpandaCmdFlags(values ...string) *BrokerPoolSpecApplyConfiguration {
	for i := range values {
		b.EmbeddedBrokerPoolSpecApplyConfiguration.AdditionalRedpandaCmdFlags = append(b.EmbeddedBrokerPoolSpecApplyConfiguration.AdditionalRedpandaCmdFlags, values[i])
	}
	return b
}

// WithPodTemplate sets the PodTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplate field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithPodTemplate(value *PodTemplateApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.PodTemplate = value
	return b
}

// WithServices sets the Services field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Services field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithServices(value *NodePoolServicesApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.Services = value
	return b
}

// WithInitContainers sets the InitContainers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitContainers field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithInitContainers(value *PoolInitContainersApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.InitContainers = value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithImage(value *RedpandaImageApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.Image = value
	return b
}

// WithSidecarImage sets the SidecarImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SidecarImage field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithSidecarImage(value *RedpandaImageApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.SidecarImage = value
	return b
}

// WithInitContainerImage sets the InitContainerImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitContainerImage field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithInitContainerImage(value *InitContainerImageApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.InitContainerImage = value
	return b
}

// WithPersistentVolumeClaimRetentionPolicy sets the PersistentVolumeClaimRetentionPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PersistentVolumeClaimRetentionPolicy field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithPersistentVolumeClaimRetentionPolicy(value v1.StatefulSetPersistentVolumeClaimRetentionPolicy) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.PersistentVolumeClaimRetentionPolicy = &value
	return b
}

// WithClusterDomain sets the ClusterDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterDomain field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithClusterDomain(value string) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.ClusterDomain = &value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithTLS(value *TLSApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.TLS = value
	return b
}

// WithExternal sets the External field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the External field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithExternal(value *ExternalApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.External = value
	return b
}

// WithListeners sets the Listeners field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Listeners field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithListeners(value *StretchListenersApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.Listeners = value
	return b
}

// WithRBAC sets the RBAC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RBAC field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithRBAC(value *RBACApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.RBAC = value
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithServiceAccount(value *ServiceAccountApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.ServiceAccount = value
	return b
}

// WithMonitoring sets the Monitoring field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Monitoring field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithMonitoring(value *MonitoringApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.Monitoring = value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithStorage(value *StretchStorageApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.Storage = value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithResources(value *StretchResourcesApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.Resources = value
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *BrokerPoolSpecApplyConfiguration) WithImagePullSecrets(values ...corev1.LocalObjectReference) *BrokerPoolSpecApplyConfiguration {
	for i := range values {
		b.EmbeddedBrokerPoolSpecApplyConfiguration.ImagePullSecrets = append(b.EmbeddedBrokerPoolSpecApplyConfiguration.ImagePullSecrets, values[i])
	}
	return b
}

// WithRackAwareness sets the RackAwareness field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RackAwareness field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithRackAwareness(value *RackAwarenessApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.RackAwareness = value
	return b
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithLogging(value *StretchLoggingApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.Logging = value
	return b
}

// WithClusterRef sets the ClusterRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterRef field is set to the value of the last call.
func (b *BrokerPoolSpecApplyConfiguration) WithClusterRef(value *ClusterRefApplyConfiguration) *BrokerPoolSpecApplyConfiguration {
	b.ClusterRef = value
	return b
}
