// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// BrokerStorageApplyConfiguration represents a declarative configuration of the BrokerStorage type for use
// with apply.
type BrokerStorageApplyConfiguration struct {
	VolumeClaimTemplates []BrokerVolumeClaimApplyConfiguration `json:"volumeClaimTemplates,omitempty"`
	ExistingClaims       []ExistingClaimApplyConfiguration     `json:"existingClaims,omitempty"`
}

// BrokerStorageApplyConfiguration constructs a declarative configuration of the BrokerStorage type for use with
// apply.
func BrokerStorage() *BrokerStorageApplyConfiguration {
	return &BrokerStorageApplyConfiguration{}
}

// WithVolumeClaimTemplates adds the given value to the VolumeClaimTemplates field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the VolumeClaimTemplates field.
func (b *BrokerStorageApplyConfiguration) WithVolumeClaimTemplates(values ...*BrokerVolumeClaimApplyConfiguration) *BrokerStorageApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithVolumeClaimTemplates")
		}
		b.VolumeClaimTemplates = append(b.VolumeClaimTemplates, *values[i])
	}
	return b
}

// WithExistingClaims adds the given value to the ExistingClaims field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ExistingClaims field.
func (b *BrokerStorageApplyConfiguration) WithExistingClaims(values ...*ExistingClaimApplyConfiguration) *BrokerStorageApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithExistingClaims")
		}
		b.ExistingClaims = append(b.ExistingClaims, *values[i])
	}
	return b
}
