// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/core/v1"
)

// EmbeddedBrokerPoolSpecApplyConfiguration represents a declarative configuration of the EmbeddedBrokerPoolSpec type for use
// with apply.
type EmbeddedBrokerPoolSpecApplyConfiguration struct {
	AdditionalSelectorLabels   map[string]string                     `json:"additionalSelectorLabels,omitempty"`
	Replicas                   *int32                                `json:"replicas,omitempty"`
	AdditionalRedpandaCmdFlags []string                              `json:"additionalRedpandaCmdFlags,omitempty"`
	PodTemplate                *PodTemplateApplyConfiguration        `json:"podTemplate,omitempty"`
	Services                   *NodePoolServicesApplyConfiguration   `json:"services,omitempty"`
	InitContainers             *PoolInitContainersApplyConfiguration `json:"initContainers,omitempty"`
	Image                      *RedpandaImageApplyConfiguration      `json:"image,omitempty"`
	SidecarImage               *RedpandaImageApplyConfiguration      `json:"sidecarImage,omitempty"`
	InitContainerImage         *InitContainerImageApplyConfiguration `json:"initContainerImage,omitempty"`
	ClusterDomain              *string                               `json:"clusterDomain,omitempty"`
	TLS                        *TLSApplyConfiguration                `json:"tls,omitempty"`
	External                   *ExternalApplyConfiguration           `json:"external,omitempty"`
	Listeners                  *StretchListenersApplyConfiguration   `json:"listeners,omitempty"`
	RBAC                       *RBACApplyConfiguration               `json:"rbac,omitempty"`
	ServiceAccount             *ServiceAccountApplyConfiguration     `json:"serviceAccount,omitempty"`
	Monitoring                 *MonitoringApplyConfiguration         `json:"monitoring,omitempty"`
	Storage                    *StretchStorageApplyConfiguration     `json:"storage,omitempty"`
	Resources                  *StretchResourcesApplyConfiguration   `json:"resources,omitempty"`
	ImagePullSecrets           []v1.LocalObjectReference             `json:"imagePullSecrets,omitempty"`
	RackAwareness              *RackAwarenessApplyConfiguration      `json:"rackAwareness,omitempty"`
	Logging                    *StretchLoggingApplyConfiguration     `json:"logging,omitempty"`
}

// EmbeddedBrokerPoolSpecApplyConfiguration constructs a declarative configuration of the EmbeddedBrokerPoolSpec type for use with
// apply.
func EmbeddedBrokerPoolSpec() *EmbeddedBrokerPoolSpecApplyConfiguration {
	return &EmbeddedBrokerPoolSpecApplyConfiguration{}
}

// WithAdditionalSelectorLabels puts the entries into the AdditionalSelectorLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the AdditionalSelectorLabels field,
// overwriting an existing map entries in AdditionalSelectorLabels field with the same key.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithAdditionalSelectorLabels(entries map[string]string) *EmbeddedBrokerPoolSpecApplyConfiguration {
	if b.AdditionalSelectorLabels == nil && len(entries) > 0 {
		b.AdditionalSelectorLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.AdditionalSelectorLabels[k] = v
	}
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithReplicas(value int32) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithAdditionalRedpandaCmdFlags adds the given value to the AdditionalRedpandaCmdFlags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalRedpandaCmdFlags field.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithAdditionalRedpandaCmdFlags(values ...string) *EmbeddedBrokerPoolSpecApplyConfiguration {
	for i := range values {
		b.AdditionalRedpandaCmdFlags = append(b.AdditionalRedpandaCmdFlags, values[i])
	}
	return b
}

// WithPodTemplate sets the PodTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplate field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithPodTemplate(value *PodTemplateApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.PodTemplate = value
	return b
}

// WithServices sets the Services field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Services field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithServices(value *NodePoolServicesApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.Services = value
	return b
}

// WithInitContainers sets the InitContainers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitContainers field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithInitContainers(value *PoolInitContainersApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.InitContainers = value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithImage(value *RedpandaImageApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.Image = value
	return b
}

// WithSidecarImage sets the SidecarImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SidecarImage field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithSidecarImage(value *RedpandaImageApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.SidecarImage = value
	return b
}

// WithInitContainerImage sets the InitContainerImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitContainerImage field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithInitContainerImage(value *InitContainerImageApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.InitContainerImage = value
	return b
}

// WithClusterDomain sets the ClusterDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterDomain field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithClusterDomain(value string) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.ClusterDomain = &value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithTLS(value *TLSApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.TLS = value
	return b
}

// WithExternal sets the External field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the External field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithExternal(value *ExternalApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.External = value
	return b
}

// WithListeners sets the Listeners field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Listeners field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithListeners(value *StretchListenersApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.Listeners = value
	return b
}

// WithRBAC sets the RBAC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RBAC field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithRBAC(value *RBACApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.RBAC = value
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithServiceAccount(value *ServiceAccountApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.ServiceAccount = value
	return b
}

// WithMonitoring sets the Monitoring field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Monitoring field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithMonitoring(value *MonitoringApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.Monitoring = value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithStorage(value *StretchStorageApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.Storage = value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithResources(value *StretchResourcesApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.Resources = value
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithImagePullSecrets(values ...v1.LocalObjectReference) *EmbeddedBrokerPoolSpecApplyConfiguration {
	for i := range values {
		b.ImagePullSecrets = append(b.ImagePullSecrets, values[i])
	}
	return b
}

// WithRackAwareness sets the RackAwareness field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RackAwareness field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithRackAwareness(value *RackAwarenessApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.RackAwareness = value
	return b
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithLogging(value *StretchLoggingApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.Logging = value
	return b
}
