// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// EmbeddedBrokerPoolSpecApplyConfiguration represents a declarative configuration of the EmbeddedBrokerPoolSpec type for use
// with apply.
type EmbeddedBrokerPoolSpecApplyConfiguration struct {
	AdditionalSelectorLabels   map[string]string                     `json:"additionalSelectorLabels,omitempty"`
	Replicas                   *int32                                `json:"replicas,omitempty"`
	AdditionalRedpandaCmdFlags []string                              `json:"additionalRedpandaCmdFlags,omitempty"`
	PodTemplate                *PodTemplateApplyConfiguration        `json:"podTemplate,omitempty"`
	Services                   *NodePoolServicesApplyConfiguration   `json:"services,omitempty"`
	InitContainers             *PoolInitContainersApplyConfiguration `json:"initContainers,omitempty"`
	Image                      *RedpandaImageApplyConfiguration      `json:"image,omitempty"`
	SidecarImage               *RedpandaImageApplyConfiguration      `json:"sidecarImage,omitempty"`
	InitContainerImage         *InitContainerImageApplyConfiguration `json:"initContainerImage,omitempty"`
}

// EmbeddedBrokerPoolSpecApplyConfiguration constructs a declarative configuration of the EmbeddedBrokerPoolSpec type for use with
// apply.
func EmbeddedBrokerPoolSpec() *EmbeddedBrokerPoolSpecApplyConfiguration {
	return &EmbeddedBrokerPoolSpecApplyConfiguration{}
}

// WithAdditionalSelectorLabels puts the entries into the AdditionalSelectorLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the AdditionalSelectorLabels field,
// overwriting an existing map entries in AdditionalSelectorLabels field with the same key.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithAdditionalSelectorLabels(entries map[string]string) *EmbeddedBrokerPoolSpecApplyConfiguration {
	if b.AdditionalSelectorLabels == nil && len(entries) > 0 {
		b.AdditionalSelectorLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.AdditionalSelectorLabels[k] = v
	}
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithReplicas(value int32) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithAdditionalRedpandaCmdFlags adds the given value to the AdditionalRedpandaCmdFlags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalRedpandaCmdFlags field.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithAdditionalRedpandaCmdFlags(values ...string) *EmbeddedBrokerPoolSpecApplyConfiguration {
	for i := range values {
		b.AdditionalRedpandaCmdFlags = append(b.AdditionalRedpandaCmdFlags, values[i])
	}
	return b
}

// WithPodTemplate sets the PodTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplate field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithPodTemplate(value *PodTemplateApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.PodTemplate = value
	return b
}

// WithServices sets the Services field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Services field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithServices(value *NodePoolServicesApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.Services = value
	return b
}

// WithInitContainers sets the InitContainers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitContainers field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithInitContainers(value *PoolInitContainersApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.InitContainers = value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithImage(value *RedpandaImageApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.Image = value
	return b
}

// WithSidecarImage sets the SidecarImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SidecarImage field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithSidecarImage(value *RedpandaImageApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.SidecarImage = value
	return b
}

// WithInitContainerImage sets the InitContainerImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitContainerImage field is set to the value of the last call.
func (b *EmbeddedBrokerPoolSpecApplyConfiguration) WithInitContainerImage(value *InitContainerImageApplyConfiguration) *EmbeddedBrokerPoolSpecApplyConfiguration {
	b.InitContainerImage = value
	return b
}
