// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// GroupSpecApplyConfiguration represents a declarative configuration of the GroupSpec type for use
// with apply.
type GroupSpecApplyConfiguration struct {
	ClusterSource *ClusterSourceApplyConfiguration          `json:"cluster,omitempty"`
	Authorization *GroupAuthorizationSpecApplyConfiguration `json:"authorization,omitempty"`
}

// GroupSpecApplyConfiguration constructs a declarative configuration of the GroupSpec type for use with
// apply.
func GroupSpec() *GroupSpecApplyConfiguration {
	return &GroupSpecApplyConfiguration{}
}

// WithClusterSource sets the ClusterSource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterSource field is set to the value of the last call.
func (b *GroupSpecApplyConfiguration) WithClusterSource(value *ClusterSourceApplyConfiguration) *GroupSpecApplyConfiguration {
	b.ClusterSource = value
	return b
}

// WithAuthorization sets the Authorization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Authorization field is set to the value of the last call.
func (b *GroupSpecApplyConfiguration) WithAuthorization(value *GroupAuthorizationSpecApplyConfiguration) *GroupSpecApplyConfiguration {
	b.Authorization = value
	return b
}
