// Copyright 2025 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// MirrorTopicOptionsApplyConfiguration represents a declarative configuration of the MirrorTopicOptions type for use
// with apply.
type MirrorTopicOptionsApplyConfiguration struct {
	AutoCreateTopics *AutoCreateTopicsApplyConfiguration `json:"autoCreateTopics,omitempty"`
	Prefix           *string                             `json:"prefix,omitempty"`
}

// MirrorTopicOptionsApplyConfiguration constructs a declarative configuration of the MirrorTopicOptions type for use with
// apply.
func MirrorTopicOptions() *MirrorTopicOptionsApplyConfiguration {
	return &MirrorTopicOptionsApplyConfiguration{}
}

// WithAutoCreateTopics sets the AutoCreateTopics field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AutoCreateTopics field is set to the value of the last call.
func (b *MirrorTopicOptionsApplyConfiguration) WithAutoCreateTopics(value *AutoCreateTopicsApplyConfiguration) *MirrorTopicOptionsApplyConfiguration {
	b.AutoCreateTopics = value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *MirrorTopicOptionsApplyConfiguration) WithPrefix(value string) *MirrorTopicOptionsApplyConfiguration {
	b.Prefix = &value
	return b
}
