// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	redpandav1alpha2 "github.com/redpanda-data/redpanda-operator/operator/api/redpanda/v1alpha2"
)

// NetworkingApplyConfiguration represents a declarative configuration of the Networking type for use
// with apply.
type NetworkingApplyConfiguration struct {
	CrossClusterMode *redpandav1alpha2.CrossClusterMode `json:"crossClusterMode,omitempty"`
}

// NetworkingApplyConfiguration constructs a declarative configuration of the Networking type for use with
// apply.
func Networking() *NetworkingApplyConfiguration {
	return &NetworkingApplyConfiguration{}
}

// WithCrossClusterMode sets the CrossClusterMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CrossClusterMode field is set to the value of the last call.
func (b *NetworkingApplyConfiguration) WithCrossClusterMode(value redpandav1alpha2.CrossClusterMode) *NetworkingApplyConfiguration {
	b.CrossClusterMode = &value
	return b
}
