// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/core/v1"
)

// NodePoolSpecApplyConfiguration represents a declarative configuration of the NodePoolSpec type for use
// with apply.
type NodePoolSpecApplyConfiguration struct {
	EmbeddedNodePoolSpecApplyConfiguration `json:",inline"`
	ClusterRef                             *ClusterRefApplyConfiguration `json:"clusterRef,omitempty"`
}

// NodePoolSpecApplyConfiguration constructs a declarative configuration of the NodePoolSpec type for use with
// apply.
func NodePoolSpec() *NodePoolSpecApplyConfiguration {
	return &NodePoolSpecApplyConfiguration{}
}

// WithAdditionalSelectorLabels puts the entries into the AdditionalSelectorLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the AdditionalSelectorLabels field,
// overwriting an existing map entries in AdditionalSelectorLabels field with the same key.
func (b *NodePoolSpecApplyConfiguration) WithAdditionalSelectorLabels(entries map[string]string) *NodePoolSpecApplyConfiguration {
	if b.EmbeddedNodePoolSpecApplyConfiguration.AdditionalSelectorLabels == nil && len(entries) > 0 {
		b.EmbeddedNodePoolSpecApplyConfiguration.AdditionalSelectorLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.EmbeddedNodePoolSpecApplyConfiguration.AdditionalSelectorLabels[k] = v
	}
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithReplicas(value int32) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.Replicas = &value
	return b
}

// WithAdditionalRedpandaCmdFlags adds the given value to the AdditionalRedpandaCmdFlags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalRedpandaCmdFlags field.
func (b *NodePoolSpecApplyConfiguration) WithAdditionalRedpandaCmdFlags(values ...string) *NodePoolSpecApplyConfiguration {
	for i := range values {
		b.EmbeddedNodePoolSpecApplyConfiguration.AdditionalRedpandaCmdFlags = append(b.EmbeddedNodePoolSpecApplyConfiguration.AdditionalRedpandaCmdFlags, values[i])
	}
	return b
}

// WithPodTemplate sets the PodTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplate field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithPodTemplate(value *PodTemplateApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.PodTemplate = value
	return b
}

// WithServices sets the Services field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Services field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithServices(value *NodePoolServicesApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.Services = value
	return b
}

// WithInitContainers sets the InitContainers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitContainers field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithInitContainers(value *PoolInitContainersApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.InitContainers = value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithImage(value *RedpandaImageApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.Image = value
	return b
}

// WithSidecarImage sets the SidecarImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SidecarImage field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithSidecarImage(value *RedpandaImageApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.SidecarImage = value
	return b
}

// WithInitContainerImage sets the InitContainerImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitContainerImage field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithInitContainerImage(value *InitContainerImageApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.InitContainerImage = value
	return b
}

// WithClusterDomain sets the ClusterDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterDomain field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithClusterDomain(value string) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.ClusterDomain = &value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithTLS(value *TLSApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.TLS = value
	return b
}

// WithExternal sets the External field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the External field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithExternal(value *ExternalApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.External = value
	return b
}

// WithListeners sets the Listeners field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Listeners field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithListeners(value *StretchListenersApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.Listeners = value
	return b
}

// WithRBAC sets the RBAC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RBAC field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithRBAC(value *RBACApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.RBAC = value
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithServiceAccount(value *ServiceAccountApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.ServiceAccount = value
	return b
}

// WithMonitoring sets the Monitoring field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Monitoring field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithMonitoring(value *MonitoringApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.Monitoring = value
	return b
}

// WithRackAwareness sets the RackAwareness field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RackAwareness field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithRackAwareness(value *RackAwarenessApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.RackAwareness = value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithStorage(value *StretchStorageApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.Storage = value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithResources(value *StretchResourcesApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.Resources = value
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *NodePoolSpecApplyConfiguration) WithImagePullSecrets(values ...v1.LocalObjectReference) *NodePoolSpecApplyConfiguration {
	for i := range values {
		b.EmbeddedNodePoolSpecApplyConfiguration.ImagePullSecrets = append(b.EmbeddedNodePoolSpecApplyConfiguration.ImagePullSecrets, values[i])
	}
	return b
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithLogging(value *StretchLoggingApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.EmbeddedNodePoolSpecApplyConfiguration.Logging = value
	return b
}

// WithClusterRef sets the ClusterRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterRef field is set to the value of the last call.
func (b *NodePoolSpecApplyConfiguration) WithClusterRef(value *ClusterRefApplyConfiguration) *NodePoolSpecApplyConfiguration {
	b.ClusterRef = value
	return b
}
