// Copyright 2025 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// PodAntiAffinityApplyConfiguration represents a declarative configuration of the PodAntiAffinity type for use
// with apply.
type PodAntiAffinityApplyConfiguration struct {
	TopologyKey *string               `json:"topologyKey,omitempty"`
	Type        *string               `json:"type,omitempty"`
	Weight      *int                  `json:"weight,omitempty"`
	Custom      *runtime.RawExtension `json:"custom,omitempty"`
}

// PodAntiAffinityApplyConfiguration constructs a declarative configuration of the PodAntiAffinity type for use with
// apply.
func PodAntiAffinity() *PodAntiAffinityApplyConfiguration {
	return &PodAntiAffinityApplyConfiguration{}
}

// WithTopologyKey sets the TopologyKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TopologyKey field is set to the value of the last call.
func (b *PodAntiAffinityApplyConfiguration) WithTopologyKey(value string) *PodAntiAffinityApplyConfiguration {
	b.TopologyKey = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *PodAntiAffinityApplyConfiguration) WithType(value string) *PodAntiAffinityApplyConfiguration {
	b.Type = &value
	return b
}

// WithWeight sets the Weight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weight field is set to the value of the last call.
func (b *PodAntiAffinityApplyConfiguration) WithWeight(value int) *PodAntiAffinityApplyConfiguration {
	b.Weight = &value
	return b
}

// WithCustom sets the Custom field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Custom field is set to the value of the last call.
func (b *PodAntiAffinityApplyConfiguration) WithCustom(value runtime.RawExtension) *PodAntiAffinityApplyConfiguration {
	b.Custom = &value
	return b
}
