// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// RBACApplyConfiguration represents a declarative configuration of the RBAC type for use
// with apply.
type RBACApplyConfiguration struct {
	Annotations    map[string]string `json:"annotations,omitempty"`
	Enabled        *bool             `json:"enabled,omitempty"`
	RPKDebugBundle *bool             `json:"rpkDebugBundle,omitempty"`
}

// RBACApplyConfiguration constructs a declarative configuration of the RBAC type for use with
// apply.
func RBAC() *RBACApplyConfiguration {
	return &RBACApplyConfiguration{}
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *RBACApplyConfiguration) WithAnnotations(entries map[string]string) *RBACApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *RBACApplyConfiguration) WithEnabled(value bool) *RBACApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithRPKDebugBundle sets the RPKDebugBundle field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RPKDebugBundle field is set to the value of the last call.
func (b *RBACApplyConfiguration) WithRPKDebugBundle(value bool) *RBACApplyConfiguration {
	b.RPKDebugBundle = &value
	return b
}
