// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/core/v1"
)

// RedpandaBrokerPoolSpecApplyConfiguration represents a declarative configuration of the RedpandaBrokerPoolSpec type for use
// with apply.
type RedpandaBrokerPoolSpecApplyConfiguration struct {
	EmbeddedBrokerPoolSpecApplyConfiguration `json:",inline"`
	ClusterRef                               *ClusterRefApplyConfiguration `json:"clusterRef,omitempty"`
}

// RedpandaBrokerPoolSpecApplyConfiguration constructs a declarative configuration of the RedpandaBrokerPoolSpec type for use with
// apply.
func RedpandaBrokerPoolSpec() *RedpandaBrokerPoolSpecApplyConfiguration {
	return &RedpandaBrokerPoolSpecApplyConfiguration{}
}

// WithAdditionalSelectorLabels puts the entries into the AdditionalSelectorLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the AdditionalSelectorLabels field,
// overwriting an existing map entries in AdditionalSelectorLabels field with the same key.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithAdditionalSelectorLabels(entries map[string]string) *RedpandaBrokerPoolSpecApplyConfiguration {
	if b.EmbeddedBrokerPoolSpecApplyConfiguration.AdditionalSelectorLabels == nil && len(entries) > 0 {
		b.EmbeddedBrokerPoolSpecApplyConfiguration.AdditionalSelectorLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.EmbeddedBrokerPoolSpecApplyConfiguration.AdditionalSelectorLabels[k] = v
	}
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithReplicas(value int32) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.Replicas = &value
	return b
}

// WithAdditionalRedpandaCmdFlags adds the given value to the AdditionalRedpandaCmdFlags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AdditionalRedpandaCmdFlags field.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithAdditionalRedpandaCmdFlags(values ...string) *RedpandaBrokerPoolSpecApplyConfiguration {
	for i := range values {
		b.EmbeddedBrokerPoolSpecApplyConfiguration.AdditionalRedpandaCmdFlags = append(b.EmbeddedBrokerPoolSpecApplyConfiguration.AdditionalRedpandaCmdFlags, values[i])
	}
	return b
}

// WithPodTemplate sets the PodTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodTemplate field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithPodTemplate(value *PodTemplateApplyConfiguration) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.PodTemplate = value
	return b
}

// WithServices sets the Services field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Services field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithServices(value *BrokerPoolServicesApplyConfiguration) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.Services = value
	return b
}

// WithInitContainers sets the InitContainers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitContainers field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithInitContainers(value *BrokerPoolInitContainersApplyConfiguration) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.InitContainers = value
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithImage(value *RedpandaImageApplyConfiguration) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.Image = value
	return b
}

// WithSidecarImage sets the SidecarImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SidecarImage field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithSidecarImage(value *RedpandaImageApplyConfiguration) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.SidecarImage = value
	return b
}

// WithInitContainerImage sets the InitContainerImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitContainerImage field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithInitContainerImage(value *InitContainerImageApplyConfiguration) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.InitContainerImage = value
	return b
}

// WithClusterDomain sets the ClusterDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterDomain field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithClusterDomain(value string) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.ClusterDomain = &value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithTLS(value *TLSApplyConfiguration) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.TLS = value
	return b
}

// WithExternal sets the External field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the External field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithExternal(value *ExternalApplyConfiguration) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.External = value
	return b
}

// WithListeners sets the Listeners field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Listeners field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithListeners(value *StretchListenersApplyConfiguration) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.Listeners = value
	return b
}

// WithRBAC sets the RBAC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RBAC field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithRBAC(value *RBACApplyConfiguration) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.RBAC = value
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithServiceAccount(value *ServiceAccountApplyConfiguration) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.ServiceAccount = value
	return b
}

// WithMonitoring sets the Monitoring field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Monitoring field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithMonitoring(value *MonitoringApplyConfiguration) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.Monitoring = value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithStorage(value *StretchStorageApplyConfiguration) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.Storage = value
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithResources(value *StretchResourcesApplyConfiguration) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.EmbeddedBrokerPoolSpecApplyConfiguration.Resources = value
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithImagePullSecrets(values ...v1.LocalObjectReference) *RedpandaBrokerPoolSpecApplyConfiguration {
	for i := range values {
		b.EmbeddedBrokerPoolSpecApplyConfiguration.ImagePullSecrets = append(b.EmbeddedBrokerPoolSpecApplyConfiguration.ImagePullSecrets, values[i])
	}
	return b
}

// WithClusterRef sets the ClusterRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterRef field is set to the value of the last call.
func (b *RedpandaBrokerPoolSpecApplyConfiguration) WithClusterRef(value *ClusterRefApplyConfiguration) *RedpandaBrokerPoolSpecApplyConfiguration {
	b.ClusterRef = value
	return b
}
