// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/core/v1"
	resource "k8s.io/apimachinery/pkg/api/resource"
)

// ResourcesApplyConfiguration represents a declarative configuration of the Resources type for use
// with apply.
type ResourcesApplyConfiguration struct {
	Limits   *map[v1.ResourceName]resource.Quantity `json:"limits,omitempty"`
	Requests *map[v1.ResourceName]resource.Quantity `json:"requests,omitempty"`
	CPU      *CPUApplyConfiguration                 `json:"cpu,omitempty"`
	Memory   *MemoryApplyConfiguration              `json:"memory,omitempty"`
}

// ResourcesApplyConfiguration constructs a declarative configuration of the Resources type for use with
// apply.
func Resources() *ResourcesApplyConfiguration {
	return &ResourcesApplyConfiguration{}
}

// WithLimits sets the Limits field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Limits field is set to the value of the last call.
func (b *ResourcesApplyConfiguration) WithLimits(value map[v1.ResourceName]resource.Quantity) *ResourcesApplyConfiguration {
	b.Limits = &value
	return b
}

// WithRequests sets the Requests field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Requests field is set to the value of the last call.
func (b *ResourcesApplyConfiguration) WithRequests(value map[v1.ResourceName]resource.Quantity) *ResourcesApplyConfiguration {
	b.Requests = &value
	return b
}

// WithCPU sets the CPU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CPU field is set to the value of the last call.
func (b *ResourcesApplyConfiguration) WithCPU(value *CPUApplyConfiguration) *ResourcesApplyConfiguration {
	b.CPU = value
	return b
}

// WithMemory sets the Memory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Memory field is set to the value of the last call.
func (b *ResourcesApplyConfiguration) WithMemory(value *MemoryApplyConfiguration) *ResourcesApplyConfiguration {
	b.Memory = value
	return b
}
