// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ShadowLinkRoleSyncOptionsApplyConfiguration represents a declarative configuration of the ShadowLinkRoleSyncOptions type for use
// with apply.
type ShadowLinkRoleSyncOptionsApplyConfiguration struct {
	Enabled         *bool                          `json:"enabled,omitempty"`
	Interval        *v1.Duration                   `json:"interval,omitempty"`
	Paused          *bool                          `json:"paused,omitempty"`
	RoleNameFilters []NameFilterApplyConfiguration `json:"roleNameFilters,omitempty"`
}

// ShadowLinkRoleSyncOptionsApplyConfiguration constructs a declarative configuration of the ShadowLinkRoleSyncOptions type for use with
// apply.
func ShadowLinkRoleSyncOptions() *ShadowLinkRoleSyncOptionsApplyConfiguration {
	return &ShadowLinkRoleSyncOptionsApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ShadowLinkRoleSyncOptionsApplyConfiguration) WithEnabled(value bool) *ShadowLinkRoleSyncOptionsApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *ShadowLinkRoleSyncOptionsApplyConfiguration) WithInterval(value v1.Duration) *ShadowLinkRoleSyncOptionsApplyConfiguration {
	b.Interval = &value
	return b
}

// WithPaused sets the Paused field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Paused field is set to the value of the last call.
func (b *ShadowLinkRoleSyncOptionsApplyConfiguration) WithPaused(value bool) *ShadowLinkRoleSyncOptionsApplyConfiguration {
	b.Paused = &value
	return b
}

// WithRoleNameFilters adds the given value to the RoleNameFilters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the RoleNameFilters field.
func (b *ShadowLinkRoleSyncOptionsApplyConfiguration) WithRoleNameFilters(values ...*NameFilterApplyConfiguration) *ShadowLinkRoleSyncOptionsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRoleNameFilters")
		}
		b.RoleNameFilters = append(b.RoleNameFilters, *values[i])
	}
	return b
}
