// Copyright 2025 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ShadowLinkStatusApplyConfiguration represents a declarative configuration of the ShadowLinkStatus type for use
// with apply.
type ShadowLinkStatusApplyConfiguration struct {
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
}

// ShadowLinkStatusApplyConfiguration constructs a declarative configuration of the ShadowLinkStatus type for use with
// apply.
func ShadowLinkStatus() *ShadowLinkStatusApplyConfiguration {
	return &ShadowLinkStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ShadowLinkStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ShadowLinkStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
