// Copyright 2025 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ShadowLinkTopicMetadataSyncOptionsApplyConfiguration represents a declarative configuration of the ShadowLinkTopicMetadataSyncOptions type for use
// with apply.
type ShadowLinkTopicMetadataSyncOptionsApplyConfiguration struct {
	Interval                     *v1.Duration                   `json:"interval,omitempty"`
	AutoCreateShadowTopicFilters []NameFilterApplyConfiguration `json:"autoCreateShadowTopicFilters,omitempty"`
	ShadowedTopicProperties      []string                       `json:"shadowedTopicProperties,omitempty"`
}

// ShadowLinkTopicMetadataSyncOptionsApplyConfiguration constructs a declarative configuration of the ShadowLinkTopicMetadataSyncOptions type for use with
// apply.
func ShadowLinkTopicMetadataSyncOptions() *ShadowLinkTopicMetadataSyncOptionsApplyConfiguration {
	return &ShadowLinkTopicMetadataSyncOptionsApplyConfiguration{}
}

// WithInterval sets the Interval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Interval field is set to the value of the last call.
func (b *ShadowLinkTopicMetadataSyncOptionsApplyConfiguration) WithInterval(value v1.Duration) *ShadowLinkTopicMetadataSyncOptionsApplyConfiguration {
	b.Interval = &value
	return b
}

// WithAutoCreateShadowTopicFilters adds the given value to the AutoCreateShadowTopicFilters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AutoCreateShadowTopicFilters field.
func (b *ShadowLinkTopicMetadataSyncOptionsApplyConfiguration) WithAutoCreateShadowTopicFilters(values ...*NameFilterApplyConfiguration) *ShadowLinkTopicMetadataSyncOptionsApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAutoCreateShadowTopicFilters")
		}
		b.AutoCreateShadowTopicFilters = append(b.AutoCreateShadowTopicFilters, *values[i])
	}
	return b
}

// WithShadowedTopicProperties adds the given value to the ShadowedTopicProperties field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ShadowedTopicProperties field.
func (b *ShadowLinkTopicMetadataSyncOptionsApplyConfiguration) WithShadowedTopicProperties(values ...string) *ShadowLinkTopicMetadataSyncOptionsApplyConfiguration {
	for i := range values {
		b.ShadowedTopicProperties = append(b.ShadowedTopicProperties, values[i])
	}
	return b
}
