// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// ShadowLinkSchemaRegistryTLSApplyConfiguration represents a declarative configuration of the ShadowLinkSchemaRegistryTLS type for use
// with apply.
type ShadowLinkSchemaRegistryTLSApplyConfiguration struct {
	Enabled *bool                          `json:"enabled,omitempty"`
	CaCert  *ValueSourceApplyConfiguration `json:"caCert,omitempty"`
	Cert    *ValueSourceApplyConfiguration `json:"cert,omitempty"`
	Key     *ValueSourceApplyConfiguration `json:"key,omitempty"`
}

// ShadowLinkSchemaRegistryTLSApplyConfiguration constructs a declarative configuration of the ShadowLinkSchemaRegistryTLS type for use with
// apply.
func ShadowLinkSchemaRegistryTLS() *ShadowLinkSchemaRegistryTLSApplyConfiguration {
	return &ShadowLinkSchemaRegistryTLSApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ShadowLinkSchemaRegistryTLSApplyConfiguration) WithEnabled(value bool) *ShadowLinkSchemaRegistryTLSApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithCaCert sets the CaCert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CaCert field is set to the value of the last call.
func (b *ShadowLinkSchemaRegistryTLSApplyConfiguration) WithCaCert(value *ValueSourceApplyConfiguration) *ShadowLinkSchemaRegistryTLSApplyConfiguration {
	b.CaCert = value
	return b
}

// WithCert sets the Cert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cert field is set to the value of the last call.
func (b *ShadowLinkSchemaRegistryTLSApplyConfiguration) WithCert(value *ValueSourceApplyConfiguration) *ShadowLinkSchemaRegistryTLSApplyConfiguration {
	b.Cert = value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *ShadowLinkSchemaRegistryTLSApplyConfiguration) WithKey(value *ValueSourceApplyConfiguration) *ShadowLinkSchemaRegistryTLSApplyConfiguration {
	b.Key = value
	return b
}
