// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	redpandav1alpha2 "github.com/redpanda-data/redpanda-operator/operator/api/redpanda/v1alpha2"
)

// StretchAPIListenerApplyConfiguration represents a declarative configuration of the StretchAPIListener type for use
// with apply.
type StretchAPIListenerApplyConfiguration struct {
	StretchListenerApplyConfiguration `json:",inline"`
	External                          map[string]*redpandav1alpha2.StretchExternalListener `json:"external,omitempty"`
}

// StretchAPIListenerApplyConfiguration constructs a declarative configuration of the StretchAPIListener type for use with
// apply.
func StretchAPIListener() *StretchAPIListenerApplyConfiguration {
	return &StretchAPIListenerApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *StretchAPIListenerApplyConfiguration) WithEnabled(value bool) *StretchAPIListenerApplyConfiguration {
	b.StretchListenerApplyConfiguration.Enabled = &value
	return b
}

// WithAuthenticationMethod sets the AuthenticationMethod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthenticationMethod field is set to the value of the last call.
func (b *StretchAPIListenerApplyConfiguration) WithAuthenticationMethod(value string) *StretchAPIListenerApplyConfiguration {
	b.StretchListenerApplyConfiguration.AuthenticationMethod = &value
	return b
}

// WithAppProtocol sets the AppProtocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppProtocol field is set to the value of the last call.
func (b *StretchAPIListenerApplyConfiguration) WithAppProtocol(value string) *StretchAPIListenerApplyConfiguration {
	b.StretchListenerApplyConfiguration.AppProtocol = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *StretchAPIListenerApplyConfiguration) WithPort(value int32) *StretchAPIListenerApplyConfiguration {
	b.StretchListenerApplyConfiguration.Port = &value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *StretchAPIListenerApplyConfiguration) WithTLS(value *StretchListenerTLSApplyConfiguration) *StretchAPIListenerApplyConfiguration {
	b.StretchListenerApplyConfiguration.TLS = value
	return b
}

// WithPrefixTemplate sets the PrefixTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrefixTemplate field is set to the value of the last call.
func (b *StretchAPIListenerApplyConfiguration) WithPrefixTemplate(value string) *StretchAPIListenerApplyConfiguration {
	b.StretchListenerApplyConfiguration.PrefixTemplate = &value
	return b
}

// WithExternal puts the entries into the External field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the External field,
// overwriting an existing map entries in External field with the same key.
func (b *StretchAPIListenerApplyConfiguration) WithExternal(entries map[string]*redpandav1alpha2.StretchExternalListener) *StretchAPIListenerApplyConfiguration {
	if b.External == nil && len(entries) > 0 {
		b.External = make(map[string]*redpandav1alpha2.StretchExternalListener, len(entries))
	}
	for k, v := range entries {
		b.External[k] = v
	}
	return b
}
