// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// StretchTuningApplyConfiguration represents a declarative configuration of the StretchTuning type for use
// with apply.
type StretchTuningApplyConfiguration struct {
	BallastFilePath *string `json:"ballast_file_path,omitempty"`
	BallastFileSize *string `json:"ballast_file_size,omitempty"`
	TuneAioEvents   *bool   `json:"tune_aio_events,omitempty"`
	TuneBallastFile *bool   `json:"tune_ballast_file,omitempty"`
	TuneClockSource *bool   `json:"tune_clocksource,omitempty"`
	WellKnownIo     *string `json:"well_known_io,omitempty"`
}

// StretchTuningApplyConfiguration constructs a declarative configuration of the StretchTuning type for use with
// apply.
func StretchTuning() *StretchTuningApplyConfiguration {
	return &StretchTuningApplyConfiguration{}
}

// WithBallastFilePath sets the BallastFilePath field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BallastFilePath field is set to the value of the last call.
func (b *StretchTuningApplyConfiguration) WithBallastFilePath(value string) *StretchTuningApplyConfiguration {
	b.BallastFilePath = &value
	return b
}

// WithBallastFileSize sets the BallastFileSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BallastFileSize field is set to the value of the last call.
func (b *StretchTuningApplyConfiguration) WithBallastFileSize(value string) *StretchTuningApplyConfiguration {
	b.BallastFileSize = &value
	return b
}

// WithTuneAioEvents sets the TuneAioEvents field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TuneAioEvents field is set to the value of the last call.
func (b *StretchTuningApplyConfiguration) WithTuneAioEvents(value bool) *StretchTuningApplyConfiguration {
	b.TuneAioEvents = &value
	return b
}

// WithTuneBallastFile sets the TuneBallastFile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TuneBallastFile field is set to the value of the last call.
func (b *StretchTuningApplyConfiguration) WithTuneBallastFile(value bool) *StretchTuningApplyConfiguration {
	b.TuneBallastFile = &value
	return b
}

// WithTuneClockSource sets the TuneClockSource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TuneClockSource field is set to the value of the last call.
func (b *StretchTuningApplyConfiguration) WithTuneClockSource(value bool) *StretchTuningApplyConfiguration {
	b.TuneClockSource = &value
	return b
}

// WithWellKnownIo sets the WellKnownIo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WellKnownIo field is set to the value of the last call.
func (b *StretchTuningApplyConfiguration) WithWellKnownIo(value string) *StretchTuningApplyConfiguration {
	b.WellKnownIo = &value
	return b
}
