// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// StretchLoggingApplyConfiguration represents a declarative configuration of the StretchLogging type for use
// with apply.
type StretchLoggingApplyConfiguration struct {
	LogLevel   *string                              `json:"logLevel,omitempty"`
	UsageStats *StretchUsageStatsApplyConfiguration `json:"usageStats,omitempty"`
}

// StretchLoggingApplyConfiguration constructs a declarative configuration of the StretchLogging type for use with
// apply.
func StretchLogging() *StretchLoggingApplyConfiguration {
	return &StretchLoggingApplyConfiguration{}
}

// WithLogLevel sets the LogLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogLevel field is set to the value of the last call.
func (b *StretchLoggingApplyConfiguration) WithLogLevel(value string) *StretchLoggingApplyConfiguration {
	b.LogLevel = &value
	return b
}

// WithUsageStats sets the UsageStats field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UsageStats field is set to the value of the last call.
func (b *StretchLoggingApplyConfiguration) WithUsageStats(value *StretchUsageStatsApplyConfiguration) *StretchLoggingApplyConfiguration {
	b.UsageStats = value
	return b
}
