// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/core/v1"
)

// StretchClusterSpecApplyConfiguration represents a declarative configuration of the StretchClusterSpec type for use
// with apply.
type StretchClusterSpecApplyConfiguration struct {
	CommonLabels     map[string]string                 `json:"commonLabels,omitempty"`
	Image            *RedpandaImageApplyConfiguration  `json:"image,omitempty"`
	ImagePullSecrets []v1.LocalObjectReference         `json:"imagePullSecrets,omitempty"`
	Enterprise       *EnterpriseApplyConfiguration     `json:"enterprise,omitempty"`
	RackAwareness    *RackAwarenessApplyConfiguration  `json:"rackAwareness,omitempty"`
	Logging          *LoggingApplyConfiguration        `json:"logging,omitempty"`
	AuditLogging     *AuditLoggingApplyConfiguration   `json:"auditLogging,omitempty"`
	Service          *ServiceApplyConfiguration        `json:"service,omitempty"`
	Storage          *StorageApplyConfiguration        `json:"storage,omitempty"`
	Tuning           *TuningApplyConfiguration         `json:"tuning,omitempty"`
	Config           *ConfigApplyConfiguration         `json:"config,omitempty"`
	RBAC             *RBACApplyConfiguration           `json:"rbac,omitempty"`
	ServiceAccount   *ServiceAccountApplyConfiguration `json:"serviceAccount,omitempty"`
}

// StretchClusterSpecApplyConfiguration constructs a declarative configuration of the StretchClusterSpec type for use with
// apply.
func StretchClusterSpec() *StretchClusterSpecApplyConfiguration {
	return &StretchClusterSpecApplyConfiguration{}
}

// WithCommonLabels puts the entries into the CommonLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the CommonLabels field,
// overwriting an existing map entries in CommonLabels field with the same key.
func (b *StretchClusterSpecApplyConfiguration) WithCommonLabels(entries map[string]string) *StretchClusterSpecApplyConfiguration {
	if b.CommonLabels == nil && len(entries) > 0 {
		b.CommonLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.CommonLabels[k] = v
	}
	return b
}

// WithImage sets the Image field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Image field is set to the value of the last call.
func (b *StretchClusterSpecApplyConfiguration) WithImage(value *RedpandaImageApplyConfiguration) *StretchClusterSpecApplyConfiguration {
	b.Image = value
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *StretchClusterSpecApplyConfiguration) WithImagePullSecrets(values ...v1.LocalObjectReference) *StretchClusterSpecApplyConfiguration {
	for i := range values {
		b.ImagePullSecrets = append(b.ImagePullSecrets, values[i])
	}
	return b
}

// WithEnterprise sets the Enterprise field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enterprise field is set to the value of the last call.
func (b *StretchClusterSpecApplyConfiguration) WithEnterprise(value *EnterpriseApplyConfiguration) *StretchClusterSpecApplyConfiguration {
	b.Enterprise = value
	return b
}

// WithRackAwareness sets the RackAwareness field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RackAwareness field is set to the value of the last call.
func (b *StretchClusterSpecApplyConfiguration) WithRackAwareness(value *RackAwarenessApplyConfiguration) *StretchClusterSpecApplyConfiguration {
	b.RackAwareness = value
	return b
}

// WithLogging sets the Logging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Logging field is set to the value of the last call.
func (b *StretchClusterSpecApplyConfiguration) WithLogging(value *LoggingApplyConfiguration) *StretchClusterSpecApplyConfiguration {
	b.Logging = value
	return b
}

// WithAuditLogging sets the AuditLogging field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuditLogging field is set to the value of the last call.
func (b *StretchClusterSpecApplyConfiguration) WithAuditLogging(value *AuditLoggingApplyConfiguration) *StretchClusterSpecApplyConfiguration {
	b.AuditLogging = value
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *StretchClusterSpecApplyConfiguration) WithService(value *ServiceApplyConfiguration) *StretchClusterSpecApplyConfiguration {
	b.Service = value
	return b
}

// WithStorage sets the Storage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Storage field is set to the value of the last call.
func (b *StretchClusterSpecApplyConfiguration) WithStorage(value *StorageApplyConfiguration) *StretchClusterSpecApplyConfiguration {
	b.Storage = value
	return b
}

// WithTuning sets the Tuning field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Tuning field is set to the value of the last call.
func (b *StretchClusterSpecApplyConfiguration) WithTuning(value *TuningApplyConfiguration) *StretchClusterSpecApplyConfiguration {
	b.Tuning = value
	return b
}

// WithConfig sets the Config field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Config field is set to the value of the last call.
func (b *StretchClusterSpecApplyConfiguration) WithConfig(value *ConfigApplyConfiguration) *StretchClusterSpecApplyConfiguration {
	b.Config = value
	return b
}

// WithRBAC sets the RBAC field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RBAC field is set to the value of the last call.
func (b *StretchClusterSpecApplyConfiguration) WithRBAC(value *RBACApplyConfiguration) *StretchClusterSpecApplyConfiguration {
	b.RBAC = value
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *StretchClusterSpecApplyConfiguration) WithServiceAccount(value *ServiceAccountApplyConfiguration) *StretchClusterSpecApplyConfiguration {
	b.ServiceAccount = value
	return b
}
