// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// StretchListenerTLSApplyConfiguration represents a declarative configuration of the StretchListenerTLS type for use
// with apply.
type StretchListenerTLSApplyConfiguration struct {
	Cert              *string                       `json:"cert,omitempty"`
	Enabled           *bool                         `json:"enabled,omitempty"`
	RequireClientAuth *bool                         `json:"requireClientAuth,omitempty"`
	TrustStore        *TrustStoreApplyConfiguration `json:"trustStore,omitempty"`
}

// StretchListenerTLSApplyConfiguration constructs a declarative configuration of the StretchListenerTLS type for use with
// apply.
func StretchListenerTLS() *StretchListenerTLSApplyConfiguration {
	return &StretchListenerTLSApplyConfiguration{}
}

// WithCert sets the Cert field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cert field is set to the value of the last call.
func (b *StretchListenerTLSApplyConfiguration) WithCert(value string) *StretchListenerTLSApplyConfiguration {
	b.Cert = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *StretchListenerTLSApplyConfiguration) WithEnabled(value bool) *StretchListenerTLSApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithRequireClientAuth sets the RequireClientAuth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RequireClientAuth field is set to the value of the last call.
func (b *StretchListenerTLSApplyConfiguration) WithRequireClientAuth(value bool) *StretchListenerTLSApplyConfiguration {
	b.RequireClientAuth = &value
	return b
}

// WithTrustStore sets the TrustStore field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrustStore field is set to the value of the last call.
func (b *StretchListenerTLSApplyConfiguration) WithTrustStore(value *TrustStoreApplyConfiguration) *StretchListenerTLSApplyConfiguration {
	b.TrustStore = value
	return b
}
