// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// StretchListenerApplyConfiguration represents a declarative configuration of the StretchListener type for use
// with apply.
type StretchListenerApplyConfiguration struct {
	Enabled              *bool                                 `json:"enabled,omitempty"`
	AuthenticationMethod *string                               `json:"authenticationMethod,omitempty"`
	AppProtocol          *string                               `json:"appProtocol,omitempty"`
	Port                 *int32                                `json:"port,omitempty"`
	TLS                  *StretchListenerTLSApplyConfiguration `json:"tls,omitempty"`
	PrefixTemplate       *string                               `json:"prefixTemplate,omitempty"`
}

// StretchListenerApplyConfiguration constructs a declarative configuration of the StretchListener type for use with
// apply.
func StretchListener() *StretchListenerApplyConfiguration {
	return &StretchListenerApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *StretchListenerApplyConfiguration) WithEnabled(value bool) *StretchListenerApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithAuthenticationMethod sets the AuthenticationMethod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthenticationMethod field is set to the value of the last call.
func (b *StretchListenerApplyConfiguration) WithAuthenticationMethod(value string) *StretchListenerApplyConfiguration {
	b.AuthenticationMethod = &value
	return b
}

// WithAppProtocol sets the AppProtocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AppProtocol field is set to the value of the last call.
func (b *StretchListenerApplyConfiguration) WithAppProtocol(value string) *StretchListenerApplyConfiguration {
	b.AppProtocol = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *StretchListenerApplyConfiguration) WithPort(value int32) *StretchListenerApplyConfiguration {
	b.Port = &value
	return b
}

// WithTLS sets the TLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLS field is set to the value of the last call.
func (b *StretchListenerApplyConfiguration) WithTLS(value *StretchListenerTLSApplyConfiguration) *StretchListenerApplyConfiguration {
	b.TLS = value
	return b
}

// WithPrefixTemplate sets the PrefixTemplate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PrefixTemplate field is set to the value of the last call.
func (b *StretchListenerApplyConfiguration) WithPrefixTemplate(value string) *StretchListenerApplyConfiguration {
	b.PrefixTemplate = &value
	return b
}
