// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// StretchTieredConfigApplyConfiguration represents a declarative configuration of the StretchTieredConfig type for use
// with apply.
type StretchTieredConfigApplyConfiguration struct {
	CloudStorageEnabled                     *bool   `json:"cloud_storage_enabled,omitempty"`
	CloudStorageAPIEndpoint                 *string `json:"cloud_storage_api_endpoint,omitempty"`
	CloudStorageAPIEndpointPort             *int    `json:"cloud_storage_api_endpoint_port,omitempty"`
	CloudStorageBucket                      *string `json:"cloud_storage_bucket,omitempty"`
	CloudStorageAzureContainer              *string `json:"cloud_storage_azure_container,omitempty"`
	CloudStorageAzureManagedIdentityID      *string `json:"cloud_storage_azure_managed_identity_id,omitempty"`
	CloudStorageAzureStorageAccount         *string `json:"cloud_storage_azure_storage_account,omitempty"`
	CloudStorageAzureSharedKey              *string `json:"cloud_storage_azure_shared_key,omitempty"`
	CloudStorageAzureADLSEndpoint           *string `json:"cloud_storage_azure_adls_endpoint,omitempty"`
	CloudStorageAzureADLSPort               *int    `json:"cloud_storage_azure_adls_port,omitempty"`
	CloudStorageCacheCheckInterval          *int    `json:"cloud_storage_cache_check_interval,omitempty"`
	CloudStorageCacheDirectory              *string `json:"cloud_storage_cache_directory,omitempty"`
	CloudStorageCacheSize                   *string `json:"cloud_storage_cache_size,omitempty"`
	CloudStorageCredentialsSource           *string `json:"cloud_storage_credentials_source,omitempty"`
	CloudStorageDisableTLS                  *bool   `json:"cloud_storage_disable_tls,omitempty"`
	CloudStorageEnableRemoteRead            *bool   `json:"cloud_storage_enable_remote_read,omitempty"`
	CloudStorageEnableRemoteWrite           *bool   `json:"cloud_storage_enable_remote_write,omitempty"`
	CloudStorageInitialBackoffMs            *int    `json:"cloud_storage_initial_backoff_ms,omitempty"`
	CloudStorageManifestUploadTimeoutMs     *int    `json:"cloud_storage_manifest_upload_timeout_ms,omitempty"`
	CloudStorageMaxConnectionIdleTimeMs     *int    `json:"cloud_storage_max_connection_idle_time_ms,omitempty"`
	CloudStorageMaxConnections              *int    `json:"cloud_storage_max_connections,omitempty"`
	CloudStorageRegion                      *string `json:"cloud_storage_region,omitempty"`
	CloudStorageSegmentMaxUploadIntervalSec *int    `json:"cloud_storage_segment_max_upload_interval_sec,omitempty"`
	CloudStorageSegmentUploadTimeoutMs      *int    `json:"cloud_storage_segment_upload_timeout_ms,omitempty"`
	CloudStorageTrustFile                   *string `json:"cloud_storage_trust_file,omitempty"`
	CloudStorageUploadCtrlDCoeff            *int    `json:"cloud_storage_upload_ctrl_d_coeff,omitempty"`
	CloudStorageUploadCtrlMaxShares         *int    `json:"cloud_storage_upload_ctrl_max_shares,omitempty"`
	CloudStorageUploadCtrlMinShares         *int    `json:"cloud_storage_upload_ctrl_min_shares,omitempty"`
	CloudStorageUploadCtrlPCoeff            *int    `json:"cloud_storage_upload_ctrl_p_coeff,omitempty"`
	CloudStorageUploadCtrlUpdateIntervalMs  *int    `json:"cloud_storage_upload_ctrl_update_interval_ms,omitempty"`
}

// StretchTieredConfigApplyConfiguration constructs a declarative configuration of the StretchTieredConfig type for use with
// apply.
func StretchTieredConfig() *StretchTieredConfigApplyConfiguration {
	return &StretchTieredConfigApplyConfiguration{}
}

// WithCloudStorageEnabled sets the CloudStorageEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageEnabled field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageEnabled(value bool) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageEnabled = &value
	return b
}

// WithCloudStorageAPIEndpoint sets the CloudStorageAPIEndpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageAPIEndpoint field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageAPIEndpoint(value string) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageAPIEndpoint = &value
	return b
}

// WithCloudStorageAPIEndpointPort sets the CloudStorageAPIEndpointPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageAPIEndpointPort field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageAPIEndpointPort(value int) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageAPIEndpointPort = &value
	return b
}

// WithCloudStorageBucket sets the CloudStorageBucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageBucket field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageBucket(value string) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageBucket = &value
	return b
}

// WithCloudStorageAzureContainer sets the CloudStorageAzureContainer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageAzureContainer field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageAzureContainer(value string) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageAzureContainer = &value
	return b
}

// WithCloudStorageAzureManagedIdentityID sets the CloudStorageAzureManagedIdentityID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageAzureManagedIdentityID field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageAzureManagedIdentityID(value string) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageAzureManagedIdentityID = &value
	return b
}

// WithCloudStorageAzureStorageAccount sets the CloudStorageAzureStorageAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageAzureStorageAccount field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageAzureStorageAccount(value string) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageAzureStorageAccount = &value
	return b
}

// WithCloudStorageAzureSharedKey sets the CloudStorageAzureSharedKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageAzureSharedKey field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageAzureSharedKey(value string) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageAzureSharedKey = &value
	return b
}

// WithCloudStorageAzureADLSEndpoint sets the CloudStorageAzureADLSEndpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageAzureADLSEndpoint field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageAzureADLSEndpoint(value string) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageAzureADLSEndpoint = &value
	return b
}

// WithCloudStorageAzureADLSPort sets the CloudStorageAzureADLSPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageAzureADLSPort field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageAzureADLSPort(value int) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageAzureADLSPort = &value
	return b
}

// WithCloudStorageCacheCheckInterval sets the CloudStorageCacheCheckInterval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageCacheCheckInterval field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageCacheCheckInterval(value int) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageCacheCheckInterval = &value
	return b
}

// WithCloudStorageCacheDirectory sets the CloudStorageCacheDirectory field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageCacheDirectory field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageCacheDirectory(value string) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageCacheDirectory = &value
	return b
}

// WithCloudStorageCacheSize sets the CloudStorageCacheSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageCacheSize field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageCacheSize(value string) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageCacheSize = &value
	return b
}

// WithCloudStorageCredentialsSource sets the CloudStorageCredentialsSource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageCredentialsSource field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageCredentialsSource(value string) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageCredentialsSource = &value
	return b
}

// WithCloudStorageDisableTLS sets the CloudStorageDisableTLS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageDisableTLS field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageDisableTLS(value bool) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageDisableTLS = &value
	return b
}

// WithCloudStorageEnableRemoteRead sets the CloudStorageEnableRemoteRead field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageEnableRemoteRead field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageEnableRemoteRead(value bool) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageEnableRemoteRead = &value
	return b
}

// WithCloudStorageEnableRemoteWrite sets the CloudStorageEnableRemoteWrite field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageEnableRemoteWrite field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageEnableRemoteWrite(value bool) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageEnableRemoteWrite = &value
	return b
}

// WithCloudStorageInitialBackoffMs sets the CloudStorageInitialBackoffMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageInitialBackoffMs field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageInitialBackoffMs(value int) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageInitialBackoffMs = &value
	return b
}

// WithCloudStorageManifestUploadTimeoutMs sets the CloudStorageManifestUploadTimeoutMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageManifestUploadTimeoutMs field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageManifestUploadTimeoutMs(value int) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageManifestUploadTimeoutMs = &value
	return b
}

// WithCloudStorageMaxConnectionIdleTimeMs sets the CloudStorageMaxConnectionIdleTimeMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageMaxConnectionIdleTimeMs field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageMaxConnectionIdleTimeMs(value int) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageMaxConnectionIdleTimeMs = &value
	return b
}

// WithCloudStorageMaxConnections sets the CloudStorageMaxConnections field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageMaxConnections field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageMaxConnections(value int) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageMaxConnections = &value
	return b
}

// WithCloudStorageRegion sets the CloudStorageRegion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageRegion field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageRegion(value string) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageRegion = &value
	return b
}

// WithCloudStorageSegmentMaxUploadIntervalSec sets the CloudStorageSegmentMaxUploadIntervalSec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageSegmentMaxUploadIntervalSec field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageSegmentMaxUploadIntervalSec(value int) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageSegmentMaxUploadIntervalSec = &value
	return b
}

// WithCloudStorageSegmentUploadTimeoutMs sets the CloudStorageSegmentUploadTimeoutMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageSegmentUploadTimeoutMs field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageSegmentUploadTimeoutMs(value int) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageSegmentUploadTimeoutMs = &value
	return b
}

// WithCloudStorageTrustFile sets the CloudStorageTrustFile field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageTrustFile field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageTrustFile(value string) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageTrustFile = &value
	return b
}

// WithCloudStorageUploadCtrlDCoeff sets the CloudStorageUploadCtrlDCoeff field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageUploadCtrlDCoeff field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageUploadCtrlDCoeff(value int) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageUploadCtrlDCoeff = &value
	return b
}

// WithCloudStorageUploadCtrlMaxShares sets the CloudStorageUploadCtrlMaxShares field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageUploadCtrlMaxShares field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageUploadCtrlMaxShares(value int) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageUploadCtrlMaxShares = &value
	return b
}

// WithCloudStorageUploadCtrlMinShares sets the CloudStorageUploadCtrlMinShares field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageUploadCtrlMinShares field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageUploadCtrlMinShares(value int) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageUploadCtrlMinShares = &value
	return b
}

// WithCloudStorageUploadCtrlPCoeff sets the CloudStorageUploadCtrlPCoeff field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageUploadCtrlPCoeff field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageUploadCtrlPCoeff(value int) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageUploadCtrlPCoeff = &value
	return b
}

// WithCloudStorageUploadCtrlUpdateIntervalMs sets the CloudStorageUploadCtrlUpdateIntervalMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CloudStorageUploadCtrlUpdateIntervalMs field is set to the value of the last call.
func (b *StretchTieredConfigApplyConfiguration) WithCloudStorageUploadCtrlUpdateIntervalMs(value int) *StretchTieredConfigApplyConfiguration {
	b.CloudStorageUploadCtrlUpdateIntervalMs = &value
	return b
}
