// Copyright 2025 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// TopicPartitionInformationApplyConfiguration represents a declarative configuration of the TopicPartitionInformation type for use
// with apply.
type TopicPartitionInformationApplyConfiguration struct {
	PartitionID            *int64 `json:"partitionId,omitempty"`
	SourceLastStableOffset *int64 `json:"sourceLastStableOffset,omitempty"`
	SourceHighWatermark    *int64 `json:"sourceHighWatermark,omitempty"`
	HighWatermark          *int64 `json:"highWatermark,omitempty"`
}

// TopicPartitionInformationApplyConfiguration constructs a declarative configuration of the TopicPartitionInformation type for use with
// apply.
func TopicPartitionInformation() *TopicPartitionInformationApplyConfiguration {
	return &TopicPartitionInformationApplyConfiguration{}
}

// WithPartitionID sets the PartitionID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PartitionID field is set to the value of the last call.
func (b *TopicPartitionInformationApplyConfiguration) WithPartitionID(value int64) *TopicPartitionInformationApplyConfiguration {
	b.PartitionID = &value
	return b
}

// WithSourceLastStableOffset sets the SourceLastStableOffset field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceLastStableOffset field is set to the value of the last call.
func (b *TopicPartitionInformationApplyConfiguration) WithSourceLastStableOffset(value int64) *TopicPartitionInformationApplyConfiguration {
	b.SourceLastStableOffset = &value
	return b
}

// WithSourceHighWatermark sets the SourceHighWatermark field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceHighWatermark field is set to the value of the last call.
func (b *TopicPartitionInformationApplyConfiguration) WithSourceHighWatermark(value int64) *TopicPartitionInformationApplyConfiguration {
	b.SourceHighWatermark = &value
	return b
}

// WithHighWatermark sets the HighWatermark field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HighWatermark field is set to the value of the last call.
func (b *TopicPartitionInformationApplyConfiguration) WithHighWatermark(value int64) *TopicPartitionInformationApplyConfiguration {
	b.HighWatermark = &value
	return b
}
