// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

import (
	v1 "k8s.io/api/core/v1"
)

// TrustStoreApplyConfiguration represents a declarative configuration of the TrustStore type for use
// with apply.
type TrustStoreApplyConfiguration struct {
	ConfigMapKeyRef *v1.ConfigMapKeySelector `json:"configMapKeyRef,omitempty"`
	SecretKeyRef    *v1.SecretKeySelector    `json:"secretKeyRef,omitempty"`
}

// TrustStoreApplyConfiguration constructs a declarative configuration of the TrustStore type for use with
// apply.
func TrustStore() *TrustStoreApplyConfiguration {
	return &TrustStoreApplyConfiguration{}
}

// WithConfigMapKeyRef sets the ConfigMapKeyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMapKeyRef field is set to the value of the last call.
func (b *TrustStoreApplyConfiguration) WithConfigMapKeyRef(value v1.ConfigMapKeySelector) *TrustStoreApplyConfiguration {
	b.ConfigMapKeyRef = &value
	return b
}

// WithSecretKeyRef sets the SecretKeyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretKeyRef field is set to the value of the last call.
func (b *TrustStoreApplyConfiguration) WithSecretKeyRef(value v1.SecretKeySelector) *TrustStoreApplyConfiguration {
	b.SecretKeyRef = &value
	return b
}
