// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// UsersItemsApplyConfiguration represents a declarative configuration of the UsersItems type for use
// with apply.
type UsersItemsApplyConfiguration struct {
	Mechanism *string `json:"mechanism,omitempty"`
	Name      *string `json:"name,omitempty"`
	Password  *string `json:"password,omitempty"`
}

// UsersItemsApplyConfiguration constructs a declarative configuration of the UsersItems type for use with
// apply.
func UsersItems() *UsersItemsApplyConfiguration {
	return &UsersItemsApplyConfiguration{}
}

// WithMechanism sets the Mechanism field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mechanism field is set to the value of the last call.
func (b *UsersItemsApplyConfiguration) WithMechanism(value string) *UsersItemsApplyConfiguration {
	b.Mechanism = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *UsersItemsApplyConfiguration) WithName(value string) *UsersItemsApplyConfiguration {
	b.Name = &value
	return b
}

// WithPassword sets the Password field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Password field is set to the value of the last call.
func (b *UsersItemsApplyConfiguration) WithPassword(value string) *UsersItemsApplyConfiguration {
	b.Password = &value
	return b
}
