apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: false
kindContainers:
  - localhost/redpanda-operator:dev
  - localhost/redpanda:dev
testDirs:
  - ./tests/e2e
kindConfig: ./kind.yaml
kindNodeCache: false
commands:
  - command: "sh -c 'until kustomize build config/e2e-tests 2>> tests/_e2e_artifacts/kustomize-output.txt | kubectl apply --server-side -f - 1>> tests/_e2e_artifacts/kubectl-output.txt 2>> tests/_e2e_artifacts/kubectl-error-output.txt; do sleep 0.5; done'"
    background: true
  - command: "./hack/wait-for-webhook-ready.sh"
artifactsDir: tests/_e2e_artifacts
timeout: 330
reportFormat: xml
parallel: 2
namespace: redpanda-system
suppress:
  - events
