apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
kindContainers:
  - localhost/redpanda-operator:dev
testDirs:
  - ./tests/e2e-v2
kindConfig: ./kind-for-v2.yaml
kindNodeCache: false
commands:
  - command: mkdir -p tests/_e2e_artifacts_v2
  - command: kubectl taint nodes -l node-role.kubernetes.io/master:NoSchedule-
    ignoreFailure: true
  - command: ./hack/install-cert-manager.sh tests/_e2e_artifacts_v2
  - script: kubectl kustomize ./config/crd | kubectl apply --server-side -f -
  - command: helm install redpanda-operator ../charts/operator
      --dependency-update --namespace redpanda --create-namespace --wait
      --set logLevel=trace --set image.tag=dev --set image.repository=localhost/redpanda-operator
      --set additionalCmdFlags="{--additional-controllers=all}"
      --set rbac.createAdditionalControllerCRs=true --set rbac.createRPKBundleCRs=true
artifactsDir: tests/_e2e_artifacts_v2
timeout: 720
reportFormat: xml
parallel: 1
namespace: redpanda
suppress:
  - events
