apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
kindContainers:
  - localhost/redpanda-operator:dev
  - localhost/configurator:dev
  - localhost/redpanda:dev
testDirs:
  - ./tests/e2e
kindConfig: ./kind.yaml
kindNodeCache: false
commands:
  - command: kubectl taint node kind-control-plane node-role.kubernetes.io/control-plane-
  - command: "mkdir -p tests/_e2e_artifacts"
  - command: "./hack/install-cert-manager.sh tests/_e2e_artifacts"
    background: true
    ignoreFailure: true
  - command: "kubectl create -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/e23ff77fceba6a5d9f190f5d1a123c87701dc964/bundle.yaml"
    background: true
    ignoreFailure: true
  - command: "sh -c 'until kustomize build config/e2e-tests 2>> tests/_e2e_artifacts/kustomize-output.txt | kubectl apply --server-side -f - 1>> tests/_e2e_artifacts/kubectl-output.txt 2>> tests/_e2e_artifacts/kubectl-error-output.txt; do sleep 0.5; done'"
    background: true
  - command: "./hack/wait-for-webhook-ready.sh"
artifactsDir: tests/_e2e_artifacts
timeout: 330
reportFormat: xml
parallel: 2
namespace: redpanda-system
suppress:
  - events
