// Copyright 2024 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Package run contains the boilerplate code to configure and run the redpanda
// operator.
package run

import (
	"context"
	"errors"
	"log"
	"net/http"
	"net/http/pprof"
	"time"

	cmapiv1 "github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1"
	helmControllerAPIv2beta1 "github.com/fluxcd/helm-controller/api/v2beta1"
	helmControllerAPIv2beta2 "github.com/fluxcd/helm-controller/api/v2beta2"
	"github.com/fluxcd/pkg/runtime/logger"
	sourceControllerAPIv1 "github.com/fluxcd/source-controller/api/v1"
	sourceControllerAPIv1beta2 "github.com/fluxcd/source-controller/api/v1beta2"
	"github.com/go-logr/logr"
	"github.com/spf13/cobra"
	"helm.sh/helm/v3/pkg/getter"
	"helm.sh/helm/v3/pkg/kube"
	"k8s.io/apimachinery/pkg/runtime"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	_ "k8s.io/client-go/plugin/pkg/client/auth"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/cache"
	metricsserver "sigs.k8s.io/controller-runtime/pkg/metrics/server"

	redpandav1alpha1 "github.com/redpanda-data/redpanda-operator/src/go/k8s/api/redpanda/v1alpha1"
	redpandav1alpha2 "github.com/redpanda-data/redpanda-operator/src/go/k8s/api/redpanda/v1alpha2"
	vectorizedv1alpha1 "github.com/redpanda-data/redpanda-operator/src/go/k8s/api/vectorized/v1alpha1"
)

type RedpandaController string

type OperatorState string

func (r RedpandaController) toString() string {
	return string(r)
}

const (
	defaultConfiguratorContainerImage = "vectorized/configurator"

	AllControllers         = RedpandaController("all")
	NodeController         = RedpandaController("nodeWatcher")
	DecommissionController = RedpandaController("decommission")

	OperatorV1Mode          = OperatorState("Clustered-v1")
	OperatorV2Mode          = OperatorState("Namespaced-v2")
	NamespaceControllerMode = OperatorState("Namespaced-Controllers")

	controllerName               = "redpanda-controller"
	helmReleaseControllerName    = "redpanda-helmrelease-controller"
	helmChartControllerName      = "redpanda-helmchart-reconciler"
	helmRepositoryControllerName = "redpanda-helmrepository-controller"
)

var (
	scheme  = runtime.NewScheme()
	getters = getter.Providers{
		getter.Provider{
			Schemes: []string{"http", "https"},
			New:     getter.NewHTTPGetter,
		},
		getter.Provider{
			Schemes: []string{"oci"},
			New:     getter.NewOCIGetter,
		},
	}

	storageAdvAddr string

	availableControllers = []string{
		NodeController.toString(),
		DecommissionController.toString(),
	}
)

//nolint:wsl // the init was generated by kubebuilder
func init() {
	utilruntime.Must(clientgoscheme.AddToScheme(scheme))
	utilruntime.Must(cmapiv1.AddToScheme(scheme))
	utilruntime.Must(helmControllerAPIv2beta1.AddToScheme(scheme))
	utilruntime.Must(helmControllerAPIv2beta2.AddToScheme(scheme))
	utilruntime.Must(redpandav1alpha1.AddToScheme(scheme))
	utilruntime.Must(redpandav1alpha2.AddToScheme(scheme))
	utilruntime.Must(sourceControllerAPIv1.AddToScheme(scheme))
	utilruntime.Must(sourceControllerAPIv1beta2.AddToScheme(scheme))
	utilruntime.Must(vectorizedv1alpha1.AddToScheme(scheme))
	//+kubebuilder:scaffold:scheme
}

// +kubebuilder:rbac:groups=coordination.k8s.io,namespace=default,resources=leases,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,namespace=default,resources=configmaps,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=core,namespace=default,resources=events,verbs=create;patch

func Command() *cobra.Command {
	runner := newRunner()

	cmd := &cobra.Command{
		Use:   "run",
		Short: "Run the redpanda operator",
		Run: func(cmd *cobra.Command, args []string) {
			runner.Run()
		},
	}

	return runner.register(cmd)
}

type runner struct {
	*flags
	setupLog logr.Logger
}

func newRunner() *runner {
	return &runner{flags: &flags{}, setupLog: ctrl.Log.WithName("setup")}
}

func (r *runner) Run() {
	if err := r.run(); err != nil {
		err.Log(r.setupLog)
	}
}

func (r *runner) run() *SetupError {
	ctrl.SetLogger(logger.NewLogger(r.logOptions))

	// set the managedFields owner for resources reconciled from Helm charts
	kube.ManagedFieldsManager = controllerName

	r.maybeRunPProf()

	mgr, err := r.initializeManager()
	if err != nil {
		return err
	}

	ctx := ctrl.SetupSignalHandler()

	if err := r.addOperatorReconcilers(ctx, mgr); err != nil {
		return err
	}

	if err := r.addHealthChecks(mgr); err != nil {
		return err
	}

	if err := r.maybeAddWebhooks(mgr); err != nil {
		return err
	}

	r.setupLog.Info("Starting manager")
	return setupError(mgr.Start(ctx), "Problem running manager")
}

func (r *runner) maybeRunPProf() {
	if r.debug {
		go func() {
			pprofMux := http.NewServeMux()
			pprofMux.HandleFunc("/debug/pprof/", pprof.Index)
			pprofMux.HandleFunc("/debug/pprof/cmdline", pprof.Cmdline)
			pprofMux.HandleFunc("/debug/pprof/profile", pprof.Profile)
			pprofMux.HandleFunc("/debug/pprof/symbol", pprof.Symbol)
			pprofMux.HandleFunc("/debug/pprof/trace", pprof.Trace)
			pprofServer := &http.Server{
				Addr:              r.pprofAddr,
				Handler:           pprofMux,
				ReadHeaderTimeout: 3 * time.Second,
			}
			log.Fatal(pprofServer.ListenAndServe())
		}()
	}
}

func (r *runner) initializeManager() (ctrl.Manager, *SetupError) {
	mgrOptions := ctrl.Options{
		Scheme:                  scheme,
		Metrics:                 metricsserver.Options{BindAddress: r.metricsAddr},
		HealthProbeBindAddress:  r.probeAddr,
		LeaderElection:          r.enableLeaderElection,
		LeaderElectionID:        "aa9fc693.vectorized.io",
		LeaderElectionNamespace: r.namespace,
	}
	if r.namespace != "" {
		mgrOptions.Cache.DefaultNamespaces = map[string]cache.Config{r.namespace: {}}
	}

	config, err := ctrl.GetConfig()
	if err != nil {
		return nil, setupError(err, "Unable to fetch kubernetes config")
	}

	mgr, err := ctrl.NewManager(config, mgrOptions)
	if err != nil {
		return nil, setupError(err, "Unable to setup manager")
	}

	return mgr, nil
}

func (r *runner) addOperatorReconcilers(ctx context.Context, mgr ctrl.Manager) *SetupError {
	// init running state values if we are not in operator mode
	var operatorRunningState OperatorState
	if r.namespace != "" {
		operatorRunningState = NamespaceControllerMode
	}

	// but if we are in operator mode, then the run state is different
	if r.operatorMode {
		operatorRunningState = OperatorV1Mode
		if r.namespace != "" {
			operatorRunningState = OperatorV2Mode
		}
	}

	// Now we start different processes depending on state
	switch operatorRunningState {
	case OperatorV1Mode:
		r.setV1Globals()
		return r.addV1Reconcilers(mgr)
	case OperatorV2Mode:
		return r.addV2Reconcilers(ctx, mgr)
	case NamespaceControllerMode:
		return r.addNamespaceReconcilers(mgr)
	}
	return setupError(errors.New("not supported"), "Unable to start operator with unknown state", "state", operatorRunningState)
}

func runThisController(rc RedpandaController, controllers []string) bool {
	if len(controllers) == 0 {
		return false
	}

	for _, c := range controllers {
		if RedpandaController(c) == AllControllers || RedpandaController(c) == rc {
			return true
		}
	}
	return false
}
