name: Auto-Approve Backport

on:
  pull_request_target:
    branches-ignore:
      - main

jobs:
  approve:
    name: Auto-approve backport
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'backport/') && (github.actor == 'vbotbuildovich')
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4