name: Changelog

on:
  pull_request:
    types: ["labeled", "unlabeled", "opened", "synchronize"]
    branches:
      # only check for changelog entries going into main 
      - main

jobs:
  changed_files:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no-changelog') }}
    runs-on: ubuntu-latest
    name: Check for changelog entry
    steps:
      - uses: actions/checkout@v4

      - name: Get all changed changelog files
        id: changed-changelog-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            .changes/unreleased/**.yaml

      - name: Pass
        if: steps.changed-changelog-files.outputs.any_changed == 'true'
        run: |
          echo "Found changelog entry"

      - name: Fail
        if: steps.changed-changelog-files.outputs.any_changed != 'true'
        run: |
          cat <<EOF
          No changelog entry detected.
          If this PR has user facing changes, ensure that a change log entry as been added via changie. See CONTRIBUTING.md for details.
          If this PR does not have user facing changes, label the PR with "no-changelog" through GitHub's UI.
          EOF
          exit 1
