---
# This workflow triggers the action in redpanda-data/docs that
# publishes the CRD and Helm chart specifications to the Redpanda documentation.
# https://github.com/redpanda-data/docs/blob/main/.github/workflows/generate-crd.yml

name: Trigger Kubernetes reference docs
on:
  release:
    types: [published]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.RP_AWS_CRED_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.RP_AWS_CRED_ACCOUNT_ID }}:role/${{ vars.RP_AWS_CRED_BASE_ROLE_NAME }}${{ github.event.repository.name }}
      - uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,sdlc/prod/github/actions_bot_token
          parse-json-secrets: true
      - name: Trigger generate-crd-docs event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ env.ACTIONS_BOT_TOKEN }}
          repository: redpanda-data/docs
          event-type: generate-crd-docs
