---
# This workflow triggers the action in redpanda-data/docs that
# publishes the CRD specifications to the Redpanda documentation.

name: Trigger CRD docs
on:
  push:
    branches: [main]
    paths:
      - 'src/k8s/api/**'
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_SM_READONLY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SM_READONLY_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: get secrets from aws sm
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,sdlc/prod/github/actions_bot_token
          parse-json-secrets: true
      - name: Trigger generate-crd-docs event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ env.ACTIONS_BOT_TOKEN }}
          repository: redpanda-data/docs
          event-type: generate-crd-docs
