---
name: Lint golang
on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/go/**'
    tags-ignore:
      - '**'
  pull_request:
    paths:
      - 'src/go/**'
env:
  GOPRIVATE: github.com/redpanda-data/*
jobs:
  go:
    name: Lint go files
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_SM_READONLY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SM_READONLY_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: get secrets from aws sm
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ,sdlc/prod/github/actions_bot_token
          parse-json-secrets: true
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Install gofumpt
        env:
          GOFUMPT_VER: 0.5.0
        run: |
          mkdir -v -p "$HOME/.local/bin"
          wget -O "$HOME/.local/bin/gofumpt" "https://github.com/mvdan/gofumpt/releases/download/v${GOFUMPT_VER}/gofumpt_v${GOFUMPT_VER}_linux_amd64"
          chmod 0700 "$HOME/.local/bin/gofumpt"
      - name: Run gofumpt
        run: |
          find src/go -type f -not -name 'zz*' -name '*.go' | xargs -n1 "$HOME/.local/bin/gofumpt" -w -lang=1.21
          git diff --exit-code
      - name: configure git
        run: git config --global "url.https://$ACTIONS_BOT_TOKEN@github.com/.insteadOf" https://github.com/
      - name: go mod tidy (k8s)
        working-directory: src/go/k8s
        run: |
          GOPRIVATE=github.com/redpanda-data/* go mod tidy
          git diff --exit-code -- go.mod go.sum
