name: Pull Requests Checks

on:
  pull_request:
    branches:
      - "**"

defaults:
  run:
    shell: nix develop --impure --command bash {0}

env:
  GOPRIVATE: github.com/redpanda-data/*

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v26
      with:
        github_access_token: ${{ secrets.ACTIONS_BOT_TOKEN }}

    - uses: actions/checkout@v4

    - name: configure git
      env:
        GH_ACCESS_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
      run: |
        git config --global "url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf" https://github.com/

    - name: Run task ci:lint
      run: |
        task ci:lint
