// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

package bootstrap

import (
	"fmt"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// GenerateBootstrapObjects returns the Kubernetes resources the bootstrap
// command would create on each remote cluster, keyed by context name. It
// makes no cluster calls; callers (e.g. `rpk k8s multicluster bootstrap
// --output=yaml`) can render the result to YAML for GitOps workflows.
//
// Only resources the operator cannot self-generate at runtime are emitted:
// the operator Namespace (when EnsureNamespace is set) and the TLS Secret
// (when BootstrapTLS is set). The ServiceAccount, the SA token Secret, and
// the per-peer kubeconfig cache Secrets are regenerated by the operator on
// startup (startupKubeconfigFetcher) and on leader-routine fallback, so
// pre-seeding them here would at best be a stale snapshot.
//
// Each RemoteConfiguration is expected to have a ServiceAddress set; this
// function does not provision LoadBalancers. Callers should validate that
// constraint up front.
func GenerateBootstrapObjects(organization string, configuration BootstrapClusterConfiguration) (map[string][]client.Object, error) {
	out := make(map[string][]client.Object, len(configuration.RemoteClusters))

	var ca *CACertificate
	if configuration.BootstrapTLS {
		var err error
		ca, err = GenerateCA(organization, "Root CA", nil)
		if err != nil {
			return nil, fmt.Errorf("generating CA: %w", err)
		}
	}

	for _, cluster := range configuration.RemoteClusters {
		var objs []client.Object

		if configuration.EnsureNamespace {
			objs = append(objs, &corev1.Namespace{
				TypeMeta: metav1.TypeMeta{
					APIVersion: "v1",
					Kind:       "Namespace",
				},
				ObjectMeta: metav1.ObjectMeta{
					Name: configuration.OperatorNamespace,
				},
			})
		}

		if configuration.BootstrapTLS {
			serviceFQDN, err := cluster.FQDN(configuration)
			if err != nil {
				return nil, fmt.Errorf("resolving FQDN for %s: %w", cluster.ContextName, err)
			}
			cert, err := ca.Sign(serviceFQDN)
			if err != nil {
				return nil, fmt.Errorf("signing certificate for %s: %w", cluster.ContextName, err)
			}
			tlsName := cluster.Name
			if tlsName == "" {
				tlsName = configuration.ServiceName
			}
			objs = append(objs, &corev1.Secret{
				TypeMeta: metav1.TypeMeta{
					APIVersion: "v1",
					Kind:       "Secret",
				},
				ObjectMeta: metav1.ObjectMeta{
					Name:      tlsName + "-multicluster-certificates",
					Namespace: configuration.OperatorNamespace,
				},
				Data: map[string][]byte{
					"ca.crt":  ca.Bytes(),
					"tls.crt": cert.Bytes(),
					"tls.key": cert.PrivateKeyBytes(),
				},
			})
		}

		if len(objs) > 0 {
			out[cluster.ContextName] = objs
		}
	}

	return out, nil
}

// GenerateLoadBalancerObjects returns a per-cluster LoadBalancer Service that
// the bootstrap command would create when --loadbalancer is set. The Services
// use the same naming, labels, selector, and port configuration as
// EnsurePeerLoadBalancer so they are fully compatible with the live-apply path.
//
// This is the first half of a two-step GitOps workflow:
//  1. bootstrap --output=yaml --loadbalancer → apply Services, wait for IPs
//  2. bootstrap --output=yaml --dns-override … → apply Namespace + TLS Secrets
func GenerateLoadBalancerObjects(configuration BootstrapClusterConfiguration) map[string][]client.Object {
	out := make(map[string][]client.Object, len(configuration.RemoteClusters))

	for _, cluster := range configuration.RemoteClusters {
		instance := cluster.Name
		if instance == "" {
			instance = configuration.ServiceName
		}
		name := peerLoadBalancerName(cluster, configuration)

		svc := &corev1.Service{
			TypeMeta: metav1.TypeMeta{
				APIVersion: "v1",
				Kind:       "Service",
			},
			ObjectMeta: metav1.ObjectMeta{
				Name:      name,
				Namespace: configuration.OperatorNamespace,
				Labels: map[string]string{
					LoadBalancerLabelKey:         "true",
					"app.kubernetes.io/name":     configuration.ServiceName,
					"app.kubernetes.io/instance": instance,
				},
			},
			Spec: corev1.ServiceSpec{
				Type: corev1.ServiceTypeLoadBalancer,
				Selector: map[string]string{
					"app.kubernetes.io/name":     configuration.ServiceName,
					"app.kubernetes.io/instance": instance,
				},
				PublishNotReadyAddresses: true,
				Ports: []corev1.ServicePort{{
					Name:       "raft",
					Protocol:   corev1.ProtocolTCP,
					Port:       PeerLoadBalancerPort,
					TargetPort: intstr.FromInt(PeerLoadBalancerPort),
				}},
			},
		}

		out[cluster.ContextName] = []client.Object{svc}
	}

	return out
}
